import {createRoot} from 'react-dom/client'
import {ThemeProvider} from '../src/theme'
import ClientAdminPage from '../src/ClientAdminPage'
import '../src/styles.css'
import '../src/v3-system.css'
import '../src/theme.css'
import '../src/liquid-glass.css'
import './design-review.css'
const previewStyle=document.createElement('style');previewStyle.textContent='.wf-theme-toggle.floating{display:none}';document.head.append(previewStyle);
const today=new Date();const date=(offset:number)=>new Date(today.getTime()+offset*86400000).toISOString();
const site:any={siteId:'preview-business',slug:'preview-business',status:'active',revision:1,business:{name:'Negocio de ejemplo',nameEn:'Sample business',nameEs:'Negocio de ejemplo',category:'Professional services',description:'Datos de ejemplo para evaluar el diseño.'},design:{primary:'#0B1529',secondary:'#3C86F6',style:'Modern'},catalog:Array.from({length:12},(_,i)=>({id:`item-${i}`,type:'service',name:`Servicio ${i+1}`,price:45,active:true,inventory:null,requiresAppointment:true,duration:30,bufferMinutes:0})),employees:[{id:'one',name:'Profesional de ejemplo',role:'Professional',active:true,serviceIds:[],calendarId:'',dailyLimit:8,schedule:{},timeOff:[]}],hours:{},paymentRules:{},googleCalendar:{},settings:{locale:'en',timezone:'America/Puerto_Rico',currency:'USD'},servicePlan:{name:'WebFactory Commerce Platform',billingModel:'subscription',subscriptionStatus:'active',billingStatus:'active'}};
const names=['Cliente de ejemplo A','Cliente de ejemplo B','Cliente de ejemplo C'];
const orders=Array.from({length:7},(_,i)=>({transactionId:`order-${i}`,kind:'order',customer:{name:names[i%3],email:`sample${i%3}@example.invalid`},items:[{name:'Servicio de ejemplo',quantity:1,unitAmount:5000}],amountTotal:[4500,7500,12000,8000,6000,16000,10500][i],paymentStatus:'paid',status:'completed',createdAt:date(i-6)}));
const bookings=names.map((name,i)=>({transactionId:`booking-${i}`,kind:'booking',customer:{name,email:`sample${i}@example.invalid`},items:[],amountTotal:4500,paymentStatus:'pending',status:'confirmed',start:date(i+1),createdAt:date(-i)}));
// Preview-only: ?caps=orders,bookings simulates a staff member limited to those capabilities.
const caps=new URLSearchParams(location.search).get('caps');const membership=caps?{role:'staff',capabilities:caps.split(',').filter(Boolean)}:{role:'owner'};
// This entire entry is preview-only. No request can reach a real backend.
window.fetch=async(input,init)=>{const url=String(input);if(!url.includes('/.netlify/functions/'))throw new Error('External requests are disabled in this preview.');let result:any={ok:true,records:[],customers:[]};if(url.includes('client-admin'))result=url.includes('siteId=')||init?.method==='PATCH'?{ok:true,site,membership}:{ok:true,sites:[{siteId:site.siteId,slug:site.slug,businessName:site.business.name,status:site.status}]};if(url.includes('client-business-accounting'))result={ok:true,revision:0,report:{summary:{estimatedRevenueCents:0,salaryCents:9600,operatingCents:0,materialsCents:0,purchaseCents:0,estimatedResultCents:-9600,regularMinutes:480,overtimeMinutes:0,paidCents:0,pendingCents:9600,unassignedRevenueCents:0},employees:[{employeeId:'one',name:'Profesional de ejemplo',hourlyCents:1200,regularMinutes:480,overtimeMinutes:0,salaryCents:9600,commissionCents:0,tipCents:0,grossCents:9600,paidCents:0,pendingCents:9600,estimatedRevenueCents:0}],inventory:[],work:[],expenses:[],entries:[],sales:[]}};if(url.includes('client-commerce-admin'))result={ok:true,orders,bookings};if(url.includes('subscription-readiness'))result={ok:true,readiness:{ready:true},entitlement:{public:true},servicePlan:site.servicePlan};if(init?.method&&!['GET','HEAD'].includes(init.method)&&init.method!=='PATCH')throw new Error('Preview: this action is disabled. Use Training to practice.');return new Response(JSON.stringify(result),{headers:{'Content-Type':'application/json'}})};
createRoot(document.getElementById('root')!).render(<ThemeProvider><aside className="design-review-banner" role="note"><span className="design-review-en">Design preview · Sample data · No real transactions</span><span className="design-review-es">Preview de diseño · Datos de ejemplo · Sin transacciones reales</span><a href="/"><span className="design-review-en">View homepage</span><span className="design-review-es">Ver homepage</span></a></aside><ClientAdminPage/></ThemeProvider>);
