import test from 'node:test';
import assert from 'node:assert/strict';
import { cleanupAuthExpiry,indexAuthExpiry } from './auth-expiry.mjs';
import cleanupHandler from '../functions/cleanup-auth-sessions.mjs';
function store(){const data=new Map();return {data,async get(key){return structuredClone(data.get(key)||null)},async setJSON(key,value,options={}){if(options.onlyIfNew&&data.has(key))return {modified:false};data.set(key,structuredClone(value));return {modified:true}},async delete(key){data.delete(key)},list({prefix,directories}){const keys=[...data.keys()].filter(key=>key.startsWith(prefix));return (async function*(){if(directories){yield {directories:[...new Set(keys.map(key=>prefix+key.slice(prefix.length).split('/')[0]+'/'))],blobs:[]};return;}for(let i=0;i<keys.length;i+=2)yield {blobs:keys.slice(i,i+2).map(key=>({key}))};})()}};}
const prefix=`users/${'a'.repeat(64)}/`,session=`${prefix}sessions/${'b'.repeat(64)}.json`;
const now=Date.parse('2026-10-02T14:30:00Z');
test('expiry collection removes only expired indexed records, preserving live sessions and credentials',async()=>{const s=store();s.data.set(session,{expiresAt:now-7200000});await indexAuthExpiry(s,session,now-7200000);const live=`${prefix}sessions/${'c'.repeat(64)}.json`;s.data.set(live,{expiresAt:now+3600000});await indexAuthExpiry(s,live,now+3600000);s.data.set(`${prefix}profile.json`,{credentials:['public-key']});const result=await cleanupAuthExpiry(s,{now});assert.equal(result.deleted,1);assert.ok(s.data.has(live));assert.ok(s.data.has(`${prefix}profile.json`));assert.ok(!s.data.has(session));});
test('index cannot delete a profile, another store key, or a renewed session',async()=>{const s=store();s.data.set(session,{expiresAt:now+3600000});await indexAuthExpiry(s,session,now-7200000);await indexAuthExpiry(s,`${prefix}profile.json`,now-7200000);await indexAuthExpiry(s,'foreign/private.json',now-7200000);const result=await cleanupAuthExpiry(s,{now});assert.equal(result.deleted,0);assert.equal(result.invalid,3);assert.ok(s.data.has(session));});
test('bounded cleanup resumes by deleting processed indexes and handles orphaned indexes',async()=>{const s=store();for(let i=0;i<5;i++)await indexAuthExpiry(s,`${prefix}sessions/${String(i).padStart(64,'0')}.json`,now-7200000);const first=await cleanupAuthExpiry(s,{now,maxRecords:2});assert.equal(first.paused,true);assert.equal(first.indexesDeleted,2);const second=await cleanupAuthExpiry(s,{now});assert.equal(second.indexesDeleted,3);assert.equal(second.deleted,0);});
test('current-hour indexes wait until the next hour and preview schedule cannot touch a store',async()=>{const s=store();await indexAuthExpiry(s,session,now-1000);assert.equal((await cleanupAuthExpiry(s,{now})).scanned,0);assert.equal((await cleanupAuthExpiry(s,{now:now+3600000})).indexesDeleted,1);await cleanupHandler(new Request('https://example.com'),{deploy:{context:'deploy-preview',published:false}});});
test('an account lock prevents deleting an in-flight record and the cleanup budget limits storage work',async()=>{const s=store();s.data.set(session,{expiresAt:now-7200000});await indexAuthExpiry(s,session,now-7200000);s.data.set(`${prefix}lock`,{owner:'active-request',expiresAt:Date.now()+120000});s.getWithMetadata=async key=>({data:await s.get(key),etag:'etag'});assert.equal((await cleanupAuthExpiry(s,{now})).deleted,0);assert.ok(s.data.has(session));s.data.delete(`${prefix}lock`);let time=0;const result=await cleanupAuthExpiry(s,{now,clock:()=>time+=1000,budgetMs:1});assert.equal(result.paused,true);assert.equal(result.deleted,0);});
test('expired Authenticator attempt limits are collected but renewed limits survive stale indexes',async()=>{const s=store(),key=`${prefix}totp-attempts.json`;s.data.set(key,{failures:5,expiresAt:now-7200000});await indexAuthExpiry(s,key,now-7200000);assert.equal((await cleanupAuthExpiry(s,{now})).deleted,1);s.data.set(key,{failures:2,expiresAt:now+300000});await indexAuthExpiry(s,key,now-7200000);assert.equal((await cleanupAuthExpiry(s,{now})).deleted,0);assert.ok(s.data.has(key))});
