import test from 'node:test';
import assert from 'node:assert/strict';
import {createShadcnCatalog} from './chatgpt-shadcn.mjs';
const registry={items:[{name:'button',type:'registry:ui',description:'Action button'},{name:'login-01',type:'registry:block',description:'Login form'}]};
const button={name:'button',type:'registry:ui',dependencies:['radix-ui'],registryDependencies:['utils'],files:[{path:'ui/button.tsx',type:'registry:ui',content:'public component source'},{path:'ui/helper.ts',content:'helper'}]};
function fixture(){const calls=[];let time=0;const client=createShadcnCatalog({now:()=>time,fetchImpl:async(url,options)=>{calls.push({url,options});return Response.json(url.endsWith('/registry.json')?registry:button)}});return {client,calls,advance:()=>time+=300001};}
test('official catalog search is bounded, paginated, cached and credential-free',async()=>{const {client,calls,advance}=fixture();const page=await client.search({limit:1});assert.equal(page.total,2);assert.equal(page.nextOffset,1);assert.equal((await client.search({query:'LOGIN'})).items[0].name,'login-01');assert.equal(calls.length,1);assert.equal(calls[0].url,'https://ui.shadcn.com/r/styles/new-york-v4/registry.json');assert.equal(calls[0].options.credentials,'omit');assert.equal(calls[0].options.redirect,'error');assert.deepEqual(calls[0].options.headers,{Accept:'application/json'});advance();await client.search();assert.equal(calls.length,2);});
test('public source excerpts can be paged and only exact component files selected',async()=>{const {client,calls}=fixture();const result=await client.component({name:'button',limit:6});assert.equal(result.selectedFile.content,'public');assert.equal(result.selectedFile.nextOffset,6);assert.deepEqual(result.dependencies,['radix-ui']);assert.equal((await client.component({name:'button',filePath:'ui/helper.ts'})).selectedFile.content,'helper');await assert.rejects(client.component({name:'button',filePath:'/etc/passwd'}),{status:404});assert(calls.every(call=>call.url.startsWith('https://ui.shadcn.com/r/styles/new-york-v4/')));});
test('names, bounds and unknown catalog entries reject before component fetch',async()=>{const {client,calls}=fixture();for(const name of ['../button','https://evil.test','Button','button?token=x','button/../x'])await assert.rejects(client.component({name}),{status:400});assert.equal(calls.length,0);await assert.rejects(client.component({name:'unknown'}),{status:404});assert.equal(calls.length,1);for(const args of [{limit:31},{offset:-1},{query:'x'.repeat(121)}])await assert.rejects(client.search(args),{status:400});});
test('upstream failures and malformed or oversized responses fail closed',async()=>{for(const response of [new Response('bad',{status:500}),new Response('{broken'),Response.json({items:[{name:'../escape'}]}),new Response('{}',{headers:{'content-length':'2000001'}}),new Response('x'.repeat(2000001))]){const client=createShadcnCatalog({fetchImpl:async()=>response});await assert.rejects(client.search(),{status:503});}const client=createShadcnCatalog({fetchImpl:async()=>{throw Error('Authorization: secret')}});await assert.rejects(client.search(),error=>error.status===503&&!error.message.includes('secret'));});
test('component identity and file schema are validated',async()=>{for(const data of [{...button,name:'wrong'},{...button,files:[{path:'ui/a',content:42}]}]){const client=createShadcnCatalog({fetchImpl:async url=>Response.json(url.endsWith('registry.json')?registry:data)});await assert.rejects(client.component({name:'button'}),{status:503});}});
