import test from 'node:test';
import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import {getStore} from '@netlify/blobs';
import {clientOAuthStore,clientSiteStore,getClientSite} from './client-store.mjs';
import {authorizeGrant,parseOperation,safeOutput,redesignSite} from './chatgpt-operations.mjs';
import {key} from './chatgpt-oauth.mjs';
import {prepareProposal,executeProposal,proposalKey} from './chatgpt-proposals.mjs';
import {serveMcp} from './chatgpt-mcp.mjs';
function fixture(t){
 globalThis.netlifyBlobsContext=Buffer.from(JSON.stringify({siteID:'test',token:'test',deployID:'test'})).toString('base64');
 globalThis.Netlify={env:{get:()=>''}};
 t.after(()=>{delete globalThis.Netlify;delete globalThis.netlifyBlobsContext});
 const rows=new Map(),proto=Object.getPrototypeOf(getStore('test'));let revision=0;
 t.mock.method(proto,'get',async function(k){return structuredClone(rows.get(this.name+'/'+k)?.data||null)});
 t.mock.method(proto,'getWithMetadata',async function(k){return structuredClone(rows.get(this.name+'/'+k)||null)});
 t.mock.method(proto,'setJSON',async function(k,data,o={}){const id=this.name+'/'+k,old=rows.get(id);if(o.onlyIfNew&&old||o.onlyIfMatch&&old?.etag!==o.onlyIfMatch)return {modified:false};rows.set(id,{data:structuredClone(data),etag:String(++revision)});return {modified:true}});
 t.mock.method(proto,'list',function({prefix='',paginate=false}={}){const page={blobs:[...rows.keys()].filter(k=>k.startsWith(this.name+'/'+prefix)).map(k=>({key:k.slice(this.name.length+1)}))};return paginate?(async function*(){yield page})():Promise.resolve(page)});
 t.mock.method(globalThis,'fetch',async()=>{throw Error('Unexpected network request')});
 const user={id:'owner-a',email:'owner-a@example.invalid'},site={siteId:'tenant-a',slug:'a',revision:1,status:'active',business:{name:'Original',description:'Original description'},design:{style:'Modern',primary:'#112233',secondary:'#445566'},features:{products:true},members:[{email:user.email,role:'owner'}],catalog:[{id:'p1',name:'Existing',price:30}],employees:[{id:'e1',name:'Existing'}],servicePlan:{subscriptionStatus:'active'},googleCalendar:{connected:true},businessEmail:{connected:true}};
 const grant={id:crypto.randomUUID(),userId:user.id,email:user.email,siteId:site.siteId,platform:false,scopes:['webfactory.read','webfactory.propose'],expiresAt:Date.now()+86400000};
 const prepare=async()=>{await clientSiteStore().setJSON('sites/tenant-a.json',site);await clientOAuthStore().setJSON(key('grants',grant.id),grant)};
 return {site,user,grant,prepare};
}
test('Tenant grant denies foreign business and platform, even for a global administrator',async t=>{const f=fixture(t);await f.prepare();for(const user of [f.user,{...f.user,roles:['admin']}]){await assert.rejects(authorizeGrant(f.grant,user,'tenant-b'),{status:403});await assert.rejects(authorizeGrant(f.grant,user,'tenant-a','platform',{platform:true}),{status:403});}await assert.rejects(authorizeGrant({...f.grant,platform:true},f.user),{status:403});});
test('Current membership and identity are rechecked; removed owners and staff cannot use grants',async t=>{const f=fixture(t);await f.prepare();await authorizeGrant(f.grant,f.user,'tenant-a');await assert.rejects(authorizeGrant(f.grant,{...f.user,id:'other'},'tenant-a'),{status:401});for(const role of ['manager','employee','cashier']){await clientSiteStore().setJSON('sites/tenant-a.json',{...f.site,members:[{email:f.user.email,role}]});await assert.rejects(authorizeGrant(f.grant,f.user,'tenant-a'),{status:403});}});
test('Credential/code inputs rejected and private tokens removed from read results',()=>{for(const name of ['password','accessToken','sourceCode','command','endpoint','__proto__'])assert.throws(()=>parseOperation('upsert_customer',{value:JSON.parse('{"'+name+'":"bad"}')}));assert.deepEqual(safeOutput({email:'a',calendarToken:'private',nested:{apiKey:'key',name:'safe'}}),{email:'a',nested:{name:'safe'}});assert.throws(()=>parseOperation('arbitrary_endpoint',{}));});
test('Redesign preserves operational records and existing business text',async t=>{const f=fixture(t);const next=redesignSite(f.site,{design:{primary:'#abcdef'}});assert.equal(next.business.name,'Original');assert.equal(next.business.description,'Original description');for(const key of ['catalog','employees','googleCalendar','businessEmail','members'])assert.deepEqual(next[key],f.site[key]);});
test('Proposals require write scope, reject changed retry payload and never apply automatically',async t=>{const f=fixture(t);await f.prepare();const input={operation:'redesign',input:{design:{primary:'#abcdef'}},requestId:crypto.randomUUID()};await assert.rejects(prepareProposal({...f.grant,scopes:['webfactory.read']},f.user,input,'https://webfactorypr.com'),{status:403});const p=await prepareProposal(f.grant,f.user,input,'https://webfactorypr.com');assert.equal((await getClientSite('tenant-a')).design.primary,'#112233');assert.equal((await prepareProposal(f.grant,f.user,input,'https://webfactorypr.com')).id,p.id);await assert.rejects(prepareProposal(f.grant,f.user,{...input,input:{design:{primary:'#123456'}}},'https://webfactorypr.com'),{status:409});});
test('Approval is owner-bound, rejects stale snapshots and requires literal human confirmation',async t=>{const f=fixture(t);await f.prepare();const p=await prepareProposal(f.grant,f.user,{operation:'redesign',input:{design:{primary:'#abcdef'}},requestId:crypto.randomUUID()},'https://webfactorypr.com');const req=new Request('https://webfactorypr.com/.netlify/functions/chatgpt-control');await assert.rejects(executeProposal(p.id,{id:'other'},req,{},'CONFIRM'),{status:404});await assert.rejects(executeProposal(p.id,f.user,req,{},'yes'),{status:400});await clientSiteStore().setJSON('sites/tenant-a.json',{...f.site,revision:2});await assert.rejects(executeProposal(p.id,f.user,req,{},'CONFIRM'),{status:409});assert.equal((await clientOAuthStore().get(proposalKey(p.id))).status,'pending');});
test('Approved redesign executes once and preserves business isolation',async t=>{const f=fixture(t);await f.prepare();const p=await prepareProposal(f.grant,f.user,{operation:'redesign',input:{design:{primary:'#abcdef'}},requestId:crypto.randomUUID()},'https://webfactorypr.com');const req=new Request('https://webfactorypr.com/.netlify/functions/chatgpt-control');const result=await executeProposal(p.id,f.user,req,{},'CONFIRM');assert.equal(result.status,'completed');assert.equal((await getClientSite('tenant-a')).design.primary,'#abcdef');const revision=(await getClientSite('tenant-a')).revision;await executeProposal(p.id,f.user,req,{},'CONFIRM');assert.equal((await getClientSite('tenant-a')).revision,revision);});
test('MCP protocol initializes and read-only tool listing excludes mutations and platform tools',async t=>{const f=fixture(t);await f.prepare();const call=async(method,params)=>{const r=await serveMcp(new Request('https://webfactorypr.com/mcp',{method:'POST',headers:{'Content-Type':'application/json',Accept:'application/json, text/event-stream'},body:JSON.stringify({jsonrpc:'2.0',id:1,method,params})}),{...f.grant,scopes:['webfactory.read']},f.user);assert.equal(r.status,200);return r.json()};const init=await call('initialize',{protocolVersion:'2025-06-18',capabilities:{},clientInfo:{name:'test',version:'1'}});assert.equal(init.result.serverInfo.name,'WebFactory PR');const list=await call('tools/list',{});assert.ok(list.result.tools.some(t=>t.name==='wf_business'));assert.ok(list.result.tools.every(t=>!t.name.startsWith('wf_prepare_')&&t.name!=='wf_businesses'));const foreign=await call('tools/call',{name:'wf_business',arguments:{siteId:'tenant-b'}});assert.equal(foreign.result.isError,true);});
test('Write-capable MCP publishes usable accounting/design schemas and no direct executor',async t=>{const f=fixture(t);await f.prepare();const response=await serveMcp(new Request('https://webfactorypr.com/mcp',{method:'POST',headers:{'Content-Type':'application/json',Accept:'application/json, text/event-stream'},body:JSON.stringify({jsonrpc:'2.0',id:1,method:'tools/list',params:{}})}),f.grant,f.user);const {result}=await response.json();assert.ok(result.tools.some(t=>t.name==='wf_prepare_reschedule_booking'));assert.ok(result.tools.some(t=>t.name==='wf_prepare_accounting_entry'));assert.ok(result.tools.every(t=>!t.name.includes('execute')&&!t.name.includes('platform_report')));const schemas=JSON.stringify(result.tools);assert.match(schemas,/hourlyCents/);assert.match(schemas,/northline-barber/);});
test('Changed booking snapshots cannot be applied from an earlier reschedule proposal',async t=>{const f=fixture(t);await f.prepare();const {clientCommerceStore}=await import('./client-store.mjs');const store=clientCommerceStore();const record={siteId:'tenant-a',transactionId:'book-1',calendarToken:'private-not-returned',kind:'booking',status:'confirmed',start:'2027-01-01T12:00:00Z',updatedAt:'2026-10-04'};await store.setJSON('tenant-a/bookings/book-1.json',record);const p=await prepareProposal(f.grant,f.user,{operation:'reschedule_booking',input:{transactionId:'book-1',start:'2027-01-02T12:00:00Z'},requestId:crypto.randomUUID()},'https://webfactorypr.com');assert.ok(!JSON.stringify(p).includes(record.calendarToken));await store.setJSON('tenant-a/bookings/book-1.json',{...record,updatedAt:'2026-10-05'});const result=await executeProposal(p.id,f.user,new Request('https://webfactorypr.com/chatgpt'),{},'CONFIRM');assert.equal(result.status,'review_required');assert.equal((await store.get('tenant-a/bookings/book-1.json')).start,record.start);});

test('Graph context stays in the MCP catalog while tenant access fails closed',async t=>{
 const f=fixture(t);await f.prepare();
 const originalGet=globalThis.Netlify.env.get;
 let values={GRAPHIFY_TENANT_PROJECT_ROOT:'/graphs/tenants'};
 globalThis.Netlify.env.get=name=>values[name]||originalGet(name);
 const request=method=>new Request('https://webfactorypr.com/mcp',{method:'POST',headers:{'Content-Type':'application/json',Accept:'application/json, text/event-stream',Authorization:'Bearer tenant-token'},body:JSON.stringify({jsonrpc:'2.0',id:1,method,params:method==='tools/list'?{}:{name:'wf_graph_context',arguments:{question:'Analyze architecture dependencies between OAuth and MCP'}}})});
 const list=await serveMcp(request('tools/list'),{...f.grant,scopes:['webfactory.read']},f.user);
 const graph=(await list.json()).result.tools.find(tool=>tool.name==='wf_graph_context');
 assert.ok(graph);
 assert.equal(graph.annotations?.readOnlyHint,true);
 assert.ok(!JSON.stringify(graph.inputSchema).includes('project_path'));
 assert.deepEqual(Object.keys(graph.inputSchema.properties).sort(),['depth','mode','question','tokenBudget']);
 assert.equal(graph.inputSchema.properties.tokenBudget.maximum,1600);
 const denied=await serveMcp(request('tools/call'),{...f.grant,scopes:['webfactory.read']},f.user);
 assert.equal((await denied.json()).result.isError,true);
 values={GRAPHIFY_TENANT_PROJECT_ROOT:'/graphs/tenants',GRAPHIFY_TENANT_CONTEXT_ENABLED:'true'};
 const relisted=await serveMcp(request('tools/list'),{...f.grant,scopes:['webfactory.read']},f.user);
 assert.ok((await relisted.json()).result.tools.some(tool=>tool.name==='wf_graph_context'));
});

test('Shadcn tools are read-only admin-only and use public registry without OAuth credentials',async t=>{
 const f=fixture(t);await f.prepare();
 const rpc=async(grant,user,method,params)=>serveMcp(new Request('https://webfactorypr.com/mcp',{method:'POST',headers:{'Content-Type':'application/json',Accept:'application/json, text/event-stream',Authorization:'Bearer private-oauth-token'},body:JSON.stringify({jsonrpc:'2.0',id:1,method,params})}),grant,user);
 const tenantAdmin={...f.user,roles:['admin']};
 const tenantList=await (await rpc(f.grant,tenantAdmin,'tools/list',{})).json();
 assert(!tenantList.result.tools.some(tool=>tool.name.startsWith('wf_shadcn_')));
 const denied=await (await rpc(f.grant,tenantAdmin,'tools/call',{name:'wf_shadcn_search',arguments:{query:'button'}})).json();
 assert(denied.error||denied.result?.isError);
 const grant={...f.grant,platform:true,siteId:undefined,scopes:['webfactory.read']};
 const listing=await (await rpc(grant,tenantAdmin,'tools/list',{})).json();
 const tools=listing.result.tools.filter(tool=>tool.name.startsWith('wf_shadcn_'));
 assert.equal(tools.length,2);assert(tools.every(tool=>tool.annotations.readOnlyHint&&tool.annotations.openWorldHint&&!tool.annotations.destructiveHint));
 let requests=0;
 t.mock.method(globalThis,'fetch',async(url,options)=>{requests++;assert.equal(options.credentials,'omit');assert.deepEqual(options.headers,{Accept:'application/json'});assert(!JSON.stringify(options.headers).includes('private-oauth-token'));assert(url.startsWith('https://ui.shadcn.com/r/styles/new-york-v4/'));return Response.json(url.endsWith('registry.json')?{items:[{name:'button',type:'registry:ui'}]}:{name:'button',files:[{path:'ui/button.tsx',content:'public source'}]});});
 const search=await (await rpc(grant,tenantAdmin,'tools/call',{name:'wf_shadcn_search',arguments:{query:'button'}})).json();assert.equal(JSON.parse(search.result.content[0].text).items[0].name,'button');
 const component=await (await rpc(grant,tenantAdmin,'tools/call',{name:'wf_shadcn_component',arguments:{name:'button'}})).json();assert.equal(JSON.parse(component.result.content[0].text).selectedFile.content,'public source');
 const prior=requests;
 const injection=await (await rpc(grant,tenantAdmin,'tools/call',{name:'wf_shadcn_component',arguments:{name:'button',url:'https://evil.invalid'}})).json();assert(injection.error||injection.result?.isError);assert.equal(requests,prior);
 await assert.rejects(rpc(grant,f.user,'tools/call',{name:'wf_shadcn_search',arguments:{query:'button'}}),{status:403});assert.equal(requests,prior);
});
