import test from 'node:test';
import assert from 'node:assert/strict';
import { applyStockOperation,projectStockMovements,stockOperationId } from './inventory-operations.mjs';
import { applyCustomerTransaction } from './customer-transactions.mjs';
function memory(){const rows=new Map();let version=0;return {rows,async get(key){return structuredClone(rows.get(key)?.data??null)},async getWithMetadata(key){return structuredClone(rows.get(key)??null)},async setJSON(key,data,options={}){const old=rows.get(key);if(options.onlyIfNew&&old||options.onlyIfMatch&&old?.etag!==options.onlyIfMatch)return {modified:false};rows.set(key,{data:structuredClone(data),etag:String(++version)});return {modified:true}}};}
async function fixture(inventory=1){const store=memory();await store.setJSON('sites/shop.json',{siteId:'shop',slug:'shop',revision:1,catalog:[{id:'p',type:'product',trackInventory:true,inventory}]});return store;}
const sale=id=>({kind:'sale',referenceId:id,items:[{id:'p',quantity:1}]});
test('simultaneous operations cannot sell the last unit twice even without a shared external lock',async()=>{const s=await fixture();const results=await Promise.allSettled([applyStockOperation('shop',sale('first'),s),applyStockOperation('shop',sale('second'),s)]);assert.equal(results.filter(value=>value.status==='fulfilled').length,1);assert.equal((await s.get('sites/shop.json')).catalog[0].inventory,0);assert.equal(Object.keys((await s.get('sites/shop.json')).stockOperations).length,1);});
test('a committed write with a lost response replays its marker instead of decrementing stock again',async()=>{const s=await fixture(3),write=s.setJSON;let broken=true;s.setJSON=async(key,value,options)=>{const result=await write(key,value,options);if(value.stockOperations&&broken){broken=false;throw new Error('response lost after commit')};return result};await assert.rejects(applyStockOperation('shop',sale('lost'),s));const result=await applyStockOperation('shop',sale('lost'),s);assert.equal(result.reused,true);assert.equal(result.site.catalog[0].inventory,2);});
test('movement projection can be repeated after failure without duplicate movement rows',async()=>{const s=await fixture(3),result=await applyStockOperation('shop',sale('tx'),s),commerce=memory();await projectStockMovements('shop',result.operation,commerce);await projectStockMovements('shop',result.operation,commerce);assert.equal(commerce.rows.size,1);const row=[...commerce.rows.values()][0].data;assert.equal(row.before,3);assert.equal(row.after,2);assert.equal(row.quantityDelta,-1);});
test('refunds restore stock once and altered replay inputs fail',async()=>{const s=await fixture(3);await applyStockOperation('shop',sale('tx'),s);const refund={...sale('tx'),kind:'refund',direction:1};await applyStockOperation('shop',refund,s);await applyStockOperation('shop',refund,s);assert.equal((await s.get('sites/shop.json')).catalog[0].inventory,3);await assert.rejects(applyStockOperation('shop',{...refund,items:[{id:'p',quantity:2}]},s),{status:409});});
test('invalid quantities, missing products and insufficient stock change neither inventory nor markers',async()=>{const s=await fixture();for(const items of [[{id:'p',quantity:-1}],[{id:'p',quantity:'bad'}],[{id:'p',quantity:1},{id:'p',quantity:1}],[{id:'missing',quantity:1}],[{id:'p',quantity:2}]])await assert.rejects(applyStockOperation('shop',{...sale('bad'),items},s));const site=await s.get('sites/shop.json');assert.equal(site.catalog[0].inventory,1);assert.equal(site.stockOperations,undefined);});
test('explicit backorders remain supported and journal exhaustion fails closed',async()=>{const s=await fixture(0);const original=await s.get('sites/shop.json');original.catalog[0].allowBackorder=true;await s.setJSON('sites/shop.json',original);await applyStockOperation('shop',sale('allowed'),s);assert.equal((await s.get('sites/shop.json')).catalog[0].inventory,-1);const full=await s.get('sites/shop.json');full.stockOperations=Object.fromEntries(Array.from({length:5000},(_,i)=>[String(i),{}]));await s.setJSON('sites/shop.json',full);await assert.rejects(applyStockOperation('shop',sale('full'),s),{status:503});});
test('customer totals and their replay markers are applied in one write',async()=>{const s=memory(),transaction={transactionId:'tx',kind:'order',amountTotal:100,customer:{email:'fixture@example.com'}};await applyCustomerTransaction('shop',transaction,s);const second=await applyCustomerTransaction('shop',transaction,s);assert.equal(second.totalSpent,100);assert.equal(second.orderCount,1);assert.equal(Object.keys(second.appliedTransactions).length,1);await assert.rejects(applyCustomerTransaction('shop',{...transaction,amountTotal:200},s),{status:409});});
test('anonymous customer identity stays stable across retries',async()=>{const s=memory(),transaction={transactionId:'tx',kind:'order',amountTotal:100,customer:{}};const first=await applyCustomerTransaction('shop',transaction,s);const second=await applyCustomerTransaction('shop',transaction,s);assert.equal(first.customerId,second.customerId);assert.equal(s.rows.size,1);assert.equal(second.orderCount,1);});
