import test from 'node:test';
import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import * as webAuthn from '@simplewebauthn/server';
import { isoCBOR } from '@simplewebauthn/server/helpers';
import { issuePrimarySession, securityState, assertSecondFactor, createMfaService, hash, userPrefix, PRIMARY_COOKIE, revokePrimarySession } from './mfa-security.mjs';
const origin='https://portal.example.com',user={id:'private-user',email:'private@example.com'};
function memory(){const data=new Map();let revision=0;return {data,async get(key){return structuredClone(data.get(key)?.data??null)},async getWithMetadata(key){return structuredClone(data.get(key)??null)},async setJSON(key,value,options={}){const old=data.get(key);if(options.onlyIfNew&&old||options.onlyIfMatch&&old?.etag!==options.onlyIfMatch)return {modified:false};data.set(key,{data:structuredClone(value),etag:String(++revision)});return {modified:true}},async delete(key){data.delete(key)},async list({prefix}){return {blobs:[...data.keys()].filter(key=>key.startsWith(prefix)).map(key=>({key}))}}};}
async function setup(){const store=memory(),jar=new Map(),context={cookies:{get:name=>jar.get(name),set:cookie=>{assert.equal(cookie.httpOnly,true);assert.equal(cookie.secure,true);jar.set(cookie.name,cookie.value)},delete:cookie=>jar.delete(cookie.name)}};let clock=Date.now();await issuePrimarySession(user,context,store,clock);const service=createMfaService(store,webAuthn,()=>clock);return {store,context,service,clock:()=>clock,advance:value=>clock+=value};}
function credential(){const {publicKey,privateKey}=crypto.generateKeyPairSync('ec',{namedCurve:'prime256v1'});const jwk=publicKey.export({format:'jwk'});return {id:crypto.randomBytes(32).toString('base64url'),privateKey,key:Buffer.from(isoCBOR.encode(new Map([[1,2],[3,-7],[-1,1],[-2,Buffer.from(jwk.x,'base64url')],[-3,Buffer.from(jwk.y,'base64url')]])))};}
function response(options,c,register,changes={}){const clientData=Buffer.from(JSON.stringify({type:register?'webauthn.create':'webauthn.get',challenge:options.challenge,origin,...changes}));const counter=Buffer.alloc(4);counter.writeUInt32BE(register?0:1);const authData=Buffer.concat([crypto.createHash('sha256').update(new URL(origin).hostname).digest(),Buffer.from([register?0x45:0x05]),counter,...(register?[Buffer.alloc(16),Buffer.from([0,32]),Buffer.from(c.id,'base64url'),c.key]:[])]);return {id:c.id,rawId:c.id,type:'public-key',clientExtensionResults:{},response:register?{clientDataJSON:clientData.toString('base64url'),attestationObject:Buffer.from(isoCBOR.encode(new Map([['fmt','none'],['attStmt',new Map()],['authData',authData]]))).toString('base64url'),transports:['internal']}:{clientDataJSON:clientData.toString('base64url'),authenticatorData:authData.toString('base64url'),signature:crypto.sign('sha256',Buffer.concat([authData,crypto.createHash('sha256').update(clientData).digest()]),c.privateKey).toString('base64url')}};}
async function enroll(s){const c=credential(),challenge=await s.service.options(user,s.context,'register',origin);const result=await s.service.verify(user,s.context,{challengeId:challenge.challengeId,response:response(challenge.options,c,true)},'register',origin);return {c,challenge,result};}
test('real WebAuthn enrollment stores public material and hashes recovery codes; challenges cannot replay',async()=>{const s=await setup();await assert.rejects(assertSecondFactor(user,s.context,s.store,true));const {challenge,c,result}=await enroll(s);assert.equal(result.recoveryCodes.length,10);const profile=await s.store.get(`${userPrefix(user)}profile.json`);assert.equal(profile.credentials[0].publicKey,c.key.toString('base64url'));assert.ok(result.recoveryCodes.every(code=>profile.codes.includes(hash(code))&&!JSON.stringify(profile).includes(code)));assert.equal((await securityState(user,s.context,s.store,true,s.clock())).verified,true);await assert.rejects(s.service.verify(user,s.context,{challengeId:challenge.challengeId,response:response(challenge.options,c,true)},'register',origin));});
test('real signed authentication verifies and updates counter, rejecting altered signatures and origins',async()=>{const s=await setup();const {c}=await enroll(s);await issuePrimarySession(user,s.context,s.store,s.clock());await assert.rejects(assertSecondFactor(user,s.context,s.store,false));for(const mutation of ['signature','origin']){const challenge=await s.service.options(user,s.context,'authenticate',origin);const signed=response(challenge.options,c,false,mutation==='origin'?{origin:'https://attacker.example'}:{});if(mutation==='signature')signed.response.signature=crypto.randomBytes(70).toString('base64url');await assert.rejects(s.service.verify(user,s.context,{challengeId:challenge.challengeId,response:signed},'authenticate',origin));assert.equal((await securityState(user,s.context,s.store,true,s.clock())).verified,false);}const challenge=await s.service.options(user,s.context,'authenticate',origin);await s.service.verify(user,s.context,{challengeId:challenge.challengeId,response:response(challenge.options,c,false)},'authenticate',origin);assert.equal((await s.store.get(`${userPrefix(user)}profile.json`)).credentials[0].counter,1);await assertSecondFactor(user,s.context,s.store,true);});
test('recovery codes work once and logout revokes server proof',async()=>{const s=await setup();const {result}=await enroll(s);await issuePrimarySession(user,s.context,s.store,s.clock());await s.service.recover(user,s.context,result.recoveryCodes[0]);await assert.rejects(s.service.recover(user,s.context,result.recoveryCodes[0]));assert.equal((await securityState(user,s.context,s.store,true,s.clock())).recoveryCodesRemaining,9);const token=s.context.cookies.get(PRIMARY_COOKIE);await revokePrimarySession(user,s.context,s.store);s.context.cookies.set({name:PRIMARY_COOKIE,value:token,httpOnly:true,secure:true});await assert.rejects(assertSecondFactor(user,s.context,s.store,true));});
test('fresh password required for initial enrollment; expired and other-session challenges fail',async()=>{const s=await setup();const challenge=await s.service.options(user,s.context,'register',origin);await issuePrimarySession(user,s.context,s.store,s.clock());await assert.rejects(s.service.verify(user,s.context,{challengeId:challenge.challengeId,response:response(challenge.options,credential(),true)},'register',origin));s.advance(300001);await assert.rejects(s.service.options(user,s.context,'register',origin));});
test('last passkey cannot be removed; modifications require recent second-factor proof',async()=>{const s=await setup();const {c}=await enroll(s);await assert.rejects(s.service.remove(user,s.context,c.id),/replacement/);s.advance(300001);await assert.rejects(s.service.options(user,s.context,'register',origin),/Verify/);});
test('replacing codes invalidates previous codes and other verified sessions',async()=>{const s=await setup();const {result}=await enroll(s);const previous=s.context.cookies.get(PRIMARY_COOKIE);await issuePrimarySession(user,s.context,s.store,s.clock());await s.service.recover(user,s.context,result.recoveryCodes[0]);const rotated=await s.service.rotateCodes(user,s.context);assert.equal(rotated.recoveryCodes.length,10);await assert.rejects(s.service.recover(user,s.context,result.recoveryCodes[1]));s.context.cookies.set({name:PRIMARY_COOKIE,value:previous,httpOnly:true,secure:true});await assert.rejects(assertSecondFactor(user,s.context,s.store,true));});
test('user verification is mandatory even for a correctly signed assertion',async()=>{const s=await setup();const {c}=await enroll(s);await issuePrimarySession(user,s.context,s.store,s.clock());const challenge=await s.service.options(user,s.context,'authenticate',origin);const signed=response(challenge.options,c,false);const data=Buffer.from(signed.response.authenticatorData,'base64url');data[32]=1;signed.response.authenticatorData=data.toString('base64url');signed.response.signature=crypto.sign('sha256',Buffer.concat([data,crypto.createHash('sha256').update(Buffer.from(signed.response.clientDataJSON,'base64url')).digest()]),c.privateKey).toString('base64url');await assert.rejects(s.service.verify(user,s.context,{challengeId:challenge.challengeId,response:signed},'authenticate',origin));});
test('challenge expiration and concurrent recovery consumption fail closed',async()=>{const s=await setup();const {c,result}=await enroll(s);await issuePrimarySession(user,s.context,s.store,s.clock());const challenge=await s.service.options(user,s.context,'authenticate',origin);s.advance(300001);await assert.rejects(s.service.verify(user,s.context,{challengeId:challenge.challengeId,response:response(challenge.options,c,false)},'authenticate',origin));const outcomes=await Promise.allSettled([s.service.recover(user,s.context,result.recoveryCodes[0]),s.service.recover(user,s.context,result.recoveryCodes[0])]);assert.equal(outcomes.filter(r=>r.status==='fulfilled').length,1);});
