import test from 'node:test';
import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import * as webAuthn from '@simplewebauthn/server';
import { totpCode } from './mfa-totp.mjs';
import { isoCBOR } from '@simplewebauthn/server/helpers';
import { issuePrimarySession, securityState, assertSecondFactor, createMfaService, hash, userPrefix, PRIMARY_COOKIE, revokePrimarySession } from './mfa-security.mjs';
const origin='https://portal.example.com',user={id:'private-user',email:'private@example.com'};
function memory(){const data=new Map();let revision=0;return {data,async get(key){return structuredClone(data.get(key)?.data??null)},async getWithMetadata(key){return structuredClone(data.get(key)??null)},async setJSON(key,value,options={}){const old=data.get(key);if(options.onlyIfNew&&old||options.onlyIfMatch&&old?.etag!==options.onlyIfMatch)return {modified:false};data.set(key,{data:structuredClone(value),etag:String(++revision)});return {modified:true}},async delete(key){data.delete(key)},async list({prefix}){return {blobs:[...data.keys()].filter(key=>key.startsWith(prefix)).map(key=>({key}))}}};}
async function setup(){const store=memory(),jar=new Map(),context={cookies:{get:name=>jar.get(name),set:cookie=>{assert.equal(cookie.httpOnly,true);assert.equal(cookie.secure,true);jar.set(cookie.name,cookie.value)},delete:cookie=>jar.delete(cookie.name)}};let clock=Date.now();await issuePrimarySession(user,context,store,clock);const service=createMfaService(store,webAuthn,()=>clock,{totpKey:()=>Buffer.alloc(32,7).toString('base64')});return {store,context,service,clock:()=>clock,advance:value=>clock+=value};}
function credential(){const {publicKey,privateKey}=crypto.generateKeyPairSync('ec',{namedCurve:'prime256v1'});const jwk=publicKey.export({format:'jwk'});return {id:crypto.randomBytes(32).toString('base64url'),privateKey,key:Buffer.from(isoCBOR.encode(new Map([[1,2],[3,-7],[-1,1],[-2,Buffer.from(jwk.x,'base64url')],[-3,Buffer.from(jwk.y,'base64url')]])))};}
function response(options,c,register,changes={}){const clientData=Buffer.from(JSON.stringify({type:register?'webauthn.create':'webauthn.get',challenge:options.challenge,origin,...changes}));const counter=Buffer.alloc(4);counter.writeUInt32BE(register?0:1);const authData=Buffer.concat([crypto.createHash('sha256').update(new URL(origin).hostname).digest(),Buffer.from([register?0x45:0x05]),counter,...(register?[Buffer.alloc(16),Buffer.from([0,32]),Buffer.from(c.id,'base64url'),c.key]:[])]);return {id:c.id,rawId:c.id,type:'public-key',clientExtensionResults:{},response:register?{clientDataJSON:clientData.toString('base64url'),attestationObject:Buffer.from(isoCBOR.encode(new Map([['fmt','none'],['attStmt',new Map()],['authData',authData]]))).toString('base64url'),transports:['internal']}:{clientDataJSON:clientData.toString('base64url'),authenticatorData:authData.toString('base64url'),signature:crypto.sign('sha256',Buffer.concat([authData,crypto.createHash('sha256').update(clientData).digest()]),c.privateKey).toString('base64url')}};}
async function enroll(s){const c=credential(),challenge=await s.service.options(user,s.context,'register',origin);const result=await s.service.verify(user,s.context,{challengeId:challenge.challengeId,response:response(challenge.options,c,true)},'register',origin);return {c,challenge,result};}
test('real WebAuthn enrollment stores public material and hashes recovery codes; challenges cannot replay',async()=>{const s=await setup();await assert.rejects(assertSecondFactor(user,s.context,s.store,true));const {challenge,c,result}=await enroll(s);assert.equal(result.recoveryCodes.length,10);const profile=await s.store.get(`${userPrefix(user)}profile.json`);assert.equal(profile.credentials[0].publicKey,c.key.toString('base64url'));assert.ok(result.recoveryCodes.every(code=>profile.codes.includes(hash(code))&&!JSON.stringify(profile).includes(code)));assert.equal((await securityState(user,s.context,s.store,true,s.clock())).verified,true);await assert.rejects(s.service.verify(user,s.context,{challengeId:challenge.challengeId,response:response(challenge.options,c,true)},'register',origin));});
test('real signed authentication verifies and updates counter, rejecting altered signatures and origins',async()=>{const s=await setup();const {c}=await enroll(s);await issuePrimarySession(user,s.context,s.store,s.clock());await assert.rejects(assertSecondFactor(user,s.context,s.store,false));for(const mutation of ['signature','origin']){const challenge=await s.service.options(user,s.context,'authenticate',origin);const signed=response(challenge.options,c,false,mutation==='origin'?{origin:'https://attacker.example'}:{});if(mutation==='signature')signed.response.signature=crypto.randomBytes(70).toString('base64url');await assert.rejects(s.service.verify(user,s.context,{challengeId:challenge.challengeId,response:signed},'authenticate',origin));assert.equal((await securityState(user,s.context,s.store,true,s.clock())).verified,false);}const challenge=await s.service.options(user,s.context,'authenticate',origin);await s.service.verify(user,s.context,{challengeId:challenge.challengeId,response:response(challenge.options,c,false)},'authenticate',origin);assert.equal((await s.store.get(`${userPrefix(user)}profile.json`)).credentials[0].counter,1);await assertSecondFactor(user,s.context,s.store,true);});
test('recovery codes work once and logout revokes server proof',async()=>{const s=await setup();const {result}=await enroll(s);await issuePrimarySession(user,s.context,s.store,s.clock());await s.service.recover(user,s.context,result.recoveryCodes[0]);await assert.rejects(s.service.recover(user,s.context,result.recoveryCodes[0]));assert.equal((await securityState(user,s.context,s.store,true,s.clock())).recoveryCodesRemaining,9);const token=s.context.cookies.get(PRIMARY_COOKIE);await revokePrimarySession(user,s.context,s.store);s.context.cookies.set({name:PRIMARY_COOKIE,value:token,httpOnly:true,secure:true});await assert.rejects(assertSecondFactor(user,s.context,s.store,true));});
test('fresh password required for initial enrollment; expired and other-session challenges fail',async()=>{const s=await setup();const challenge=await s.service.options(user,s.context,'register',origin);await issuePrimarySession(user,s.context,s.store,s.clock());await assert.rejects(s.service.verify(user,s.context,{challengeId:challenge.challengeId,response:response(challenge.options,credential(),true)},'register',origin));s.advance(300001);await assert.rejects(s.service.options(user,s.context,'register',origin));});
test('last passkey cannot be removed; modifications require recent second-factor proof',async()=>{const s=await setup();const {c}=await enroll(s);await assert.rejects(s.service.remove(user,s.context,c.id),/replacement/);s.advance(300001);await assert.rejects(s.service.options(user,s.context,'register',origin),/Verify/);});
test('replacing codes invalidates previous codes and other verified sessions',async()=>{const s=await setup();const {result}=await enroll(s);const previous=s.context.cookies.get(PRIMARY_COOKIE);await issuePrimarySession(user,s.context,s.store,s.clock());await s.service.recover(user,s.context,result.recoveryCodes[0]);const rotated=await s.service.rotateCodes(user,s.context);assert.equal(rotated.recoveryCodes.length,10);await assert.rejects(s.service.recover(user,s.context,result.recoveryCodes[1]));s.context.cookies.set({name:PRIMARY_COOKIE,value:previous,httpOnly:true,secure:true});await assert.rejects(assertSecondFactor(user,s.context,s.store,true));});
test('user verification is mandatory even for a correctly signed assertion',async()=>{const s=await setup();const {c}=await enroll(s);await issuePrimarySession(user,s.context,s.store,s.clock());const challenge=await s.service.options(user,s.context,'authenticate',origin);const signed=response(challenge.options,c,false);const data=Buffer.from(signed.response.authenticatorData,'base64url');data[32]=1;signed.response.authenticatorData=data.toString('base64url');signed.response.signature=crypto.sign('sha256',Buffer.concat([data,crypto.createHash('sha256').update(Buffer.from(signed.response.clientDataJSON,'base64url')).digest()]),c.privateKey).toString('base64url');await assert.rejects(s.service.verify(user,s.context,{challengeId:challenge.challengeId,response:signed},'authenticate',origin));});
test('challenge expiration and concurrent recovery consumption fail closed',async()=>{const s=await setup();const {c,result}=await enroll(s);await issuePrimarySession(user,s.context,s.store,s.clock());const challenge=await s.service.options(user,s.context,'authenticate',origin);s.advance(300001);await assert.rejects(s.service.verify(user,s.context,{challengeId:challenge.challengeId,response:response(challenge.options,c,false)},'authenticate',origin));const outcomes=await Promise.allSettled([s.service.recover(user,s.context,result.recoveryCodes[0]),s.service.recover(user,s.context,result.recoveryCodes[0])]);assert.equal(outcomes.filter(r=>r.status==='fulfilled').length,1);});
const otp=(s,pending)=>totpCode(pending.secret,Math.floor(s.clock()/30000));
async function enrollTotp(s){const pending=await s.service.beginTotp(user,s.context,origin);const result=await s.service.confirmTotp(user,s.context,pending.challengeId,otp(s,pending),origin);return {pending,result}}
test('Authenticator-only enrollment grants proof and hashed recovery codes without plaintext storage',async()=>{const s=await setup(),{pending,result}=await enrollTotp(s);assert.equal(result.recoveryCodes.length,10);const profile=await s.store.get(`${userPrefix(user)}profile.json`);assert.equal(profile.credentials.length,0);assert.ok(!JSON.stringify([...s.store.data]).includes(pending.secret));assert.ok(result.recoveryCodes.every(code=>profile.codes.includes(hash(code))));const state=await securityState(user,s.context,s.store,true,s.clock());assert.equal(state.verified,true);assert.equal(state.authenticatorEnrolled,true);assert.ok(!JSON.stringify(state).includes('encrypted'));await assert.rejects(s.service.removeTotp(user,s.context,origin),/Add a passkey/);await assert.rejects(s.service.confirmTotp(user,s.context,pending.challengeId,otp(s,pending),origin));});
test('Authenticator login rejects reused codes, serializes concurrent use and retains recovery fallback',async()=>{const s=await setup(),{pending,result}=await enrollTotp(s);await issuePrimarySession(user,s.context,s.store,s.clock());await assert.rejects(s.service.authenticateTotp(user,s.context,otp(s,pending),origin),/already used/);s.advance(30000);const outcomes=await Promise.allSettled([s.service.authenticateTotp(user,s.context,otp(s,pending),origin),s.service.authenticateTotp(user,s.context,otp(s,pending),origin)]);assert.equal(outcomes.filter(x=>x.status==='fulfilled').length,1);await assertSecondFactor(user,s.context,s.store,true);await issuePrimarySession(user,s.context,s.store,s.clock());await s.service.recover(user,s.context,result.recoveryCodes[0]);await assertSecondFactor(user,s.context,s.store,true)});
test('pending enrollment is bound to session, origin, expiry and cancellation',async()=>{for(const mode of ['session','origin','expiry','cancel']){const s=await setup(),p=await s.service.beginTotp(user,s.context,origin);if(mode==='session')await issuePrimarySession(user,s.context,s.store,s.clock());if(mode==='expiry')s.advance(300001);if(mode==='cancel')await s.service.cancelTotp(user,s.context,p.challengeId,origin);await assert.rejects(s.service.confirmTotp(user,s.context,p.challengeId,otp(s,p),mode==='origin'?'https://foreign.example':origin));assert.equal((await securityState(user,s.context,s.store,true,s.clock())).enrolled,false)}});
test('five failed codes block the account across setup challenges',async()=>{const s=await setup(),p=await s.service.beginTotp(user,s.context,origin);for(let i=0;i<5;i++)await assert.rejects(s.service.confirmTotp(user,s.context,p.challengeId,'invalid',origin),{status:401});const next=await s.service.beginTotp(user,s.context,origin);await assert.rejects(s.service.confirmTotp(user,s.context,next.challengeId,otp(s,next),origin),{status:429});s.advance(300001);const fresh=await issuePrimarySession(user,s.context,s.store,s.clock());const retry=await s.service.beginTotp(user,s.context,origin);await s.service.confirmTotp(user,s.context,retry.challengeId,otp(s,retry),origin)});
test('adding and removing factors requires fresh proof and preserves the remaining factor',async()=>{const s=await setup(),{c}=await enroll(s);await issuePrimarySession(user,s.context,s.store,s.clock());await assert.rejects(s.service.beginTotp(user,s.context,origin),/Verify/);const challenge=await s.service.options(user,s.context,'authenticate',origin);await s.service.verify(user,s.context,{challengeId:challenge.challengeId,response:response(challenge.options,c,false)},'authenticate',origin);await enrollTotp(s);await s.service.remove(user,s.context,c.id);assert.equal((await securityState(user,s.context,s.store,true,s.clock())).credentials.length,0);await enroll(s);await s.service.removeTotp(user,s.context,origin);assert.equal((await securityState(user,s.context,s.store,true,s.clock())).authenticatorEnrolled,false)});
test('Authenticator-only accounts cannot register a passkey without second-factor proof',async()=>{const s=await setup();await enrollTotp(s);await issuePrimarySession(user,s.context,s.store,s.clock());await assert.rejects(s.service.options(user,s.context,'register',origin),/Verify/)});
test('invalid encryption key, altered encrypted state and missing replay marker fail closed',async()=>{const s=await setup(),{pending}=await enrollTotp(s);await issuePrimarySession(user,s.context,s.store,s.clock());s.advance(30000);await assert.rejects(s.service.authenticateTotp(user,s.context,otp(s,pending),'https://foreign.example'),{status:403});const noKey=createMfaService(s.store,webAuthn,s.clock,{totpKey:()=>''});await assert.rejects(noKey.authenticateTotp(user,s.context,otp(s,pending),origin),{status:503});const path=`${userPrefix(user)}profile.json`,original=await s.store.get(path);await s.store.setJSON(path,{...original,totp:{...original.totp,encrypted:{...original.totp.encrypted,tag:Buffer.alloc(16).toString('base64')}}});await assert.rejects(s.service.authenticateTotp(user,s.context,otp(s,pending),origin),{status:503});await s.store.setJSON(path,{...original,totp:{encrypted:original.totp.encrypted}});await assert.rejects(s.service.authenticateTotp(user,s.context,otp(s,pending),origin),{status:503});await assert.rejects(assertSecondFactor(user,s.context,s.store,true))});
