import test from 'node:test';
import assert from 'node:assert/strict';
import nodemailer from 'nodemailer';
import {emailConfigured,emailProvider,sendEmail} from './email.mjs';
import {verifyResendCredentials} from './resend-diagnostics.mjs';
import {createResendVerifier} from '../functions/verify-resend.mjs';
function environment(t,values){const previous=globalThis.Netlify;globalThis.Netlify={env:{get:name=>values[name]}};t.after(()=>{globalThis.Netlify=previous});}
const values={WEBFACTORY_EMAIL_PROVIDER:'resend',RESEND_API_KEY:'fixture-secret',WEBFACTORY_EMAIL_FROM_TEAM:'team@example.com',WEBFACTORY_GMAIL_USER:'fallback@example.com',WEBFACTORY_GMAIL_APP_PASSWORD:'fixture-gmail'};
test('Resend sends existing HTML, text, attachment and headers from the configured corporate sender',async t=>{
 environment(t,values);let message;
 t.mock.method(nodemailer,'createTransport',options=>{assert.equal(options.host,'smtp.resend.com');assert.equal(options.port,465);assert.equal(options.secure,true);assert.deepEqual(options.auth,{user:'resend',pass:'fixture-secret'});return {sendMail:async mail=>{message=mail;return {accepted:mail.to}},close(){}}});
 const html='<!doctype html><html><body>Fixture</body></html>',attachments=[{filename:'booking.ics',content:'fixture-calendar'}],headers={'List-Unsubscribe':'<https://example.com/unsubscribe>'};
 const result=await sendEmail({to:'recipient@example.com',subject:'Booking',html,text:'Fixture text',attachments,headers,replyTo:'support@example.com'});
 assert.equal(result.provider,'resend');assert.equal(message.from,'"WebFactory PR" <team@example.com>');assert.equal(message.html,html);assert.equal(message.text,'Fixture text');assert.deepEqual(message.attachments,attachments);assert.deepEqual(message.headers,headers);assert.equal(message.replyTo,'support@example.com');
});
test('adding a Resend key does not override Gmail or existing auto selection',t=>{environment(t,{...values,WEBFACTORY_EMAIL_PROVIDER:'gmail'});assert.equal(emailProvider(),'gmail');globalThis.Netlify.env.get=name=>({...values,WEBFACTORY_EMAIL_PROVIDER:'auto'})[name];assert.equal(emailProvider(),'gmail-fallback');});
test('selected Resend with missing key fails closed before opening SMTP',async t=>{environment(t,{...values,RESEND_API_KEY:''});assert.equal(emailProvider(),'unconfigured');let opened=false;t.mock.method(nodemailer,'createTransport',()=>{opened=true});await assert.rejects(sendEmail({to:'recipient@example.com',subject:'Fixture',text:'Fixture'}),/API key is not configured/);assert.equal(opened,false);});
test('Resend verification authenticates and closes without sending or returning credentials',async()=>{let closed=0;const result=await verifyResendCredentials({read:()=> 'fixture-secret',createTransport:options=>{assert.equal(options.auth.user,'resend');return {verify:async()=>true,close:()=>closed++}}});assert.equal(result.authenticated,true);assert.equal(closed,1);assert.ok(!JSON.stringify(result).includes('fixture-secret'));});
test('Resend rejects missing credentials and sanitizes SMTP authentication errors',async()=>{let opened=false;assert.equal((await verifyResendCredentials({read:()=>'',createTransport:()=>{opened=true}})).issue,'credentials_missing');assert.equal(opened,false);const result=await verifyResendCredentials({read:()=> 'fixture-secret',createTransport:()=>({verify:async()=>{throw Object.assign(new Error('fixture-secret'),{responseCode:535})},close(){}})});assert.equal(result.smtpStatus,535);assert.equal(result.authenticated,false);assert.ok(!JSON.stringify(result).includes('fixture-secret'));});
test('diagnostic requires administrator and same origin; reports no email sent and active Gmail',async()=>{let verified=0;const handler=createResendVerifier({authorize:async()=>{},verify:async()=>{verified++;return {authenticated:true}},provider:()=> 'gmail'});const request=(method,origin)=>new Request('https://example.com/.netlify/functions/verify-resend',{method,headers:{Origin:origin}});assert.equal((await handler(request('GET','https://example.com'))).status,405);assert.equal((await handler(request('POST','https://other.example'))).status,403);assert.equal(verified,0);const response=await handler(request('POST','https://example.com'));assert.equal(response.headers.get('Cache-Control'),'no-store');assert.deepEqual(await response.json(),{ok:true,authenticated:true,activeProvider:'gmail',emailSent:false});const denied=createResendVerifier({authorize:async()=>{throw Object.assign(new Error('Unauthorized'),{status:401})},verify:async()=>{throw new Error('Must not run')}});assert.equal((await denied(request('POST','https://example.com'))).status,401);});

test('retired provider cannot authenticate or silently select another transport',async t=>{environment(t,{...values,WEBFACTORY_EMAIL_PROVIDER:'mailjet'});assert.equal(emailConfigured(),false);let opened=false;t.mock.method(nodemailer,'createTransport',()=>{opened=true});await assert.rejects(sendEmail({to:'recipient@example.com',subject:'Fixture',text:'Fixture'}),/must be set to auto, gmail, or resend/);assert.equal(opened,false);});
test('client readiness recognizes selected Resend without Gmail credentials and fails closed when its key is missing',async t=>{environment(t,{WEBFACTORY_EMAIL_PROVIDER:'resend',RESEND_API_KEY:'fixture',STRIPE_SECRET_KEY:'fixture',STRIPE_CONNECT_WEBHOOK_SECRET:'fixture'});const {default:readiness}=await import('../functions/client-runtime-readiness.mjs');const read=async()=> (await readiness(new Request('https://example.com/.netlify/functions/client-runtime-readiness'))).json();assert.equal((await read()).clientPaymentsReady,true);globalThis.Netlify.env.get=name=>({WEBFACTORY_EMAIL_PROVIDER:'resend',WEBFACTORY_GMAIL_USER:'fallback@example.com',WEBFACTORY_GMAIL_APP_PASSWORD:'fixture'})[name];assert.equal((await read()).checks.transactionalEmail,false);});
