import test from 'node:test';
import assert from 'node:assert/strict';
import { createReviewProcessor,REVIEW_HEALTH_KEY,publicReviewHealth } from './review-processing.mjs';
import handler from '../functions/process-review-requests.mjs';
function memory(rows=[]){const data=new Map(rows.map(([key,value],i)=>[key,{data:structuredClone(value),etag:String(i)}]));let revision=1000;return {data,async get(key){return structuredClone(data.get(key)?.data??null)},async getWithMetadata(key){return structuredClone(data.get(key)??null)},async setJSON(key,value,options={}){const old=data.get(key);if(options.onlyIfNew&&old||options.onlyIfMatch&&old?.etag!==options.onlyIfMatch)return {modified:false};data.set(key,{data:structuredClone(value),etag:String(++revision)});return {modified:true}},async delete(key){data.delete(key)},list({prefix}){const keys=[...data.keys()].filter(key=>key.startsWith(prefix)).reverse();return(async function*(){for(let i=0;i<keys.length;i+=17)yield {blobs:keys.slice(i,i+17).map(key=>({key}))};})()}};}
const now=Date.parse('2026-10-02T15:00:00Z');
const site=id=>({siteId:id,reviewSettings:{enabled:true,postalAddress:'Fixture postal address'},settings:{locale:'es'},business:{name:'Fixture'}});
const request=(id,extra={})=>({siteId:'s',reviewRequestId:id,status:'pending',customer:{name:'Fixture',email:'fixture@example.com',reviewOptIn:true},reviewUrl:'https://reviews.example.com',dueAt:new Date(now-10000).toISOString(),...extra});
function fixture(records=[request('r')],siteRows=[site('s')]){const sites=memory(siteRows.map(value=>[`sites/${value.siteId}.json`,value])),commerce=memory(records.map(value=>[`${value.siteId}/v3/review-requests/${value.reviewRequestId}.json`,value])),events=memory(),delivered=[];const deps={sites,commerce,events,getSite:id=>sites.get(`sites/${id}.json`),unsubscribe:async()=>'https://example.com/unsubscribe',send:async (_site,message)=>{delivered.push(message);return {accepted:[message.to]}},clock:()=>now};return {sites,commerce,events,delivered,deps,run:options=>createReviewProcessor(deps)(options)};}
test('paginated tenant rotation reaches businesses beyond 100 across repeated bounded batches',async()=>{const f=fixture([],Array.from({length:151},(_,i)=>site(`s${String(i).padStart(3,'0')}`)));for(let i=0;i<16;i++)await f.run();const state=await f.events.get(REVIEW_HEALTH_KEY);assert.equal(state.listedSites,151);assert.equal(state.siteCursor,'sites/s008.json');});
test('request rotation reaches old pending requests beyond the previous 500-request cut',async()=>{const f=fixture(Array.from({length:505},(_,i)=>request(`r${String(i).padStart(3,'0')}`)));for(let i=0;i<101;i++)await f.run({perSite:5});assert.equal(f.delivered.length,505);assert.equal(f.delivered[504].timeoutMs,6000);assert.ok(f.delivered.every(message=>message.headers['List-Unsubscribe-Post']==='List-Unsubscribe=One-Click'));});
test('parallel processors cannot send the same review twice',async()=>{const f=fixture();const outcomes=await Promise.allSettled([f.run(),f.run()]);assert.equal(f.delivered.length,1);assert.equal(outcomes.filter(result=>result.status==='rejected'&&result.reason.status===409).length,1);assert.equal((await f.commerce.get('s/v3/review-requests/r.json')).status,'sent');});
test('unknown delivery remains uncertain and is never automatically retried',async()=>{const f=fixture();let attempts=0;f.deps.send=async()=>{attempts++;throw new Error('Provider might have accepted the message; private detail')};await f.run();await f.run();const record=await f.commerce.get('s/v3/review-requests/r.json');assert.equal(attempts,1);assert.equal(record.status,'delivery_uncertain');assert.equal(record.deliveryIssue,'provider_or_persistence_failure');assert.ok(!JSON.stringify(record).includes('private detail'));});
test('interrupted sending claims become uncertain without sending another message',async()=>{const f=fixture([request('r',{status:'sending',deliveryStartedAt:new Date(now-3600000).toISOString()})]);assert.equal((await f.run()).uncertain,1);assert.equal(f.delivered.length,0);assert.equal((await f.commerce.get('s/v3/review-requests/r.json')).status,'delivery_uncertain');});
test('consent and suppression are rechecked before sending and due dates must be valid',async()=>{const f=fixture([request('no-opt-in',{customer:{email:'fixture@example.com',reviewOptIn:false}}),request('future',{dueAt:new Date(now+3600000).toISOString()}),request('bad',{dueAt:'invalid'})]);const result=await f.run();assert.equal(result.suppressed,1);assert.equal(result.deferred,1);assert.equal(result.errors,1);assert.equal(f.delivered.length,0);});
test('an opt-out during preparation prevents the sending claim',async()=>{const f=fixture();f.deps.unsubscribe=async()=>{const {preferenceKey}=await import('./marketing-preferences.mjs');await f.events.setJSON(preferenceKey('s','fixture@example.com'),{unsubscribed:true});return 'https://example.com/unsubscribe'};await f.run();assert.equal(f.delivered.length,0);assert.equal((await f.commerce.get('s/v3/review-requests/r.json')).status,'suppressed');});
test('preparation errors are delayed and transport misconfiguration leaves requests untouched',async()=>{const f=fixture();f.deps.unsubscribe=async()=>{throw new Error('private credential')};await f.run();const record=await f.commerce.get('s/v3/review-requests/r.json');assert.equal(record.status,'pending');assert.equal(record.deliveryIssue,'preparation_failed');assert.ok(Date.parse(record.nextAttemptAt)>now);assert.equal((await f.run()).deferred,1);f.deps.configured=()=>false;assert.equal((await f.run()).providerConfigured,false);assert.equal(f.delivered.length,0);});
test('a tight time budget starts no delivery; preview schedule touches no store',async()=>{const f=fixture();const result=await f.run({budgetMs:7000});assert.equal(result.paused,true);assert.equal(f.delivered.length,0);await handler(new Request('https://example.com'),{deploy:{context:'deploy-preview',published:false}});});
test('health summary excludes tenant cursors and all private recipient data',()=>{assert.deepEqual(publicReviewHealth({lastRunAt:'timestamp',sent:3,siteCursor:'private',email:'private@example.com'}),{lastRunAt:'timestamp',sent:3});});
test('a post-send persistence failure leaves a durable sending claim and cannot trigger another delivery',async()=>{const f=fixture();const set=f.commerce.setJSON;let failUncertain=true;f.commerce.setJSON=async(key,value,options)=>{if(value.status==='sent')throw new Error('write failed after provider acceptance');if(value.status==='delivery_uncertain'&&failUncertain){failUncertain=false;throw new Error('storage unavailable')};return set(key,value,options)};await f.run();assert.equal((await f.commerce.get('s/v3/review-requests/r.json')).status,'sending');assert.equal(f.delivered.length,1);f.deps.clock=()=>now+16*60000;await f.run();assert.equal((await f.commerce.get('s/v3/review-requests/r.json')).status,'delivery_uncertain');assert.equal(f.delivered.length,1);});
test('a changed etag prevents sending stale customer data',async()=>{const f=fixture();const set=f.commerce.setJSON;f.deps.unsubscribe=async()=>{const key='s/v3/review-requests/r.json';const value=await f.commerce.get(key);await set(key,{...value,status:'cancelled'});return 'https://example.com/unsubscribe'};await f.run();assert.equal(f.delivered.length,0);assert.equal((await f.commerce.get('s/v3/review-requests/r.json')).status,'cancelled');});
