import test from 'node:test';import assert from 'node:assert/strict';
import {importApprovedShift} from './workforce-accounting.mjs';import {appendEntry,emptyLedger} from './business-accounting.mjs';
const site={siteId:'fixture',settings:{timezone:'America/Puerto_Rico'},employees:[{id:'employee',name:'Fixture'}]},state={siteId:'fixture',shifts:[{id:'shift-12345',employeeId:'employee',locationId:'main',start:'2026-10-10T12:00:00Z',end:'2026-10-10T14:00:00Z',breaks:[{start:'2026-10-10T13:00:00Z',end:'2026-10-10T13:10:00Z'}],paidBreaks:false,approvedAt:'2026-10-10T15:00:00Z'}]};
const rate=()=>appendEntry(emptyLedger(),{id:'rate-123456',type:'rate',revision:0,date:'2026-01-01',employeeId:'employee',hourlyCents:1200},site,'owner');
test('attendance projection is immutable, idempotent, server-derived and never paid or approved',()=>{const input={revision:1,shiftId:'shift-12345',overtimeMinutes:10,overtimeHourlyCents:1800,employeeId:'forged',regularMinutes:9999,date:'2099-01-01'};const ledger=importApprovedShift(rate(),input,state,site,'owner');const work=ledger.entries.at(-1);assert.equal(work.employeeId,'employee');assert.equal(work.regularMinutes,100);assert.equal(work.overtimeMinutes,10);assert.equal(work.amountCents,2300);assert.equal(work.approved,false);assert.equal(work.date,'2026-10-10');assert.equal(work.sourceShiftId,'shift-12345');assert.equal(ledger.entries.some(e=>e.type==='payment'),false);assert.equal(importApprovedShift(ledger,input,state,site,'owner'),ledger);});
test('unapproved, foreign, missing-rate and invalid overtime imports fail closed',()=>{const input={revision:1,shiftId:'shift-12345',overtimeMinutes:0};assert.throws(()=>importApprovedShift(rate(),input,{...state,siteId:'other'},site,'owner'),{status:403});assert.throws(()=>importApprovedShift(rate(),input,{...state,shifts:[{...state.shifts[0],approvedAt:null}]},site,'owner'),{status:409});assert.throws(()=>importApprovedShift(emptyLedger(),{...input,revision:0},state,site,'owner'),{status:409});assert.throws(()=>importApprovedShift(rate(),{...input,overtimeMinutes:111},state,site,'owner'),{status:400});});

import {createAccountingHandler} from '../functions/client-business-accounting.mjs';
test('HTTP attendance imports require owner, enforce CSRF and use CAS under concurrent retries',async()=>{
 let current=rate(),revision=0,writes=0;const db={getWithMetadata:async()=>({data:structuredClone(current),etag:String(revision)}),get:async key=>{assert.equal(key,'fixture/workforce/state.json');return structuredClone(state)},setJSON:async(key,next,options)=>{assert.equal(key,'fixture/accounting/ledger.json');if(options.onlyIfMatch!==String(revision))return {modified:false};current=structuredClone(next);revision++;writes++;return {modified:true}}};
 let authCalls=0;const handler=createAccountingHandler({authorize:async(id,roles)=>{authCalls++;assert.equal(id,'fixture');assert.deepEqual(roles,['owner']);return {site,user:{id:'owner'}}},getStore:()=>db});
 const req=(origin='https://example.invalid')=>new Request('https://example.invalid/.netlify/functions/client-business-accounting',{method:'POST',headers:{origin,'Content-Type':'application/json'},body:JSON.stringify({siteId:'fixture',type:'attendance_import',shiftId:'shift-12345',revision:1,overtimeMinutes:0,id:'untrusted-id'})});
 assert.equal((await handler(req('https://foreign.invalid'))).status,403);assert.equal(authCalls,0);
 const results=await Promise.all(Array.from({length:12},()=>handler(req())));assert(results.every(r=>[200,409].includes(r.status)));assert.equal(writes,1);assert.equal(current.entries.filter(e=>e.sourceShiftId==='shift-12345').length,1);assert.equal((await handler(req())).status,200);assert.equal(writes,1);assert.equal(current.entries.some(e=>e.type==='payment'),false);
});
