import test from 'node:test';import assert from 'node:assert/strict';
import {emptyWorkforce,transitionWorkforce,updateWorkforce,workforceView,shiftMinutes,attendanceCsv,attendanceTotals} from './workforce.mjs';
import {createWorkforceHandler} from '../functions/client-workforce.mjs';
const site={siteId:'shop',business:{locations:[{id:'branch',name:'Branch'}]},settings:{timezone:'America/Puerto_Rico'},employees:[{id:'a',name:'A',active:true,locationIds:['branch']},{id:'b',name:'B',active:true}],members:[{email:'a@example.invalid',role:'employee',locationIds:['branch']},{email:'owner@example.invalid',role:'owner'}]};
const owner={id:'owner',email:'owner@example.invalid'},user={id:'user-a',email:'a@example.invalid'},role={role:'employee',locationIds:['branch']},admin={role:'owner'};
let seq=0;const op=(action,extra={})=>({action,operationId:`operation-${++seq}`,...extra});
function setup(){let s=emptyWorkforce('shop');s=transitionWorkforce(s,op('configure',{enabled:true,paidBreaks:false}),site,owner,admin,1000000).state;return transitionWorkforce(s,op('bind',{email:user.email,employeeId:'a',locationId:'branch'}),site,owner,admin,1000000).state;}
function store(initial){let saved=initial?{data:structuredClone(initial),etag:'0'}:null,n=0;return {get:async()=>structuredClone(saved?.data||null),getWithMetadata:async()=>structuredClone(saved),setJSON:async(key,value,options)=>{if((options.onlyIfNew&&saved)||(options.onlyIfMatch&&saved?.etag!==options.onlyIfMatch))return {modified:false};saved={data:structuredClone(value),etag:String(++n)};return {modified:true}},current:()=>saved};}
test('attendance uses server time, one active shift, break lifecycle and exact replay',()=>{let s=setup();const input=op('clock_in',{timestamp:'2099-01-01'});s=transitionWorkforce(s,input,site,user,role,3600000).state;assert.equal(s.shifts[0].start,'1970-01-01T01:00:00.000Z');assert.equal(transitionWorkforce(s,input,site,user,role,3601000).reused,true);assert.throws(()=>transitionWorkforce(s,op('clock_in'),site,user,role),{status:409});s=transitionWorkforce(s,op('start_break'),site,user,role,5400000).state;assert.throws(()=>transitionWorkforce(s,op('start_break'),site,user,role),{status:409});s=transitionWorkforce(s,op('end_break'),site,user,role,6000000).state;s=transitionWorkforce(s,op('clock_out'),site,user,role,7200000).state;assert.deepEqual(shiftMinutes(s.shifts[0]),{workedMinutes:50,breakMinutes:10,elapsedMinutes:60});assert.throws(()=>transitionWorkforce(s,op('clock_out'),site,user,role),{status:409});assert.equal(s.shifts[0].approvedAt,undefined);assert.equal(s.events.length,6);});
test('identity cannot choose arbitrary employee or inherit another identity login',()=>{const s=setup();assert.throws(()=>transitionWorkforce(s,op('clock_in',{employeeId:'b'}),site,user,role),{status:400});assert.throws(()=>transitionWorkforce(s,op('bind',{email:user.email,employeeId:'b'}),site,user,role),{status:403});const active=transitionWorkforce(s,op('clock_in'),site,user,role).state;assert.throws(()=>transitionWorkforce(active,op('clock_out'),site,{...user,id:'replacement'},role),{status:403});assert.throws(()=>transitionWorkforce(active,op('bind',{email:user.email,employeeId:'b'}),site,owner,admin),{status:409});assert.throws(()=>transitionWorkforce(active,op('configure',{enabled:false,paidBreaks:false}),site,owner,admin),{status:409});});
test('concurrent clock-ins commit only one shift; same operation concurrent replay is safe',async()=>{const db=store(setup());const results=await Promise.allSettled(Array.from({length:12},()=>updateWorkforce(db,site,op('clock_in'),user,role,3600000)));assert.equal(results.filter(r=>r.status==='fulfilled').length,1);assert.equal(db.current().data.shifts.filter(s=>!s.end).length,1);const db2=store(setup()),input=op('clock_in');const replay=await Promise.all(Array.from({length:8},()=>updateWorkforce(db2,site,input,user,role,3600000)));assert.equal(replay.length,8);assert.equal(db2.current().data.shifts.length,1);});
test('corrections preserve originals, require review and lock approved hours',()=>{let s=setup();s=transitionWorkforce(s,op('clock_in'),site,user,role,3600000).state;s=transitionWorkforce(s,op('clock_out'),site,user,role,7200000).state;const id=s.shifts[0].id;s=transitionWorkforce(s,op('request_correction',{shiftId:id,start:'1970-01-01T01:10:00Z',end:'1970-01-01T02:00:00Z',reason:'Clock correction'}),site,user,role,9000000).state;assert.throws(()=>transitionWorkforce(s,op('approve',{shiftId:id}),site,owner,admin,9000000),{status:409});assert.throws(()=>transitionWorkforce(s,op('review_correction',{requestId:s.requests[0].id,accept:true}),site,user,role,9000000),{status:403});s=transitionWorkforce(s,op('review_correction',{requestId:s.requests[0].id,accept:true}),site,owner,admin,9000000).state;assert.equal(s.shifts[0].start,'1970-01-01T01:00:00.000Z');assert.equal(workforceView(s,site,user,role).shifts[0].workedMinutes,50);s=transitionWorkforce(s,op('approve',{shiftId:id}),site,owner,admin,9000000).state;assert.throws(()=>transitionWorkforce(s,op('request_correction',{shiftId:id}),site,user,role),{status:409});});
test('private views contain only own shifts, no salary fields and safe CSV',()=>{let s=setup();s=transitionWorkforce(s,op('clock_in'),site,user,role,3600000).state;s.shifts.push({...s.shifts[0],id:'other',employeeId:'b',userId:'other'});const view=workforceView(s,site,user,role,5400000);assert.equal(view.shifts.length,1);assert.equal(view.employees.length,1);assert.equal(view.bindings.length,0);assert.equal(JSON.stringify(view).includes('hourlyCents'),false);assert.equal(workforceView(s,site,{id:'unknown',email:'unknown@example.invalid'},role).shifts.length,0);assert(!attendanceCsv(view,'','','b').includes('other'));assert.throws(()=>attendanceCsv(view,'bad'),{status:400});});
test('handler enforces tenant auth, CSRF, methods and never uses browser clock',async()=>{const db=store(setup());const handler=createWorkforceHandler({authorize:async id=>{if(id!=='shop')throw Object.assign(Error('Denied'),{status:403});return {site,user,membership:role}},getStore:()=>db,clock:()=>3600000});const make=(method,body,origin='https://qa.invalid')=>new Request('https://qa.invalid/.netlify/functions/client-workforce?siteId=shop',{method,headers:{origin,'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});assert.equal((await handler(make('POST',{siteId:'shop',...op('clock_in')},'https://bad.invalid'))).status,403);assert.equal((await handler(make('DELETE'))).status,405);assert.equal((await handler(make('POST',{siteId:'other',...op('clock_in')}))).status,403);const r=await handler(make('POST',{siteId:'shop',...op('clock_in'),now:999999999}));assert.equal(r.status,200);assert.equal((await r.json()).serverNow,'1970-01-01T01:00:00.000Z');const broken={...db,getWithMetadata:async()=>({data:setup()})};await assert.rejects(()=>updateWorkforce(broken,site,op('clock_in'),user,role),{status:503});});

test('business timezone totals clip overnight shifts and unpaid breaks at midnight',()=>{const shifts=[{start:'2026-10-12T03:00:00Z',end:'2026-10-12T05:00:00Z',paidBreaks:false,breaks:[{start:'2026-10-12T03:50:00Z',end:'2026-10-12T04:10:00Z'}]}];const totals=attendanceTotals(shifts,Date.parse('2026-10-12T06:00:00Z'),'America/Puerto_Rico');assert.equal(totals.todayMinutes,50);assert.equal(totals.weekMinutes,50);assert.equal(totals.weekStart,'2026-10-12');assert.throws(()=>attendanceCsv({shifts:[],timeZone:'America/Puerto_Rico'},'2026-02-30'),{status:400});});

test('branch-limited managers cannot read or approve shifts at another location',()=>{const state=setup();state.shifts.push({id:'other-branch',employeeId:'b',userId:'other',locationId:'outside',start:'2026-10-10T12:00:00Z',end:'2026-10-10T13:00:00Z',breaks:[],paidBreaks:false});const manager={role:'manager',locationIds:['branch']};assert.throws(()=>transitionWorkforce(state,op('configure',{enabled:false,paidBreaks:false}),site,owner,manager),{status:403});assert.equal(workforceView(state,site,owner,manager).shifts.length,0);assert.throws(()=>transitionWorkforce(state,op('approve',{shiftId:'other-branch'}),site,owner,manager),{status:403});assert.throws(()=>transitionWorkforce(state,op('bind',{email:user.email,employeeId:'a',locationId:''}),site,owner,manager),{status:403});});

test('authorized administrative close uses server time and preserves reason without approving payroll',()=>{let state=setup();state=transitionWorkforce(state,op('clock_in'),site,user,role,3600000).state;const id=state.shifts[0].id;assert.throws(()=>transitionWorkforce(state,op('close_shift',{shiftId:id,reason:'Employee account inactive'}),site,user,role,7200000),{status:403});state=transitionWorkforce(state,op('close_shift',{shiftId:id,reason:'Employee account inactive',end:'2099-01-01'}),site,owner,admin,7200000).state;assert.equal(state.shifts[0].end,'1970-01-01T02:00:00.000Z');assert.equal(state.shifts[0].closedBy,'owner');assert.equal(state.shifts[0].approvedAt,undefined);});

test('malformed attendance payloads fail before authorization or storage',async()=>{const handler=createWorkforceHandler({authorize:async()=>{throw Error('Authorization must not run')},getStore:()=>{throw Error('Storage must not run')}});for(const body of ['null','[]','123','"invalid"','{']){const response=await handler(new Request('https://fixture.invalid/.netlify/functions/client-workforce',{method:'POST',headers:{origin:'https://fixture.invalid','Content-Type':'application/json'},body}));assert.equal(response.status,400);}});
