import {useEffect,useState} from 'react'
import {PortalPanel} from './PortalPanel'
import {withAuthRetry} from './auth-retry'
type Health={lastRunAt:string;ok:boolean;tenants:number;assets?:number;assetBytes?:number;issue?:string}
export default function BackupScheduleHealth({lang,sites}:{lang:'es'|'en';sites:{siteId:string;businessName:string}[]}){
 const es=lang==='es',[data,setData]=useState<{enabled:boolean;health:Health|null}|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[siteId,setSiteId]=useState(''),[report,setReport]=useState<{verifiedRecords:number;verifiedAssets:number}|null>(null)
 useEffect(()=>{let active=true;void withAuthRetry(async()=>{const response=await fetch('/.netlify/functions/tenant-backup-health',{credentials:'same-origin',cache:'no-store'});if(!response.ok)throw Error(es?'No se pudo consultar backups.':'Unable to check backups.');return response.json()}).then(value=>{if(active)setData(value)}).catch(e=>{if(active)setError(e.message)});return()=>{active=false}},[])
 const verify=async()=>{setBusy(true);setError('');setReport(null);try{const value=await withAuthRetry(async()=>{const response=await fetch('/.netlify/functions/verify-tenant-backup',{method:'POST',credentials:'same-origin',cache:'no-store',headers:{'Content-Type':'application/json'},body:JSON.stringify({siteId})});if(!response.ok)throw Error(es?'No hay una copia completa verificable o requiere revisión.':'No complete verifiable backup exists or it requires review.');return response.json()});setReport(value)}catch(e){setError(e instanceof Error?e.message:'Verification failed')}finally{setBusy(false)}}
 return <PortalPanel className="wfa-card"><header><div><small>{es?'COPIAS DE SEGURIDAD':'BACKUPS'}</small><h2>{es?'Copias con imágenes':'Snapshots with images'}</h2></div></header>{error&&<p role="alert">{error}</p>}{data&&!data.enabled&&<p>{es?'La programación no está activada en este entorno.':'Scheduled snapshots are not enabled in this environment.'}</p>}{data?.health&&<><p>{new Date(data.health.lastRunAt).toLocaleString(es?'es-PR':'en-US')}</p><p role={data.health.ok?undefined:'alert'}>{data.health.ok?(es?'Última copia completada y verificada.':'Last snapshot completed and verified.'):(es?'La última copia requiere revisión.':'The last snapshot requires review.')}</p></>}<label>{es?'Negocio':'Business'}<select value={siteId} onChange={e=>{setSiteId(e.target.value);setReport(null)}}><option value="">{es?'Seleccionar negocio':'Select business'}</option>{sites.map(site=><option key={site.siteId} value={site.siteId}>{site.businessName}</option>)}</select></label><button disabled={!siteId||busy} onClick={()=>void verify()}>{busy?(es?'Verificando…':'Verifying…'):(es?'Verificar última copia':'Verify latest snapshot')}</button>{report&&<p role="status">{report.verifiedRecords} {es?'registros y':'records and'} {report.verifiedAssets} {es?'archivos verificados.':'verified files.'}</p>}<p className="wfa-note">{es?'Esta comprobación no modifica el negocio. Las copias no son transaccionales y las integraciones externas requieren reconexión.':'This check does not change the business. Snapshots are not transactional and external integrations require reconnection.'}</p></PortalPanel>
}
