import { useMemo, useState } from 'react'
import { PortalPanel } from './PortalPanel'

type Booking = {transactionId:string;kind:string;status:string;start?:string;customer:{name?:string};employeeId?:string}
export function BookingCalendar({records,lang,timeZone='America/Puerto_Rico',employees=[]}:{records:Booking[];lang:'es'|'en';timeZone?:string;employees?:Array<{id:string;name:string}>}) {
  const es=lang==='es', locale=es?'es-PR':'en-US'
  const dayKey=(date:Date)=>new Intl.DateTimeFormat('en-CA',{timeZone,year:'numeric',month:'2-digit',day:'2-digit'}).format(date)
  const today=dayKey(new Date())
  const [month,setMonth]=useState(today.slice(0,7)), [selected,setSelected]=useState(today), [employee,setEmployee]=useState('all')
  const rows=useMemo(()=>records.filter(r=>r.kind==='booking'&&['confirmed','completed'].includes(r.status)&&r.start&&Number.isFinite(Date.parse(r.start))&&(employee==='all'||r.employeeId===employee)).sort((a,b)=>Date.parse(a.start!)-Date.parse(b.start!)),[records,employee])
  const days=new Map<string,Booking[]>()
  for(const row of rows){const key=dayKey(new Date(row.start!));days.set(key,[...(days.get(key)||[]),row])}
  const [year,monthNumber]=month.split('-').map(Number), count=new Date(Date.UTC(year,monthNumber,0)).getUTCDate(), first=new Date(Date.UTC(year,monthNumber-1,1)).getUTCDay()
  const move=(amount:number)=>{const date=new Date(Date.UTC(year,monthNumber-1+amount,1));const key=date.toISOString().slice(0,7);setMonth(key);setSelected(`${key}-01`)}
  const labels=Array.from({length:7},(_,i)=>new Intl.DateTimeFormat(locale,{weekday:'short',timeZone:'UTC'}).format(new Date(Date.UTC(2026,0,4+i))))
  return <PortalPanel className="ca-panel ca-booking-calendar"><header><h2>{es?'Calendario de citas':'Appointment calendar'}</h2><p>{es?'Las citas confirmadas aparecen aquí aunque se paguen al llegar. Google Calendar se sincroniza por separado.':'Confirmed appointments appear here even when payment is due on arrival. Google Calendar syncs separately.'}</p><small>{timeZone}</small></header><div className="ca-booking-calendar-controls"><button aria-label={es?'Mes anterior':'Previous month'} onClick={()=>move(-1)}>‹</button><strong>{new Intl.DateTimeFormat(locale,{month:'long',year:'numeric',timeZone:'UTC'}).format(new Date(Date.UTC(year,monthNumber-1,1)))}</strong><button aria-label={es?'Mes siguiente':'Next month'} onClick={()=>move(1)}>›</button><button onClick={()=>{setMonth(today.slice(0,7));setSelected(today)}}>{es?'Hoy':'Today'}</button><label>{es?'Empleado':'Employee'}<select value={employee} onChange={e=>setEmployee(e.target.value)}><option value="all">{es?'Todos':'All'}</option>{employees.map(e=><option value={e.id} key={e.id}>{e.name}</option>)}</select></label></div><div className="ca-booking-month" role="group" aria-label={es?'Días del mes':'Days of the month'}>{labels.map((label,i)=><small key={`label-${i}`}>{label}</small>)}{Array.from({length:first},(_,i)=><span key={`empty-${i}`}/>)}{Array.from({length:count},(_,i)=>{const day=`${month}-${String(i+1).padStart(2,'0')}`,n=days.get(day)?.length||0;return <button key={day} aria-label={`${day} · ${n} ${es?'citas':'appointments'}`} aria-pressed={day===selected} onClick={()=>setSelected(day)}><b>{i+1}</b>{n>0&&<span>{n}</span>}</button>})}</div><h3>{new Intl.DateTimeFormat(locale,{dateStyle:'full',timeZone:'UTC'}).format(new Date(`${selected}T12:00:00Z`))}</h3><div className="ca-booking-agenda">{!(days.get(selected)?.length)?<p>{es?'No hay citas confirmadas para este día.':'No confirmed appointments for this day.'}</p>:days.get(selected)!.map(row=><article key={row.transactionId}><time>{new Intl.DateTimeFormat(locale,{timeZone,hour:'numeric',minute:'2-digit'}).format(new Date(row.start!))}</time><strong>{row.customer?.name||row.transactionId}</strong><span>{employees.find(e=>e.id===row.employeeId)?.name}</span></article>)}</div></PortalPanel>
}
