import { useEffect, useRef, useState, type FormEvent } from 'react'
import { withAuthRetry } from './auth-retry'
import { PortalPanel } from './PortalPanel'
import './business-accounting.css'

type Employee={id:string;name:string}
type Entry={id:string;type:string;date:string;employeeId?:string;employeeName?:string;amountCents?:number;note?:string;description?:string;category?:string;approved?:boolean;paidCents?:number;pendingCents?:number;regularMinutes?:number;overtimeMinutes?:number;hourlyCents?:number}
type EmployeeMetric={employeeId:string;name:string;hourlyCents:number|null;regularMinutes:number;overtimeMinutes:number;salaryCents:number;commissionCents:number;tipCents:number;grossCents:number;paidCents:number;pendingCents:number;estimatedRevenueCents:number}
type Sale={transactionId:string;employeeId:string;date:string;status:string;estimatedRevenueCents:number;review:boolean}
type Report={inventory:Array<{itemId:string;name:string;quantityNow:number;unitCostCents:number|null;estimatedValueCents:number|null}>;summary:Record<string,number>;employees:EmployeeMetric[];work:Entry[];expenses:Entry[];entries:Entry[];sales:Sale[]}
const money=(v:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(v/100)
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'America/Puerto_Rico',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())
const endpoint='/.netlify/functions/client-business-accounting'
const blank=()=>({date:today(),employeeId:'',hourly:'',regular:'',overtime:'0',overtimeRate:'',commission:'0',tips:'0',category:'operations',description:'',amount:'',quantity:'0',itemId:'',reference:'',note:'',targetId:'',transactionId:''})
const cents=(v:string)=>Math.round(Number(v)*100)

export function BusinessAccountingPanel({siteId,employees,catalog,lang,initialMode='work'}:{siteId:string;employees:Employee[];catalog:Array<{id:string;name?:string;nameEn?:string}>;lang:'es'|'en';initialMode?:string}){
 const es=lang==='es',t=(a:string,b:string)=>es?a:b
 const [from,setFrom]=useState(()=>today().slice(0,7)+'-01'),[to,setTo]=useState(today),[employeeFilter,setEmployeeFilter]=useState('')
 const [report,setReport]=useState<Report|null>(null),[revision,setRevision]=useState(0),[busy,setBusy]=useState(false),[loading,setLoading]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('')
 const [mode,setMode]=useState(initialMode),[form,setForm]=useState(blank),[requestId,setRequestId]=useState(()=>crypto.randomUUID())
 const loadSequence=useRef(0)
 const query=()=>new URLSearchParams({siteId,from,to,employeeId:employeeFilter})
 const load=async()=>{const sequence=++loadSequence.current;setLoading(true);setError('');try{const response=await withAuthRetry(()=>fetch(`${endpoint}?${query()}`,{credentials:'include',cache:'no-store'}));const result=await response.json();if(!response.ok)throw new Error(result.message);if(sequence===loadSequence.current){setReport(result.report);setRevision(result.revision)}}catch(e){if(sequence===loadSequence.current){setReport(null);setError(e instanceof Error?e.message:'Error')}}finally{if(sequence===loadSequence.current)setLoading(false)}}
 useEffect(()=>{setReport(null);void load();return()=>{loadSequence.current++}},[siteId,from,to,employeeFilter])
 useEffect(()=>{setForm(blank());setRequestId(crypto.randomUUID())},[siteId])
 const change=(key:keyof ReturnType<typeof blank>,value:string)=>{setForm(old=>({...old,[key]:value}));setRequestId(crypto.randomUUID())}
 const mutate=async(payload:Record<string,unknown>,id:string)=>{setBusy(true);setError('');setMessage('');try{const response=await withAuthRetry(()=>fetch(endpoint,{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({...payload,siteId,revision,id})}));const result=await response.json();if(!response.ok)throw new Error(result.message);setRequestId(crypto.randomUUID());setForm(blank());setMessage(t('Registro guardado.','Record saved.'));await load()}catch(e){setError(e instanceof Error?e.message:'Error');setReport(null)}finally{setBusy(false)}}
 const submit=(event:FormEvent)=>{event.preventDefault();const payload:Record<string,unknown>={...form,type:mode,hourlyCents:cents(form.hourly),regularMinutes:Math.round(Number(form.regular)*60),overtimeMinutes:Math.round(Number(form.overtime)*60),overtimeHourlyCents:cents(form.overtimeRate),commissionCents:cents(form.commission),tipCents:cents(form.tips),amountCents:cents(form.amount),quantity:Number(form.quantity)};void mutate(payload,requestId)}
 const download=async()=>{setBusy(true);setError('');try{const response=await withAuthRetry(()=>fetch(`${endpoint}?${query()}&format=csv`,{credentials:'include',cache:'no-store'}));if(!response.ok){const result=await response.json();throw new Error(result.message)}const url=URL.createObjectURL(await response.blob()),anchor=document.createElement('a');anchor.href=url;anchor.download=`business-accounting-${from}-${to}.csv`;anchor.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}catch(e){setError(e instanceof Error?e.message:'Error')}finally{setBusy(false)}}
 const field=(key:keyof ReturnType<typeof blank>,label:string,type='text',required=true)=><label>{label}<input type={type} value={form[key]} onChange={e=>change(key,e.target.value)} required={required} {...(type==='number'?{min:0,step:key==='quantity'?1:0.01}:{})}/></label>
 const employeeSelect=<label>{t('Empleado','Employee')}<select value={form.employeeId} onChange={e=>change('employeeId',e.target.value)} required={mode!=='expense'}><option value="">{t('Seleccionar','Select')}</option>{employees.map(e=><option value={e.id} key={e.id}>{e.name}</option>)}</select></label>
 const modes=[['rate',t('Salario por hora','Hourly rate')],['work',t('Registrar horas','Record hours')],['expense',t('Costos y gastos','Costs and expenses')],['payment',t('Registrar pago','Record payment')],['allocation',t('Asignar venta','Assign sale')],['void',t('Corregir registro','Correct record')]]
 return <PortalPanel className="ca-panel wf-accounting"><header><h2>{t('Sueldos, costos y contabilidad','Wages, costs and accounting')}</h2><p>{t('Control privado del dueño. Salarios y horas reales, separados de los ingresos que genera cada empleado.','Private owner controls. Actual wages and hours, separate from revenue generated by each employee.')}</p></header>
 <div className="ca-grid"><label>{t('Desde','From')}<input type="date" value={from} onChange={e=>setFrom(e.target.value)} disabled={busy}/></label><label>{t('Hasta','Through')}<input type="date" value={to} onChange={e=>setTo(e.target.value)} disabled={busy}/></label><label>{t('Filtrar empleado','Filter employee')}<select value={employeeFilter} onChange={e=>setEmployeeFilter(e.target.value)} disabled={busy}><option value="">{t('Todo el negocio','Whole business')}</option>{employees.map(e=><option key={e.id} value={e.id}>{e.name}</option>)}</select></label></div>
 <div className="ca-export-actions"><button disabled={busy||loading||!report} onClick={download}>{t('Descargar información contable (CSV / Excel)','Download accounting information (CSV / Excel)')}</button><button disabled={busy||loading} onClick={()=>void load()}>{t('Actualizar','Refresh')}</button></div>
 {error&&<div className="ca-error" role="alert">{error}</div>}{message&&<p role="status">{message}</p>}{loading&&<p role="status">{t('Cargando registros…','Loading records…')}</p>}
 {report&&!loading&&<><div className="ca-v3-metrics">{[
 ['estimatedRevenueCents',t('Ingresos netos estimados','Estimated net revenue')],['salaryCents',t('Sueldos + comisiones aprobados','Approved wages + commissions')],['operatingCents',t('Gastos operacionales','Operating expenses')],['materialsCents',t('Materiales consumidos','Materials consumed')],['purchaseCents',t('Compras de inventario','Inventory purchases')],['estimatedResultCents',t('Resultado estimado','Estimated result')],['paidCents',t('Pagos registrados de estas horas','Payments recorded for these hours')],['pendingCents',t('Bruto pendiente de estas horas','Gross balance for these hours')]
 ].map(([key,label])=><article key={key}><small>{label}</small><strong>{money(report.summary[key])}</strong></article>)}</div>
 <p>{t('Horas aprobadas','Approved hours')}: {(report.summary.regularMinutes/60).toFixed(2)} · {t('Horas extra','Overtime')}: {(report.summary.overtimeMinutes/60).toFixed(2)} · {t('Ingresos sin asignar','Unassigned revenue')}: {money(report.summary.unassignedRevenueCents)}</p>
 <div className="wf-accounting-scroll"><table><caption>{t('Métricas por empleado • tarifa vigente al fin del periodo','Employee metrics • rate effective at period end')}</caption><thead><tr>{[t('Empleado','Employee'),t('Salario / hr','Wage / hr'),t('Horas / extra','Hours / overtime'),t('Sueldo','Wages'),t('Comisión','Commission'),t('Propinas','Tips'),t('Pagado','Paid'),t('Pendiente bruto','Gross pending'),t('Ingresos estimados','Estimated revenue')].map(label=><th key={label} scope="col">{label}</th>)}</tr></thead><tbody>{report.employees.map(e=><tr key={e.employeeId}><th scope="row">{e.name}</th><td>{e.hourlyCents===null?t('Sin asignar','Not set'):money(e.hourlyCents)}</td><td>{(e.regularMinutes/60).toFixed(2)} / {(e.overtimeMinutes/60).toFixed(2)}</td><td>{money(e.salaryCents)}</td><td>{money(e.commissionCents)}</td><td>{money(e.tipCents)}</td><td>{money(e.paidCents)}</td><td>{money(e.pendingCents)}</td><td>{money(e.estimatedRevenueCents)}</td></tr>)}</tbody></table></div>
 <details><summary>{t('Inventario actual y costos de referencia','Current inventory and reference costs')}</summary><p>{t('Existencias actuales, no históricas; costo de la última compra registrada hasta la fecha final. No es una valoración contable definitiva.','Current stock, not historical; cost of the last recorded purchase through the end date. This is not a final accounting valuation.')}</p><div className="ca-list">{report.inventory.map(i=><article key={i.itemId}><strong>{i.name} · {i.quantityNow}</strong><p>{t('Costo unitario','Unit cost')}: {i.unitCostCents===null?t('Sin registrar','Not recorded'):money(i.unitCostCents)} · {t('Valor estimado','Estimated value')}: {i.estimatedValueCents===null?'—':money(i.estimatedValueCents)}</p></article>)}</div></details>
 <h3>{t('Horas registradas','Recorded hours')}</h3><div className="ca-list">{report.work.length===0?<p>{t('No hay horas en este periodo.','No hours in this period.')}</p>:report.work.map(w=><article key={w.id}><strong>{w.employeeName} · {w.date}</strong><p>{((w.regularMinutes||0)/60).toFixed(2)} h + {((w.overtimeMinutes||0)/60).toFixed(2)} {t('extra','overtime')} · {money(w.amountCents||0)} {t('bruto','gross')}</p><small>{w.id} · {w.approved?t('Aprobado','Approved'):t('Pendiente de aprobación','Pending approval')}</small>{!w.approved&&<button disabled={busy} onClick={()=>void mutate({type:'approve',targetId:w.id,date:today()},crypto.randomUUID())}>{t('Aprobar horas y cálculo','Approve hours and calculation')}</button>}</article>)}</div>
 <details><summary>{t('Ver gastos e historial del periodo','View expenses and period history')}</summary><div className="ca-list">{report.entries.map(e=><article key={e.id}><strong>{e.date} · {e.type} · {e.employeeName||''}</strong><p>{e.description||e.note} {e.amountCents!==undefined?money(e.amountCents):''}</p><small>{e.id}</small></article>)}</div></details></>}
 <form onSubmit={submit}><fieldset disabled={busy||loading||!report}><legend>{t('Añadir o corregir información','Add or correct information')}</legend><label>{t('Acción','Action')}<select value={mode} onChange={e=>{setMode(e.target.value);setForm(blank());setRequestId(crypto.randomUUID())}}>{modes.map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></label><div className="ca-grid">{field('date',mode==='rate'?t('Vigente desde','Effective from'):t('Fecha','Date'),'date')}
 {['rate','work','expense','allocation'].includes(mode)&&employeeSelect}
 {mode==='rate'&&field('hourly',t('Salario por hora (USD)','Hourly wage (USD)'),'number')}
 {mode==='work'&&<>{field('regular',t('Horas regulares','Regular hours'),'number')}{field('overtime',t('Horas extra','Overtime hours'),'number')}{Number(form.overtime)>0&&field('overtimeRate',t('Tarifa por hora extra (USD)','Overtime hourly rate (USD)'),'number')}{field('commission',t('Comisión acordada (USD)','Agreed commission (USD)'),'number')}{field('tips',t('Propinas a pagar (USD)','Tips payable (USD)'),'number')}</>}
 {mode==='expense'&&<><label>{t('Categoría','Category')}<select value={form.category} onChange={e=>change('category',e.target.value)}><option value="operations">{t('Gasto operacional','Operating expense')}</option><option value="material_consumption">{t('Material / inventario consumido','Material / inventory consumed')}</option><option value="inventory_purchase">{t('Compra de inventario','Inventory purchase')}</option></select></label>{field('description',t('Descripción','Description'))}{field('amount',t('Costo total (USD)','Total cost (USD)'),'number')}{field('quantity',t('Cantidad de referencia','Reference quantity'),'number')}<label>{t('Producto / servicio relacionado','Related product / service')}<select value={form.itemId} onChange={e=>change('itemId',e.target.value)}><option value="">{t('No aplica','Not applicable')}</option>{catalog.map(e=><option key={e.id} value={e.id}>{e.nameEn||e.name||e.id}</option>)}</select></label>{field('reference',t('Referencia de factura / comprobante','Invoice / receipt reference'),'text',false)}</>}
 {mode==='payment'&&<><label>{t('Horas aprobadas que se pagan','Approved work being paid')}<select required value={form.targetId} onChange={e=>change('targetId',e.target.value)}><option value="">{t('Seleccionar','Select')}</option>{report?.work.filter(w=>w.approved&&(w.pendingCents||0)>0).map(w=><option key={w.id} value={w.id}>{w.employeeName} · {w.date} · {money(w.pendingCents||0)}</option>)}</select></label>{field('amount',t('Pago registrado (USD)','Recorded payment (USD)'),'number')}</>}
 {mode==='allocation'&&<label>{t('Venta / reservación','Sale / booking')}<select required value={form.transactionId} onChange={e=>change('transactionId',e.target.value)}><option value="">{t('Seleccionar','Select')}</option>{report?.sales.map(s=><option value={s.transactionId} key={s.transactionId}>{s.date} · {s.transactionId} · {money(s.estimatedRevenueCents)}</option>)}</select></label>}
 {mode==='void'&&<label>{t('Registro a anular (conserva historial)','Entry to void (keeps history)')}<select required value={form.targetId} onChange={e=>change('targetId',e.target.value)}><option value="">{t('Seleccionar','Select')}</option>{report?.entries.filter(e=>!['void','approve'].includes(e.type)).map(e=><option value={e.id} key={e.id}>{e.date} · {e.type} · {e.employeeName||e.description||e.id}</option>)}</select></label>}
 {field('note',mode==='void'?t('Motivo obligatorio','Required reason'):t('Nota','Note'),'text',mode==='void')}</div>
 <p className="ca-note">{mode==='expense'?t('Este registro mide costos. No cambia las existencias físicas; utiliza los controles de Inventario para entradas, consumo o ajustes.','This records costs. It does not change stock quantities; use Inventory controls for receipts, consumption or adjustments.'):mode==='work'?t('Horas manuales sujetas a aprobación. La tarifa regular se toma del historial vigente en esa fecha. La tarifa extra la determina el dueño; no se calcula automáticamente una obligación de nómina.','Manual hours require approval. The regular rate comes from history for that date. The owner supplies the overtime rate; payroll obligations are not calculated automatically.'):mode==='payment'?t('Registra un pago ya realizado; no transfiere dinero. El balance es bruto y no calcula deducciones.','Record a payment already made; this does not transfer money. The balance is gross and does not calculate deductions.'):mode==='rate'?t('Guarda el empleado primero. Los nuevos salarios no cambian cálculos de horas ya registradas.','Save the employee first. New rates do not change work already recorded.'):''}</p><button className="ca-save" type="submit">{busy?t('Guardando…','Saving…'):t('Guardar registro','Save record')}</button></fieldset></form>
 <p className="ca-note">{t('Información administrativa para tu contable, no una planilla ni nómina neta. El resultado excluye IVU, propinas y compras de inventario; descuenta sueldos aprobados, comisiones, gastos y consumo registrado. No restes una compra y su consumo como el mismo gasto. Los reembolsos se prorratean para estimar ingresos y se agrupan en la fecha original del cobro; requieren conciliación. El CSV incluye métricas, ventas, horas, salarios, costos, pagos e historial.','Administrative information for your accountant, not a tax return or net payroll. The result excludes tax, tips and inventory purchases; it subtracts approved wages, commissions, expenses and recorded consumption. Do not count a purchase and its consumption as the same expense. Refunds are allocated proportionally to estimate revenue and grouped under the original payment date; reconciliation is required. CSV includes metrics, sales, hours, rates, costs, payments and history.')}</p>
 </PortalPanel>
}
