import { useEffect, useMemo, useState, type FormEvent } from 'react'
import './client-storefront.css'

type Item={id:string;type:'product'|'service';name:string;description:string;price:number;inventory:number|null;requiresAppointment:boolean;duration:number;imageUrl:string}
type Employee={id:string;name:string;role:string;serviceIds:string[]}
type Site={siteId:string;slug:string;business:any;design:any;features:Record<string,boolean>;catalog:Item[];employees:Employee[];hours:any;paymentRules:any;settings:any}
type CartLine={id:string;quantity:number}
const money=(value:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(value)

export default function ClientStorefront({slug}:{slug:string}){
  const [site,setSite]=useState<Site|null>(null);const [error,setError]=useState('');const [lang,setLang]=useState<'es'|'en'>('es');const [catalog,setCatalog]=useState(false);const [cart,setCart]=useState<CartLine[]>([]);const [booking,setBooking]=useState<{serviceId:string;employeeId:string;date:string;start:string}|null>(null);const [slots,setSlots]=useState<Array<{start:string;end:string}>>([]);const [customer,setCustomer]=useState({name:'',email:'',phone:''});const [busy,setBusy]=useState(false);const [checkoutOpen,setCheckoutOpen]=useState(false)
  useEffect(()=>{let active=true;let initial=true;let loadedAt=0;const load=()=>fetch(`/.netlify/functions/public-client-site?slug=${encodeURIComponent(slug)}`).then(async r=>{const x=await r.json();if(!r.ok)throw new Error(x.message);if(!active)return;loadedAt=Date.now();setError('');setSite(x.site);if(initial){setLang(x.site.settings?.locale==='en'?'en':'es');initial=false}document.title=x.site.business.name}).catch(e=>{if(active)setError(e instanceof Error?e.message:'No se pudo actualizar la página.')}),refresh=()=>{if(document.visibilityState==='visible'&&Date.now()-loadedAt>60000)void load()};void load();window.addEventListener('focus',refresh);document.addEventListener('visibilitychange',refresh);return()=>{active=false;window.removeEventListener('focus',refresh);document.removeEventListener('visibilitychange',refresh)}},[slug])
  const cartItems=useMemo(()=>cart.map(line=>({line,item:site?.catalog.find(x=>x.id===line.id)})).filter(x=>x.item),[cart,site]);const total=cartItems.reduce((sum,x)=>sum+(x.item?.price||0)*x.line.quantity,0)
  const add=(item:Item)=>setCart(current=>{const found=current.find(x=>x.id===item.id);return found?current.map(x=>x.id===item.id?{...x,quantity:Math.min(20,x.quantity+1)}:x):[...current,{id:item.id,quantity:1}]})
  const beginBooking=(item:Item)=>{setBooking({serviceId:item.id,employeeId:'',date:'',start:''});setSlots([]);setCatalog(false)}
  const employees=site?.employees.filter(x=>x.serviceIds.includes(booking?.serviceId||''))||[]
  const getSlots=async(next:{serviceId:string;employeeId:string;date:string;start:string})=>{setBooking(next);if(!next.employeeId||!next.date||!site)return;setBusy(true);try{const r=await fetch('/.netlify/functions/booking-availability',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({siteId:site.siteId,serviceId:next.serviceId,employeeId:next.employeeId,date:next.date})});const x=await r.json();if(!r.ok)throw new Error(x.message);setSlots(x.slots)}catch(e){setError(e instanceof Error?e.message:'No se pudo consultar disponibilidad.')}finally{setBusy(false)}}
  const checkout=async(event:FormEvent)=>{event.preventDefault();if(!site)return;setBusy(true);setError('');try{const body=booking?{siteId:site.siteId,customer,booking}:{siteId:site.siteId,customer,items:cart};const r=await fetch('/.netlify/functions/create-client-checkout',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const x=await r.json();if(!r.ok)throw new Error(x.message);if(x.checkoutUrl)location.assign(x.checkoutUrl);else{setCheckoutOpen(false);setBooking(null);setCart([]);alert(lang==='es'?'Confirmación recibida. El pago se realizará presencialmente.':'Confirmation received. Payment is due in person.')}}catch(e){setError(e instanceof Error?e.message:'No se pudo iniciar el pago.')}finally{setBusy(false)}}
  if(error&&!site)return <main className="cs-state"><h1>No disponible</h1><p>{error}</p></main>;if(!site)return <main className="cs-state">Cargando website…</main>
  const t=lang==='es'?{catalog:'Catálogo',book:'Reservar',shop:'Comprar',cart:'Carrito',contact:'Contacto',available:'Productos y servicios',empty:'Todavía no hay artículos publicados.',team:'Selecciona un profesional',date:'Selecciona una fecha',times:'Horas disponibles',continue:'Continuar',customer:'Tus datos',pay:'Continuar al pago seguro'}:{catalog:'Catalog',book:'Book',shop:'Add to cart',cart:'Cart',contact:'Contact',available:'Products and services',empty:'No items have been published yet.',team:'Choose a professional',date:'Choose a date',times:'Available times',continue:'Continue',customer:'Your details',pay:'Continue to secure payment'}
  return <main className={`cs-site style-${String(site.design.style||'Modern').toLowerCase()}`} style={{'--cs-primary':site.design.primary||'#0b1529','--cs-accent':site.design.secondary||'#3c86f6'} as React.CSSProperties}>
    <header className="cs-nav"><a href="#top">{site.business.logoUrl?<img src={site.business.logoUrl}/>:<b>{site.business.name}</b>}</a><nav><button onClick={()=>setCatalog(true)}>{t.catalog}</button>{site.features.bookings&&<button onClick={()=>setCatalog(true)}>{t.book}</button>}<a href="#contact">{t.contact}</a></nav><div><button onClick={()=>setLang(lang==='es'?'en':'es')}>{lang==='es'?'EN':'ES'}</button><button className="cs-cart" onClick={()=>{setBooking(null);setCheckoutOpen(true)}}>{t.cart} ({cart.reduce((s,x)=>s+x.quantity,0)})</button></div></header>
    <section className="cs-hero" id="top"><div><small>{site.business.category}</small><h1>{site.business.name}</h1><p>{site.business.description}</p><div><button onClick={()=>setCatalog(true)}>{t.catalog}</button>{site.features.bookings&&<button className="ghost" onClick={()=>setCatalog(true)}>{t.book}</button>}</div></div></section>
    <section className="cs-featured"><small>{t.available.toUpperCase()}</small><div>{site.catalog.slice(0,6).map(item=><article key={item.id}>{item.imageUrl&&<img src={item.imageUrl}/>}<span>{item.type}</span><h2>{item.name}</h2><p>{item.description}</p><footer><b>{money(item.price)}</b><button onClick={()=>item.requiresAppointment?beginBooking(item):add(item)}>{item.requiresAppointment?t.book:t.shop}</button></footer></article>)}</div></section>
    <footer className="cs-footer" id="contact"><div><h2>{site.business.name}</h2><p>{site.business.description}</p></div><address>{site.business.phone&&<a href={`tel:${site.business.phone}`}>{site.business.phone}</a>}{site.business.email&&<a href={`mailto:${site.business.email}`}>{site.business.email}</a>}{site.business.mapsUrl&&<a href={site.business.mapsUrl} target="_blank">Google Maps ↗</a>}</address></footer>
    {catalog&&<div className="cs-modal" onMouseDown={()=>setCatalog(false)}><section onMouseDown={e=>e.stopPropagation()}><header><div><small>CATALOG</small><h2>{t.available}</h2></div><button onClick={()=>setCatalog(false)}>×</button></header>{site.catalog.length===0?<p>{t.empty}</p>:<div className="cs-catalog-grid">{site.catalog.map(item=><article key={item.id}>{item.imageUrl&&<img src={item.imageUrl}/>}<div><small>{item.type}</small><h3>{item.name}</h3><p>{item.description}</p><b>{money(item.price)}</b><button disabled={item.inventory===0} onClick={()=>item.requiresAppointment?beginBooking(item):add(item)}>{item.inventory===0?'Sold out':item.requiresAppointment?t.book:t.shop}</button></div></article>)}</div>}</section></div>}
    {booking&&<div className="cs-modal"><section><header><div><small>BOOKING</small><h2>{site.catalog.find(x=>x.id===booking.serviceId)?.name}</h2></div><button onClick={()=>setBooking(null)}>×</button></header><div className="cs-booking"><label>{t.team}<select value={booking.employeeId} onChange={e=>getSlots({...booking,employeeId:e.target.value,start:''})}><option value="">—</option>{employees.map(x=><option key={x.id} value={x.id}>{x.name} · {x.role}</option>)}</select></label><label>{t.date}<input type="date" min={new Date().toISOString().slice(0,10)} value={booking.date} onChange={e=>getSlots({...booking,date:e.target.value,start:''})}/></label><fieldset><legend>{t.times}</legend>{busy?<p>Consultando…</p>:slots.map(slot=><button className={booking.start===slot.start?'active':''} key={slot.start} onClick={()=>setBooking({...booking,start:slot.start})}>{new Date(slot.start).toLocaleTimeString(lang==='es'?'es-PR':'en-US',{hour:'numeric',minute:'2-digit',timeZone:site.settings.timezone})}</button>)}</fieldset><button className="cs-primary" disabled={!booking.start} onClick={()=>setCheckoutOpen(true)}>{t.continue}</button></div></section></div>}
    {checkoutOpen&&<div className="cs-modal"><section className="cs-checkout"><header><div><small>CHECKOUT</small><h2>{t.customer}</h2></div><button onClick={()=>setCheckoutOpen(false)}>×</button></header>{!booking&&<div className="cs-cart-lines">{cartItems.map(({line,item})=><div key={line.id}><span>{item?.name} × {line.quantity}</span><b>{money((item?.price||0)*line.quantity)}</b></div>)}<strong>Total <b>{money(total)}</b></strong></div>}<form onSubmit={checkout}><label>Nombre / Name<input value={customer.name} onChange={e=>setCustomer({...customer,name:e.target.value})} required/></label><label>Email<input type="email" value={customer.email} onChange={e=>setCustomer({...customer,email:e.target.value})} required/></label><label>Teléfono / Phone<input value={customer.phone} onChange={e=>setCustomer({...customer,phone:e.target.value})}/></label><button disabled={busy||(!booking&&cart.length===0)}>{busy?'Preparando…':t.pay}</button></form><p>Stripe procesa el pago. Esta página no confirma una transacción hasta recibir verificación segura del servidor.</p>{error&&<div className="cs-error">{error}</div>}</section></div>}
  </main>
}
