import { useEffect, useMemo, useState } from 'react'
import { withAuthRetry } from './auth-retry'

type Language='es'|'en'
type Transaction={transactionId:string;kind:'order'|'booking';source?:string;customer:{name:string;email:string;phone:string};items:Array<{name:string;quantity:number;unitAmount:number}>;amountTotal:number;paymentStatus:string;status:string;createdAt:string;start?:string}
type Customer={customerId:string;name:string;email:string;phone:string;tags:string[];notes:string;totalSpent:number;orderCount:number;bookingCount:number;lastActivityAt:string}
type PaymentLink={paymentLinkId:string;token:string;title:string;description:string;amount:number;active:boolean;expiresAt?:string;createdAt:string}
type Receipt={receiptId:string;transactionId:string;total:number;paymentStatus:string;createdAt:string;customer:{name:string;email:string}}
type TaxConfig={enabled:boolean;stateRate:number;municipalRate:number;pricesIncludeTax:boolean;defaultTaxable:boolean}
type Payout={id:string;amount:number;currency:string;status:string;arrivalDate:string;createdAt:string;method:string;type:string}

const api=(url:string,options?:RequestInit)=>withAuthRetry(async()=>{const response=await fetch(url,{credentials:'include',cache:'no-store',...options});const result=await response.json();if(!response.ok||result.ok===false)throw new Error(result.message||'Request failed.');return result})
const money=(cents:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format((Number(cents)||0)/100)

export function TransactionPanel({records,kind,lang,onAction,busy}:{records:Transaction[];kind:'order'|'booking';lang:Language;onAction:(r:Transaction,a:string)=>void;busy:boolean}){
  const es=lang==='es';const rows=records.filter(x=>x.kind===kind).sort((a,b)=>Date.parse(b.createdAt)-Date.parse(a.createdAt))
  return <section className="ca-panel"><header><h2>{kind==='order'?(es?'Órdenes':'Orders'):(es?'Reservaciones':'Bookings')}</h2><p>{kind==='order'?(es?'Ventas online, links de pago y futuras ventas POS aparecerán aquí.':'Online sales, payment links and future POS sales appear here.'):(es?'Administra citas, pagos y cancelaciones por separado.':'Manage appointments, payments and cancellations separately.')}</p></header><div className="ca-transactions">{rows.length===0?<p>{es?'No hay registros todavía.':'No records yet.'}</p>:rows.map(record=><article key={record.transactionId}><div><small>{kind==='order'?(es?'ORDEN':'ORDER'):(es?'CITA':'BOOKING')}</small><strong>{record.customer?.name||record.customer?.email||record.transactionId}</strong><span>{record.transactionId}</span></div><div><b>{money(record.amountTotal)}</b><span>{record.paymentStatus} · {record.status}</span>{record.start&&<time>{new Date(record.start).toLocaleString(es?'es-PR':'en-US')}</time>}</div><nav>{record.paymentStatus==='due'&&<button disabled={busy} onClick={()=>onAction(record,'mark_paid')}>{es?'Marcar pagado':'Mark paid'}</button>}{['paid','paid_in_person'].includes(record.paymentStatus)&&!['completed','refunded'].includes(record.status)&&<button disabled={busy} onClick={()=>onAction(record,'complete')}>{es?'Completar':'Complete'}</button>}{record.paymentStatus==='paid'&&!record.status.includes('refund')&&<button disabled={busy} onClick={()=>onAction(record,'refund')}>{es?'Reembolsar':'Refund'}</button>}{kind==='booking'&&record.status!=='cancelled'&&record.status!=='completed'&&<button disabled={busy} onClick={()=>onAction(record,'cancel')}>{es?'Cancelar':'Cancel'}</button>}</nav></article>)}</div></section>
}

export function CustomersPanel({siteId,lang}:{siteId:string;lang:Language}){
  const es=lang==='es';const [rows,setRows]=useState<Customer[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState('')
  const load=async()=>{setLoading(true);setError('');try{const result=await api(`/.netlify/functions/client-v3-admin?siteId=${encodeURIComponent(siteId)}&collection=customers`);setRows(result.records||[])}catch(e){setError(e instanceof Error?e.message:'Error')}finally{setLoading(false)}}
  useEffect(()=>{load()},[siteId])
  return <section className="ca-panel"><header><h2>{es?'Clientes':'Customers'}</h2><p>{es?'Los clientes se crean automáticamente desde ventas y reservaciones confirmadas.':'Customer profiles are created automatically from confirmed sales and bookings.'}</p></header>{error&&<div className="ca-error">{error}</div>}{loading?<p>{es?'Cargando clientes…':'Loading customers…'}</p>:<div className="ca-v3-table">{rows.length===0?<p>{es?'Aún no hay clientes registrados.':'No customers have been recorded yet.'}</p>:rows.map(customer=><article key={customer.customerId}><div><strong>{customer.name||customer.email||customer.phone||customer.customerId}</strong><span>{customer.email}{customer.phone&&` · ${customer.phone}`}</span></div><div><b>{money(customer.totalSpent)}</b><span>{es?'Valor total':'Lifetime value'}</span></div><div><b>{customer.orderCount}</b><span>{es?'Órdenes':'Orders'}</span></div><div><b>{customer.bookingCount}</b><span>{es?'Citas':'Bookings'}</span></div></article>)}</div>}</section>
}

export function PaymentLinksPanel({siteId,siteSlug,lang}:{siteId:string;siteSlug:string;lang:Language}){
  const es=lang==='es';const [rows,setRows]=useState<PaymentLink[]>([]);const [title,setTitle]=useState('');const [amount,setAmount]=useState('');const [busy,setBusy]=useState(false);const [error,setError]=useState('')
  const load=async()=>{try{const result=await api(`/.netlify/functions/client-v3-admin?siteId=${encodeURIComponent(siteId)}&collection=payment-links`);setRows(result.records||[])}catch(e){setError(e instanceof Error?e.message:'Error')}}
  useEffect(()=>{load()},[siteId])
  const create=async()=>{const cents=Math.round(Number(amount)*100);if(!title.trim()||!Number.isFinite(cents)||cents<=0)return setError(es?'Escribe un título y una cantidad válida.':'Enter a title and valid amount.');setBusy(true);setError('');try{await api('/.netlify/functions/client-v3-admin',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({siteId,action:'create_payment_link',value:{title,amount:cents,currency:'usd'}})});setTitle('');setAmount('');await load()}catch(e){setError(e instanceof Error?e.message:'Error')}finally{setBusy(false)}}
  const toggle=async(row:PaymentLink)=>{setBusy(true);try{await api('/.netlify/functions/client-v3-admin',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({siteId,action:'set_payment_link_active',paymentLinkId:row.paymentLinkId,active:!row.active})});await load()}catch(e){setError(e instanceof Error?e.message:'Error')}finally{setBusy(false)}}
  return <section className="ca-panel"><header><h2>{es?'Links de pago':'Payment links'}</h2><p>{es?'Crea un enlace directo de cobro para compartir por WhatsApp, redes, SMS o QR.':'Create direct payment links to share through WhatsApp, social, SMS or QR.'}</p></header>{error&&<div className="ca-error">{error}</div>}<div className="ca-grid"><label>{es?'Título':'Title'}<input value={title} onChange={e=>setTitle(e.target.value)} placeholder={es?'Ej. Depósito de cita':'e.g. Appointment deposit'}/></label><label>{es?'Cantidad USD':'Amount USD'}<input type="number" min="0.01" step="0.01" value={amount} onChange={e=>setAmount(e.target.value)}/></label></div><button className="ca-save" disabled={busy} onClick={create}>{busy?(es?'Creando…':'Creating…'):(es?'Crear link de pago':'Create payment link')}</button><div className="ca-v3-links">{rows.map(row=>{const path=`/pay/${siteSlug}/${row.token}`;return <article key={row.paymentLinkId}><div><strong>{row.title}</strong><span>{money(row.amount)} · {row.active?(es?'Activo':'Active'):(es?'Inactivo':'Inactive')}</span><code>{path}</code></div><nav><button onClick={()=>navigator.clipboard?.writeText(location.origin+path)}>{es?'Copiar':'Copy'}</button><a className="ca-primary-link secondary" href={`/.netlify/functions/client-payment-link-qr?siteId=${encodeURIComponent(siteId)}&paymentLinkId=${encodeURIComponent(row.paymentLinkId)}`} target="_blank">QR</a><button disabled={busy} onClick={()=>toggle(row)}>{row.active?(es?'Desactivar':'Disable'):(es?'Activar':'Enable')}</button></nav></article>})}</div></section>
}

export function ReceiptsPanel({siteId,lang}:{siteId:string;lang:Language}){
  const es=lang==='es';const [rows,setRows]=useState<Receipt[]>([]);const [busy,setBusy]=useState('');const [error,setError]=useState('')
  const load=()=>api(`/.netlify/functions/client-v3-admin?siteId=${encodeURIComponent(siteId)}&collection=receipts`).then(r=>setRows(r.records||[])).catch(()=>setRows([]))
  useEffect(()=>{load()},[siteId])
  const resend=async(receiptId:string)=>{setBusy(receiptId);setError('');try{await api('/.netlify/functions/client-v3-admin',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({siteId,action:'resend_receipt',receiptId})});await load()}catch(e){setError(e instanceof Error?e.message:'Error')}finally{setBusy('')}}
  return <section className="ca-panel"><header><h2>{es?'Recibos':'Receipts'}</h2><p>{es?'Registro normalizado de pagos confirmados.':'Normalized record of confirmed payments.'}</p></header>{error&&<div className="ca-error">{error}</div>}<div className="ca-transactions">{rows.length===0?<p>{es?'No hay recibos todavía.':'No receipts yet.'}</p>:rows.map(r=><article key={r.receiptId}><div><strong>{r.customer?.name||r.customer?.email||r.receiptId}</strong><span>{r.receiptId}</span></div><div><b>{money(r.total)}</b><span>{r.paymentStatus}</span><time>{new Date(r.createdAt).toLocaleString(es?'es-PR':'en-US')}</time></div><nav><a className="ca-primary-link secondary" href={`/.netlify/functions/client-receipt-pdf?siteId=${encodeURIComponent(siteId)}&receiptId=${encodeURIComponent(r.receiptId)}`} target="_blank">{es?'Abrir PDF':'Open PDF'}</a>{r.customer?.email&&<button disabled={busy===r.receiptId} onClick={()=>resend(r.receiptId)}>{busy===r.receiptId?(es?'Enviando…':'Sending…'):(es?'Reenviar':'Resend')}</button>}</nav></article>)}</div></section>
}

export function AnalyticsPanel({commerce,lang}:{commerce:{orders:Transaction[];bookings:Transaction[]};lang:Language}){
  const es=lang==='es';const all=[...commerce.orders,...commerce.bookings];const paid=all.filter(x=>['paid','paid_in_person'].includes(x.paymentStatus));const revenue=paid.reduce((s,x)=>s+Number(x.amountTotal||0),0);const average=paid.length?Math.round(revenue/paid.length):0
  const orderRevenue=commerce.orders.filter(x=>['paid','paid_in_person'].includes(x.paymentStatus)).reduce((s,x)=>s+Number(x.amountTotal||0),0)
  const bookingRevenue=commerce.bookings.filter(x=>['paid','paid_in_person'].includes(x.paymentStatus)).reduce((s,x)=>s+Number(x.amountTotal||0),0)
  const itemMap=new Map<string,{name:string;quantity:number;revenue:number}>()
  paid.forEach(tx=>tx.items?.forEach(item=>{const key=item.name||'Item';const current=itemMap.get(key)||{name:key,quantity:0,revenue:0};current.quantity+=Number(item.quantity||0);current.revenue+=Number(item.quantity||0)*Number(item.unitAmount||0);itemMap.set(key,current)}))
  const topItems=[...itemMap.values()].sort((a,b)=>b.revenue-a.revenue).slice(0,5)
  const paymentLinks=commerce.orders.filter(x=>x.source==='payment_link').length
  return <><section className="ca-panel"><header><h2>{es?'Analítica':'Analytics'}</h2><p>{es?'Vista consolidada de ventas, reservaciones y rendimiento comercial registrado por WebFactory.':'Consolidated view of sales, bookings and business performance recorded by WebFactory.'}</p></header><div className="ca-v3-metrics"><article><small>{es?'INGRESOS REGISTRADOS':'RECORDED REVENUE'}</small><strong>{money(revenue)}</strong></article><article><small>{es?'TRANSACCIONES PAGADAS':'PAID TRANSACTIONS'}</small><strong>{paid.length}</strong></article><article><small>{es?'TICKET PROMEDIO':'AVERAGE TICKET'}</small><strong>{money(average)}</strong></article><article><small>{es?'LINKS DE PAGO':'PAYMENT LINK SALES'}</small><strong>{paymentLinks}</strong></article></div></section><section className="ca-panel"><header><h2>{es?'Ingresos por canal':'Revenue by channel'}</h2><p>{es?'Separa ventas directas de ingresos por reservaciones.':'Separate direct sales from booking revenue.'}</p></header><div className="ca-v3-metrics"><article><small>{es?'ÓRDENES':'ORDERS'}</small><strong>{money(orderRevenue)}</strong></article><article><small>{es?'RESERVACIONES':'BOOKINGS'}</small><strong>{money(bookingRevenue)}</strong></article></div></section><section className="ca-panel"><header><h2>{es?'Más vendidos':'Top sellers'}</h2><p>{es?'Productos y servicios con mayor ingreso dentro del historial cargado.':'Products and services with the highest revenue in the loaded history.'}</p></header><div className="ca-v3-table">{topItems.length===0?<p>{es?'Todavía no hay datos suficientes.':'Not enough data yet.'}</p>:topItems.map(item=><article key={item.name}><div><strong>{item.name}</strong></div><div><b>{item.quantity}</b><span>{es?'Unidades':'Units'}</span></div><div><b>{money(item.revenue)}</b><span>{es?'Ingresos':'Revenue'}</span></div></article>)}</div></section></>
}

export function MarketingPanel({site,lang}:{site:any;lang:Language}){
  const es=lang==='es'
  return <section className="ca-panel"><header><h2>{es?'Marketing':'Marketing'}</h2><p>{es?'Centro de crecimiento y retención del negocio.':'Business growth and retention center.'}</p></header><div className="ca-v3-cards"><article><small>REVIEWS</small><strong>{es?'Solicitudes automáticas de reseñas':'Automated review requests'}</strong><p>{es?'La automatización se habilitará en V3.1 usando órdenes y citas completadas.':'Automation will be enabled in V3.1 using completed orders and bookings.'}</p></article><article><small>SOCIAL</small><strong>{es?'Comparte tu website':'Share your website'}</strong><p>/sites/{site.slug}</p></article><article><small>CUSTOMERS</small><strong>{es?'Retención basada en CRM':'CRM-based retention'}</strong><p>{es?'Los perfiles de clientes ya se están preparando automáticamente con cada pago confirmado.':'Customer profiles are already being prepared automatically with each confirmed payment.'}</p></article></div></section>
}

export function WebsitePanel({site,lang}:{site:any;lang:Language}){
  const es=lang==='es'
  return <section className="ca-panel"><header><h2>{es?'Website':'Website'}</h2><p>{es?'Administra la presencia pública de tu negocio y vuelve al Builder cuando necesites cambios de diseño.':'Manage your public business presence and return to the Builder for design changes.'}</p></header><div className="ca-v3-cards"><article><small>PUBLIC SITE</small><strong>/sites/{site.slug}</strong><a className="ca-primary-link" href={`/sites/${site.slug}`} target="_blank">{es?'Ver website':'View website'}</a></article><article><small>BUILDER</small><strong>{site.design?.mode==='template_base'?(site.design?.templateName||site.design?.templateSlug||'Template'):'Custom'}</strong><a className="ca-primary-link" href="/builder">{es?'Abrir Builder':'Open Builder'}</a></article><article><small>REVISION</small><strong>Rev. {site.revision}</strong><p>{es?'Los cambios administrativos se publican sin crear un nuevo deploy por cliente.':'Administrative changes publish without a separate client deployment.'}</p></article></div></section>
}

export function SettingsPanel({site,lang,onSave,busy}:{site:any;lang:Language;onSave:(section:string,value:any)=>void;busy:boolean}){
  const es=lang==='es';const [tax,setTax]=useState<TaxConfig>(()=>({enabled:site.taxConfig?.enabled!==false,stateRate:Number(site.taxConfig?.stateRate??10.5),municipalRate:Number(site.taxConfig?.municipalRate??1),pricesIncludeTax:Boolean(site.taxConfig?.pricesIncludeTax),defaultTaxable:site.taxConfig?.defaultTaxable!==false}))
  useEffect(()=>setTax({enabled:site.taxConfig?.enabled!==false,stateRate:Number(site.taxConfig?.stateRate??10.5),municipalRate:Number(site.taxConfig?.municipalRate??1),pricesIncludeTax:Boolean(site.taxConfig?.pricesIncludeTax),defaultTaxable:site.taxConfig?.defaultTaxable!==false}),[site.siteId,site.revision])
  const total=useMemo(()=>Number(tax.stateRate||0)+Number(tax.municipalRate||0),[tax])
  return <section className="ca-panel"><header><h2>{es?'Configuración':'Settings'}</h2><p>{es?'Impuestos y comportamiento general de comercio para este negocio.':'Taxes and general commerce behavior for this business.'}</p></header><h3>{es?'IVU de Puerto Rico':'Puerto Rico IVU'}</h3><div className="ca-grid"><label className="check"><input type="checkbox" checked={tax.enabled} onChange={e=>setTax({...tax,enabled:e.target.checked})}/>{es?'Calcular IVU':'Calculate IVU'}</label><label>{es?'IVU estatal %':'State rate %'}<input type="number" min="0" step="0.01" value={tax.stateRate} onChange={e=>setTax({...tax,stateRate:Number(e.target.value)})}/></label><label>{es?'IVU municipal %':'Municipal rate %'}<input type="number" min="0" step="0.01" value={tax.municipalRate} onChange={e=>setTax({...tax,municipalRate:Number(e.target.value)})}/></label><label>{es?'Total':'Total'}<input value={`${total.toFixed(2)}%`} disabled/></label><label className="check"><input type="checkbox" checked={tax.pricesIncludeTax} onChange={e=>setTax({...tax,pricesIncludeTax:e.target.checked})}/>{es?'Precios incluyen IVU':'Prices include tax'}</label><label className="check"><input type="checkbox" checked={tax.defaultTaxable} onChange={e=>setTax({...tax,defaultTaxable:e.target.checked})}/>{es?'Artículos son tributables por defecto':'Items taxable by default'}</label></div><button className="ca-save" disabled={busy} onClick={()=>onSave('taxConfig',tax)}>{busy?(es?'Guardando…':'Saving…'):(es?'Guardar configuración':'Save settings')}</button></section>
}


export function PayoutsPanel({siteId,lang}:{siteId:string;lang:Language}){
  const es=lang==='es';const [rows,setRows]=useState<Payout[]>([]);const [connected,setConnected]=useState<boolean|null>(null);const [error,setError]=useState('')
  useEffect(()=>{api(`/.netlify/functions/client-stripe-payouts?siteId=${encodeURIComponent(siteId)}`).then(r=>{setConnected(Boolean(r.connected));setRows(r.payouts||[])}).catch(e=>setError(e instanceof Error?e.message:'Error'))},[siteId])
  return <section className="ca-panel"><header><h2>{es?'Depósitos de Stripe':'Stripe payouts'}</h2><p>{es?'Consulta los depósitos enviados por Stripe a la cuenta bancaria conectada del negocio.':'View payouts Stripe sends to the connected business bank account.'}</p></header>{error&&<div className="ca-error">{error}</div>}{connected===false?<div className="ca-warning">{es?'Conecta Stripe para ver depósitos y fechas estimadas.':'Connect Stripe to view payouts and estimated arrival dates.'}</div>:rows.length===0?<p>{es?'No hay depósitos recientes para mostrar.':'No recent payouts to display.'}</p>:<div className="ca-transactions">{rows.map(row=><article key={row.id}><div><small>PAYOUT</small><strong>{row.id}</strong><span>{row.method||'standard'} · {row.type||'bank_account'}</span></div><div><b>{money(row.amount)}</b><span>{row.status}</span>{row.arrivalDate&&<time>{es?'Llega aprox. ':'Expected '} {new Date(row.arrivalDate).toLocaleDateString(es?'es-PR':'en-US')}</time>}</div></article>)}</div>}</section>
}

export function InventoryStatusPanel({site,lang}:{site:any;lang:Language}){
  const es=lang==='es'
  const tracked=(site.catalog||[]).filter((item:any)=>item.type==='product'&&item.trackInventory)
  const low=tracked.filter((item:any)=>Number(item.inventory??0)<=Number(item.lowStockThreshold??0))
  const out=tracked.filter((item:any)=>Number(item.inventory??0)<=0&&!item.allowBackorder)
  return <section className="ca-panel"><header><h2>{es?'Inventario':'Inventory'}</h2><p>{es?'Estado del inventario rastreado en todo WebFactory.':'Inventory status tracked across WebFactory.'}</p></header><div className="ca-v3-metrics"><article><small>{es?'RASTREADOS':'TRACKED'}</small><strong>{tracked.length}</strong></article><article><small>{es?'BAJO INVENTARIO':'LOW STOCK'}</small><strong>{low.length}</strong></article><article><small>{es?'AGOTADOS':'SOLD OUT'}</small><strong>{out.length}</strong></article></div>{low.length>0&&<div className="ca-v3-table">{low.map((item:any)=><article key={item.id}><div><strong>{item.nameEn||item.name||item.nameEs}</strong><span>SKU {item.sku||'—'}</span></div><div><b>{Number(item.inventory??0)}</b><span>{es?'Disponibles':'On hand'}</span></div><div><b>{Number(item.lowStockThreshold??0)}</b><span>{es?'Alerta desde':'Alert at'}</span></div><div><b>{item.allowBackorder?(es?'Sí':'Yes'):(es?'No':'No')}</b><span>Backorder</span></div></article>)}</div>}</section>
}


export function InventoryMovementsPanel({siteId,lang}:{siteId:string;lang:Language}){
  const es=lang==='es';const [rows,setRows]=useState<any[]>([])
  useEffect(()=>{api(`/.netlify/functions/client-v3-admin?siteId=${encodeURIComponent(siteId)}&collection=inventory-movements&limit=100`).then(r=>setRows(r.records||[])).catch(()=>setRows([]))},[siteId])
  return <section className="ca-panel"><header><h2>{es?'Movimientos de inventario':'Inventory movements'}</h2><p>{es?'Historial reciente de ventas, reembolsos y ajustes que cambiaron existencias.':'Recent sales, refunds and adjustments that changed stock.'}</p></header><div className="ca-transactions">{rows.length===0?<p>{es?'No hay movimientos todavía.':'No inventory movements yet.'}</p>:rows.map(row=><article key={row.movementId}><div><small>{String(row.reason||'adjustment').toUpperCase()}</small><strong>{row.itemId}</strong><span>{row.referenceId||row.movementId}</span></div><div><b>{Number(row.quantityDelta)>0?'+':''}{row.quantityDelta}</b><time>{new Date(row.createdAt).toLocaleString(es?'es-PR':'en-US')}</time></div></article>)}</div></section>
}

export function MemberRolesPanel({site,lang,onSave,busy,membership}:{site:any;lang:Language;onSave:(section:string,value:any)=>void;busy:boolean;membership:any}){
  const es=lang==='es';const [members,setMembers]=useState<any[]>(site.members||[])
  useEffect(()=>setMembers(site.members||[]),[site.siteId,site.revision])
  const ownerOnly=(membership?.role||'owner')==='owner'||membership?.role==='admin'
  const update=(index:number,role:string)=>setMembers(current=>current.map((member,i)=>i===index?{...member,role}:member))
  return <section className="ca-panel"><header><h2>{es?'Roles del portal':'Portal roles'}</h2><p>{es?'Controla qué puede administrar cada miembro existente del negocio.':'Control what each existing business member can manage.'}</p></header><div className="ca-v3-table">{members.map((member,index)=><article key={member.email}><div><strong>{member.email}</strong><span>{member.role}</span></div><div>{member.role==='owner'?<b>Owner</b>:<select disabled={!ownerOnly||busy} value={member.role||'staff'} onChange={e=>update(index,e.target.value)}><option value="manager">Manager</option><option value="employee">Employee</option><option value="cashier">Cashier</option><option value="staff">Legacy staff</option></select>}</div></article>)}</div>{ownerOnly&&<button className="ca-save" disabled={busy} onClick={()=>onSave('members',members)}>{busy?(es?'Guardando…':'Saving…'):(es?'Guardar roles':'Save roles')}</button>}</section>
}

export function ReviewAutomationPanel({site,lang,onSave,busy}:{site:any;lang:Language;onSave:(section:string,value:any)=>void;busy:boolean}){
  const es=lang==='es';const [value,setValue]=useState<any>(()=>({enabled:Boolean(site.reviewSettings?.enabled),delayHours:Number(site.reviewSettings?.delayHours??2),reviewUrl:site.reviewSettings?.reviewUrl||'',includeOrders:site.reviewSettings?.includeOrders!==false,includeBookings:site.reviewSettings?.includeBookings!==false}))
  useEffect(()=>setValue({enabled:Boolean(site.reviewSettings?.enabled),delayHours:Number(site.reviewSettings?.delayHours??2),reviewUrl:site.reviewSettings?.reviewUrl||'',includeOrders:site.reviewSettings?.includeOrders!==false,includeBookings:site.reviewSettings?.includeBookings!==false}),[site.siteId,site.revision])
  return <section className="ca-panel"><header><h2>{es?'Solicitudes de reseñas':'Review requests'}</h2><p>{es?'Configura cuándo WebFactory debe preparar una solicitud de reseña después de completar una venta o cita.':'Configure when WebFactory should prepare a review request after a completed sale or booking.'}</p></header><div className="ca-grid"><label className="check"><input type="checkbox" checked={value.enabled} onChange={e=>setValue({...value,enabled:e.target.checked})}/>{es?'Activar automatización':'Enable automation'}</label><label>{es?'Enviar después de (horas)':'Send after (hours)'}<input type="number" min="0" max="720" value={value.delayHours} onChange={e=>setValue({...value,delayHours:Number(e.target.value)})}/></label><label className="wide">{es?'Google review URL':'Google review URL'}<input value={value.reviewUrl} onChange={e=>setValue({...value,reviewUrl:e.target.value})} placeholder="https://..."/></label><label className="check"><input type="checkbox" checked={value.includeOrders} onChange={e=>setValue({...value,includeOrders:e.target.checked})}/>{es?'Incluir órdenes':'Include orders'}</label><label className="check"><input type="checkbox" checked={value.includeBookings} onChange={e=>setValue({...value,includeBookings:e.target.checked})}/>{es?'Incluir citas':'Include bookings'}</label></div><button className="ca-save" disabled={busy} onClick={()=>onSave('reviewSettings',value)}>{busy?(es?'Guardando…':'Saving…'):(es?'Guardar automatización':'Save automation')}</button></section>
}
