import { useEffect, useMemo, useState, type FormEvent } from 'react'
import { acceptInvite, getUser, handleAuthCallback, login, logout, onAuthChange, requestPasswordRecovery, updateUser, type User } from '@netlify/identity'
import './client-admin.css'
import { withAuthRetry } from './auth-retry'

type CatalogItem={id:string;type:'product'|'service';name:string;description:string;price:number;active:boolean;inventory:number|null;requiresAppointment:boolean;duration:number;bufferMinutes:number;imageAssetKey?:string}
type Employee={id:string;name:string;role:string;active:boolean;serviceIds:string[];calendarId:string;dailyLimit:number;schedule:Record<string,DayHours>;timeOff:Array<{start:string;end:string;note:string}>}
type DayHours={enabled:boolean;open:string;close:string}
type ClientSite={siteId:string;slug:string;status:string;revision:number;business:Record<string,string>;design:{style:string;primary:string;secondary:string};catalog:CatalogItem[];employees:Employee[];hours:Record<string,DayHours>;paymentRules:any;googleCalendar:any;settings:{locale:string;timezone:string;currency:string}}
type Transaction={transactionId:string;kind:'order'|'booking';customer:{name:string;email:string;phone:string};items:Array<{name:string;quantity:number;unitAmount:number}>;amountTotal:number;paymentStatus:string;status:string;createdAt:string;start?:string}
type Tab='overview'|'catalog'|'team'|'hours'|'payments'|'calendar'|'commerce'

const api=(url:string,options?:RequestInit)=>withAuthRetry(async()=>{const response=await fetch(url,{credentials:'include',cache:'no-store',...options});const result=await response.json();if(!response.ok||result.ok===false)throw new Error(result.message||'No se pudo completar la solicitud.');return result})
const money=(cents:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(cents/100)
const uid=(prefix:string)=>`${prefix}-${crypto.randomUUID()}`

function LoginPanel({onLogin}:{onLogin:(user:User)=>Promise<void>}){
  const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [sent,setSent]=useState(false)
  const submit=async(event:FormEvent)=>{event.preventDefault();setBusy(true);setError('');try{const current=await withAuthRetry(()=>login(email,password));await onLogin(current)}catch(e){setError(e instanceof Error?e.message:'No se pudo iniciar sesión.')}finally{setBusy(false)}}
  const recover=async()=>{if(!email)return setError('Escribe primero tu email.');setBusy(true);setError('');try{await requestPasswordRecovery(email);setSent(true)}catch(e){setError(e instanceof Error?e.message:'No se pudo enviar el enlace.')}finally{setBusy(false)}}
  return <section className="ca-login"><img src="/webfactory-pr-logo.png" alt="WebFactory PR"/><small>PORTAL PRIVADO</small><h1>Administra tu website.</h1><p>Actualiza catálogo, reservaciones, equipo, pagos y calendario desde un solo lugar.</p><form onSubmit={submit}><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>Contraseña<input type="password" value={password} onChange={e=>setPassword(e.target.value)} required/></label><button disabled={busy}>{busy?'Verificando…':'Entrar al portal'}</button></form><button className="ca-link" onClick={recover}>Olvidé mi contraseña</button>{sent&&<div className="ca-success">Revisa tu email para restablecer la contraseña.</div>}{error&&<div className="ca-error">{error}</div>}</section>
}

function ActivationPanel({orderId,token}:{orderId:string;token:string}){
  const [status,setStatus]=useState<'idle'|'busy'|'done'>('idle');const [error,setError]=useState('')
  const activate=async()=>{setStatus('busy');setError('');try{await api('/.netlify/functions/activate-client-portal',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({orderId,token})});setStatus('done')}catch(e){setError(e instanceof Error?e.message:'No se pudo activar el portal.');setStatus('idle')}}
  return <section className="ca-activate"><small>INVITACIÓN SEGURA</small><h2>Activa el portal de tu negocio</h2><p>Crearemos tu acceso privado y te enviaremos un enlace para establecer tu propia contraseña.</p><button onClick={activate} disabled={status==='busy'||status==='done'}>{status==='busy'?'Activando…':status==='done'?'Enlace enviado':'Activar acceso'}</button>{status==='done'&&<div className="ca-success">Revisa el email usado en tu orden. Luego regresa aquí para iniciar sesión.</div>}{error&&<div className="ca-error">{error}</div>}</section>
}

export default function ClientAdminPage(){
  const query=new URLSearchParams(location.search);const orderId=query.get('orderId')||'';const token=query.get('token')||''
  const [user,setUser]=useState<User|null>(null);const [loading,setLoading]=useState(true);const [resetToken,setResetToken]=useState('');const [inviteToken,setInviteToken]=useState('');const [newPassword,setNewPassword]=useState('');const [authMessage,setAuthMessage]=useState('')
  const [sites,setSites]=useState<Array<{siteId:string;slug:string;businessName:string;status:string}>>([]);const [site,setSite]=useState<ClientSite|null>(null);const [tab,setTab]=useState<Tab>('overview');const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');const [error,setError]=useState('');const [commerce,setCommerce]=useState<{orders:Transaction[];bookings:Transaction[]}>({orders:[],bookings:[]});const [calendars,setCalendars]=useState<Array<{id:string;summary:string;primary:boolean}>>([]);const [googleConfigured,setGoogleConfigured]=useState(false)

  const loadSites=async()=>{const result=await api('/.netlify/functions/client-admin');setSites(result.sites);if(result.sites.length){const selected=result.sites[0];const detail=await api(`/.netlify/functions/client-admin?siteId=${encodeURIComponent(selected.siteId)}`);setSite(detail.site)}}
  useEffect(()=>{document.title='Portal administrativo | WebFactory PR';let unsub=()=>{};(async()=>{try{const callback=await handleAuthCallback();if(callback?.type==='recovery')setResetToken('recovery');if(callback?.type==='invite'&&callback.token)setInviteToken(callback.token);const current=callback?.user||await getUser();setUser(current);if(current)await loadSites()}catch(e){setError(e instanceof Error?e.message:'No se pudo abrir el portal.')}finally{setLoading(false)}})();unsub=onAuthChange((_event,current)=>setUser(current));return()=>unsub()},[])
  const save=async(section:string,value:unknown)=>{if(!site)return;setBusy(true);setError('');setMessage('');try{const result=await api('/.netlify/functions/client-admin',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({siteId:site.siteId,section,value})});setSite(result.site);setMessage('Cambios publicados en tiempo real.')}catch(e){setError(e instanceof Error?e.message:'No se pudo guardar.')}finally{setBusy(false)}}
  const loadCommerce=async()=>{if(!site)return;const result=await api(`/.netlify/functions/client-commerce-admin?siteId=${encodeURIComponent(site.siteId)}`);setCommerce({orders:result.orders,bookings:result.bookings})}
  const loadCalendar=async()=>{if(!site)return;const result=await api(`/.netlify/functions/google-calendar-status?siteId=${encodeURIComponent(site.siteId)}`);setCalendars(result.calendars||[]);setGoogleConfigured(result.configured);if(result.message)setError(result.message)}
  useEffect(()=>{if(tab==='commerce')loadCommerce().catch(e=>setError(e.message));if(tab==='calendar')loadCalendar().catch(e=>setError(e.message))},[tab,site?.siteId])
  const resetPassword=async()=>{if(newPassword.length<8)return setError('Usa una contraseña de al menos 8 caracteres.');setBusy(true);try{let current:User|null;if(inviteToken){const invited=await acceptInvite(inviteToken,newPassword);if(!invited.email)throw new Error('La invitación no contiene un email válido.');current=await withAuthRetry(()=>login(invited.email!,newPassword))}else{current=await updateUser({password:newPassword})}setResetToken('');setInviteToken('');setAuthMessage('Contraseña guardada.');setUser(current);if(current)await loadSites()}catch(e){setError(e instanceof Error?e.message:'No se pudo guardar la contraseña.')}finally{setBusy(false)}}
  const signOut=async()=>{await logout();setUser(null);setSite(null)}
  const transactionAction=async(record:Transaction,action:string)=>{if(!site)return;if(!confirm(`¿Confirmas ${action} para ${record.transactionId}?`))return;setBusy(true);try{await api('/.netlify/functions/client-commerce-admin',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({siteId:site.siteId,kind:record.kind,transactionId:record.transactionId,action})});await loadCommerce();setMessage('Transacción actualizada.')}catch(e){setError(e instanceof Error?e.message:'No se pudo actualizar.')}finally{setBusy(false)}}

  if(loading)return <main className="ca-page"><div className="ca-loading">Abriendo portal seguro…</div></main>
  if(resetToken||inviteToken)return <main className="ca-page"><section className="ca-login"><img src="/webfactory-pr-logo.png" alt="WebFactory PR"/><h1>Establece tu contraseña</h1><label>Nueva contraseña<input type="password" value={newPassword} onChange={e=>setNewPassword(e.target.value)}/></label><button onClick={resetPassword} disabled={busy}>Guardar contraseña</button>{error&&<div className="ca-error">{error}</div>}</section></main>
  if(!user)return <main className="ca-page">{orderId&&token&&<ActivationPanel orderId={orderId} token={token}/>}<LoginPanel onLogin={async current=>{setUser(current);await loadSites()}}/></main>
  if(!site)return <main className="ca-page"><header className="ca-top"><img src="/webfactory-pr-logo.png"/><button onClick={signOut}>Salir</button></header><section className="ca-empty"><h1>No hay negocios asignados.</h1><p>Abre el enlace privado recibido después de tu compra para activar el portal.</p></section></main>

  const publicUrl=`/sites/${site.slug}`
  return <main className="ca-dashboard" style={{'--ca-primary':site.design?.primary||'#0B1529','--ca-accent':site.design?.secondary||'#3C86F6'} as React.CSSProperties}>
    <aside className="ca-sidebar"><img src="/webfactory-pr-logo.png" alt="WebFactory PR"/><div><small>NEGOCIO</small><strong>{site.business.name}</strong><span>{user.email}</span></div><nav>{([['overview','Resumen'],['catalog','Catálogo'],['team','Equipo'],['hours','Horarios'],['payments','Pagos'],['calendar','Google Calendar'],['commerce','Órdenes y citas']] as Array<[Tab,string]>).map(([id,label])=><button key={id} className={tab===id?'active':''} onClick={()=>{setTab(id);setMessage('');setError('')}}>{label}</button>)}</nav><a href={publicUrl} target="_blank">Ver website ↗</a><button className="ca-signout" onClick={signOut}>Cerrar sesión</button></aside>
    <section className="ca-work"><header><div><small>PORTAL ADMINISTRATIVO</small><h1>{site.business.name}</h1></div><div><span className={`ca-status ${site.status}`}>{site.status.replace('_',' ')}</span><b>Rev. {site.revision}</b></div></header>{message&&<div className="ca-success">{message}</div>}{error&&<div className="ca-error">{error}</div>}
      {tab==='overview'&&<Overview site={site} onSave={value=>save('business',value)} busy={busy}/>} 
      {tab==='catalog'&&<CatalogEditor site={site} setSite={setSite} onSave={()=>save('catalog',site.catalog)} busy={busy}/>} 
      {tab==='team'&&<TeamEditor site={site} setSite={setSite} onSave={()=>save('employees',site.employees)} busy={busy}/>} 
      {tab==='hours'&&<HoursEditor site={site} setSite={setSite} onSave={()=>save('hours',site.hours)} busy={busy}/>} 
      {tab==='payments'&&<Payments site={site} setSite={setSite} onSave={()=>save('paymentRules',site.paymentRules)} busy={busy} setError={setError}/>} 
      {tab==='calendar'&&<CalendarPanel site={site} setSite={setSite} calendars={calendars} configured={googleConfigured} onSave={()=>save('employees',site.employees)} busy={busy}/>} 
      {tab==='commerce'&&<Commerce records={commerce} onAction={transactionAction} busy={busy}/>} 
    </section>
  </main>
}

function Overview({site,onSave,busy}:{site:ClientSite;onSave:(v:any)=>void;busy:boolean}){const [value,setValue]=useState(site.business);useEffect(()=>setValue(site.business),[site.revision]);return <Panel title="Información del negocio" text="Estos cambios aparecen en el website después de guardar."><div className="ca-grid">{[['name','Nombre'],['category','Categoría'],['email','Email'],['phone','Teléfono'],['whatsapp','WhatsApp'],['instagram','Instagram'],['mapsUrl','Google Maps URL']].map(([key,label])=><label key={key}>{label}<input value={value[key]||''} onChange={e=>setValue({...value,[key]:e.target.value})}/></label>)}<label className="wide">Descripción<textarea rows={5} value={value.description||''} onChange={e=>setValue({...value,description:e.target.value})}/></label></div><Save busy={busy} onClick={()=>onSave(value)}/></Panel>}

function CatalogEditor({site,setSite,onSave,busy}:{site:ClientSite;setSite:(s:ClientSite)=>void;onSave:()=>void;busy:boolean}){const update=(i:number,patch:Partial<CatalogItem>)=>setSite({...site,catalog:site.catalog.map((x,n)=>n===i?{...x,...patch}:x)});const add=()=>site.catalog.length<100&&setSite({...site,catalog:[...site.catalog,{id:uid('item'),type:'product',name:'Nuevo artículo',description:'',price:0,active:true,inventory:null,requiresAppointment:false,duration:30,bufferMinutes:0}]});return <Panel title="Productos y servicios" text={`${site.catalog.length} de 100 artículos. El precio guardado aquí es el único que usa el servidor al cobrar.`}><div className="ca-actions"><button onClick={add}>+ Añadir</button><Save busy={busy} onClick={onSave}/></div><div className="ca-list">{site.catalog.map((item,i)=><article key={item.id}><header><input value={item.name} onChange={e=>update(i,{name:e.target.value})}/><button onClick={()=>setSite({...site,catalog:site.catalog.filter((_,n)=>n!==i)})}>Eliminar</button></header><div className="ca-grid compact"><label>Tipo<select value={item.type} onChange={e=>update(i,{type:e.target.value as any,requiresAppointment:e.target.value==='service'&&item.requiresAppointment})}><option value="product">Producto</option><option value="service">Servicio</option></select></label><label>Precio USD<input type="number" min="0" step="0.01" value={item.price} onChange={e=>update(i,{price:Number(e.target.value)})}/></label>{item.type==='product'&&<label>Inventario<input type="number" min="0" value={item.inventory??''} placeholder="Sin límite" onChange={e=>update(i,{inventory:e.target.value===''?null:Number(e.target.value)})}/></label>}{item.type==='service'&&<><label>Duración (min)<input type="number" value={item.duration} onChange={e=>update(i,{duration:Number(e.target.value)})}/></label><label>Buffer (min)<input type="number" value={item.bufferMinutes} onChange={e=>update(i,{bufferMinutes:Number(e.target.value)})}/></label><label className="check"><input type="checkbox" checked={item.requiresAppointment} onChange={e=>update(i,{requiresAppointment:e.target.checked})}/> Requiere cita</label></>}<label className="check"><input type="checkbox" checked={item.active} onChange={e=>update(i,{active:e.target.checked})}/> Visible</label><label className="wide">Descripción<textarea value={item.description} onChange={e=>update(i,{description:e.target.value})}/></label></div></article>)}</div></Panel>}

function TeamEditor({site,setSite,onSave,busy}:{site:ClientSite;setSite:(s:ClientSite)=>void;onSave:()=>void;busy:boolean}){const update=(i:number,p:Partial<Employee>)=>setSite({...site,employees:site.employees.map((x,n)=>n===i?{...x,...p}:x)});return <Panel title="Equipo" text="Asigna cada servicio al empleado correcto."><div className="ca-actions"><button onClick={()=>setSite({...site,employees:[...site.employees,{id:uid('employee'),name:'Nuevo empleado',role:'Profesional',active:true,serviceIds:[],calendarId:'',dailyLimit:8,schedule:{},timeOff:[]}]})}>+ Añadir</button><Save busy={busy} onClick={onSave}/></div><div className="ca-list">{site.employees.map((employee,i)=><article key={employee.id}><header><input value={employee.name} onChange={e=>update(i,{name:e.target.value})}/><button onClick={()=>setSite({...site,employees:site.employees.filter((_,n)=>n!==i)})}>Eliminar</button></header><div className="ca-grid compact"><label>Rol<input value={employee.role} onChange={e=>update(i,{role:e.target.value})}/></label><label>Límite diario<input type="number" min="1" value={employee.dailyLimit} onChange={e=>update(i,{dailyLimit:Number(e.target.value)})}/></label><label className="check"><input type="checkbox" checked={employee.active} onChange={e=>update(i,{active:e.target.checked})}/> Activo</label><fieldset className="wide"><legend>Servicios</legend>{site.catalog.filter(x=>x.type==='service').map(service=><label className="check" key={service.id}><input type="checkbox" checked={employee.serviceIds.includes(service.id)} onChange={e=>update(i,{serviceIds:e.target.checked?[...employee.serviceIds,service.id]:employee.serviceIds.filter(id=>id!==service.id)})}/>{service.name}</label>)}</fieldset></div></article>)}</div></Panel>}

function HoursEditor({site,setSite,onSave,busy}:{site:ClientSite;setSite:(s:ClientSite)=>void;onSave:()=>void;busy:boolean}){return <Panel title="Horario general" text="La disponibilidad real también considera empleado, citas, holds y Google Calendar."><div className="ca-hours">{Object.entries(site.hours).map(([day,hours])=><article key={day}><b>{day}</b><label className="check"><input type="checkbox" checked={hours.enabled} onChange={e=>setSite({...site,hours:{...site.hours,[day]:{...hours,enabled:e.target.checked}}})}/>Abierto</label><input type="time" value={hours.open} onChange={e=>setSite({...site,hours:{...site.hours,[day]:{...hours,open:e.target.value}}})}/><input type="time" value={hours.close} onChange={e=>setSite({...site,hours:{...site.hours,[day]:{...hours,close:e.target.value}}})}/></article>)}</div><Save busy={busy} onClick={onSave}/></Panel>}

function Payments({site,setSite,onSave,busy,setError}:{site:ClientSite;setSite:(s:ClientSite)=>void;onSave:()=>void;busy:boolean;setError:(s:string)=>void}){const p=site.paymentRules||{};const openStripe=async()=>{try{const result=await api('/.netlify/functions/client-stripe-account-link',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({siteId:site.siteId})});location.assign(result.url)}catch(e){setError(e instanceof Error?e.message:'No se pudo abrir Stripe.')}};return <Panel title="Pagos" text="Los fondos de ventas van directamente a la cuenta Stripe del negocio."><div className="ca-payment-status"><span className={p.stripeCapabilityStatus==='active'?'ready':''}/><div><small>STRIPE CONNECT</small><strong>{p.stripeCapabilityStatus==='active'?'Pagos activos':'Configuración pendiente'}</strong></div><button onClick={openStripe}>{p.stripeCapabilityStatus==='active'?'Administrar en Stripe':'Continuar verificación'}</button></div><div className="ca-grid"><label>Pago de productos<select value={p.productPayment||'online'} onChange={e=>setSite({...site,paymentRules:{...p,productPayment:e.target.value}})}><option value="online">Online</option><option value="in_person">Presencial</option></select></label><label>Pago de citas<select value={p.bookingPayment||'full'} onChange={e=>setSite({...site,paymentRules:{...p,bookingPayment:e.target.value}})}><option value="full">Completo</option><option value="deposit">Depósito</option><option value="in_person">Presencial</option></select></label>{p.bookingPayment==='deposit'&&<label>Depósito %<select value={p.bookingDepositPercent||25} onChange={e=>setSite({...site,paymentRules:{...p,bookingDepositPercent:Number(e.target.value)}})}>{[10,20,25,30,50].map(x=><option key={x}>{x}</option>)}</select></label>}</div><Save busy={busy} onClick={onSave}/><p className="ca-note">Identidad, banco, impuestos, disputas sensibles y seguridad se completan en pantallas oficiales de Stripe cuando sea requerido.</p></Panel>}

function CalendarPanel({site,setSite,calendars,configured,onSave,busy}:{site:ClientSite;setSite:(s:ClientSite)=>void;calendars:Array<{id:string;summary:string;primary:boolean}>;configured:boolean;onSave:()=>void;busy:boolean}){return <Panel title="Google Calendar" text="Los conflictos y eventos se sincronizan por empleado.">{!configured?<div className="ca-warning">La aplicación Google OAuth todavía necesita sus credenciales privadas de producción.</div>:!site.googleCalendar?.connected?<a className="ca-primary-link" href={`/.netlify/functions/google-calendar-start?siteId=${encodeURIComponent(site.siteId)}`}>Conectar Google Calendar</a>:<><div className="ca-success">Google Calendar conectado.</div><div className="ca-list">{site.employees.map((employee,i)=><article key={employee.id}><strong>{employee.name}</strong><label>Calendario<select value={employee.calendarId||''} onChange={e=>setSite({...site,employees:site.employees.map((x,n)=>n===i?{...x,calendarId:e.target.value}:x)})}><option value="">Sin asignar</option>{calendars.map(calendar=><option value={calendar.id} key={calendar.id}>{calendar.summary}{calendar.primary?' (principal)':''}</option>)}</select></label></article>)}</div><Save busy={busy} onClick={onSave}/></>}</Panel>}

function Commerce({records,onAction,busy}:{records:{orders:Transaction[];bookings:Transaction[]};onAction:(r:Transaction,a:string)=>void;busy:boolean}){const all=[...records.bookings,...records.orders].sort((a,b)=>Date.parse(b.createdAt)-Date.parse(a.createdAt));return <Panel title="Órdenes y citas" text="Los pagos se muestran solamente después de confirmación del webhook de Stripe."><div className="ca-transactions">{all.length===0?<p>No hay transacciones todavía.</p>:all.map(record=><article key={record.transactionId}><div><small>{record.kind==='booking'?'CITA':'ORDEN'}</small><strong>{record.customer.name}</strong><span>{record.transactionId}</span></div><div><b>{money(record.amountTotal)}</b><span>{record.paymentStatus} · {record.status}</span>{record.start&&<time>{new Date(record.start).toLocaleString()}</time>}</div><nav>{record.paymentStatus==='due'&&<button disabled={busy} onClick={()=>onAction(record,'mark_paid')}>Marcar pagado</button>}{record.paymentStatus==='paid'&&!record.status.includes('refund')&&<button disabled={busy} onClick={()=>onAction(record,'refund')}>Reembolsar</button>}{record.kind==='booking'&&record.status!=='cancelled'&&<button disabled={busy} onClick={()=>onAction(record,'cancel')}>Cancelar</button>}</nav></article>)}</div></Panel>}

function Panel({title,text,children}:{title:string;text:string;children:React.ReactNode}){return <section className="ca-panel"><header><h2>{title}</h2><p>{text}</p></header>{children}</section>}
function Save({busy,onClick}:{busy:boolean;onClick:()=>void}){return <button className="ca-save" disabled={busy} onClick={onClick}>{busy?'Guardando…':'Guardar y publicar'}</button>}
