import {useRef,useState,type FormEvent} from 'react'
import {PortalPanel} from './PortalPanel'
type Client={siteId:string;businessName:string;ownerEmail:string}
export default function ClientAuthenticatorReset({lang,sites}:{lang:'es'|'en';sites:Client[]}){
 const es=lang==='es',[siteId,setSiteId]=useState(''),[email,setEmail]=useState(''),[reference,setReference]=useState(''),[reason,setReason]=useState(''),[requested,setRequested]=useState(false),[verified,setVerified]=useState(false),[confirmation,setConfirmation]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState(''),[audit,setAudit]=useState<Array<{auditId:string;siteId:string;requestReference:string;createdAt:string;status:string;notification:string}>>([]);const requestId=useRef(crypto.randomUUID())
 const loadAudit=async()=>{setError('');try{const response=await fetch('/.netlify/functions/admin-security-audit',{credentials:'same-origin',cache:'no-store'});if(!response.ok)throw Error(es?'No se pudo leer el registro.':'Unable to read audit.');setAudit((await response.json()).rows)}catch(e){setError(e instanceof Error?e.message:String(e))}}
 const submit=async(event:FormEvent)=>{event.preventDefault();setBusy(true);setError('');setMessage('');try{
  const response=await fetch('/.netlify/functions/admin-reset-authenticator',{method:'POST',credentials:'same-origin',cache:'no-store',headers:{'Content-Type':'application/json'},body:JSON.stringify({siteId,email,requestReference:reference,reason,requestedByClient:requested,identityVerified:verified,verificationMethod:'registered-contact-and-business-verification',confirmation,requestId:requestId.current})});const result=await response.json();
  if(!response.ok)throw Error(response.status===403?(es?'Verifica nuevamente tu propio MFA y vuelve a intentar.':'Verify your own MFA again and retry.'):result.message||'Reset failed.');
  setMessage((es?'Restablecimiento registrado. Referencia: ':'Reset recorded. Reference: ')+result.auditId+(result.notification==='accepted'?(es?' · Correo aceptado por el proveedor.':' · Email accepted by provider.'):(es?' · Notificación incierta: revisa al proveedor antes de reenviar.':' · Notification uncertain: check the provider before resending.')));setRequested(false);setVerified(false);setConfirmation('');requestId.current=crypto.randomUUID();
 }catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy(false)}}
 return <PortalPanel className="wfa-card"><header><div><small>{es?'RECUPERACIÓN DE CLIENTES':'CLIENT ACCOUNT RECOVERY'}</small><h2>{es?'Restablecer Authenticator':'Reset Authenticator'}</h2></div></header>
 <p>{es?'Usa esta acción únicamente por solicitud del titular. Antes, verifica un contacto registrado por un canal independiente y la autoridad del solicitante sobre el negocio. Un email o conocer el nombre del negocio no basta.':'Use only at the account holder’s request. First verify a registered contact through an independent channel and the requester’s authority over the business. An email or knowing the business name is insufficient.'}</p>
 <p className="wfa-note">{es?'Debes verificar tu propio MFA durante los cinco minutos anteriores. Se invalida el Authenticator, los códigos de recuperación y las sesiones previas de WebFactory del cliente. Sus passkeys se conservan. Si no quedan factores, debe iniciar sesión con contraseña y configurar uno nuevo. No afecta Stripe, Google ni su aplicación Authenticator.':'You must verify your own MFA within the previous five minutes. This invalidates the client’s Authenticator, recovery codes and previous WebFactory sessions. Passkeys remain. If no factors remain, the client must sign in with a password and enroll again. Stripe, Google and their Authenticator app are unaffected.'}</p>
 <form onSubmit={event=>void submit(event)} className="wfa-invite">
 <label>{es?'Negocio':'Business'}<select aria-label={es?'Negocio':'Business'} required value={siteId} disabled={busy} onChange={event=>{setSiteId(event.target.value);setEmail(sites.find(site=>site.siteId===event.target.value)?.ownerEmail||'');requestId.current=crypto.randomUUID()}}><option value="">{es?'Selecciona un negocio':'Select a business'}</option>{sites.map(site=><option key={site.siteId} value={site.siteId}>{site.businessName}</option>)}</select></label>
 <label>{es?'Email del miembro registrado':'Registered member email'}<input type="email" required maxLength={320} value={email} disabled={busy} onChange={event=>{setEmail(event.target.value);requestId.current=crypto.randomUUID()}}/></label>
 <label>{es?'Referencia de la solicitud':'Support request reference'}<input required minLength={8} maxLength={300} value={reference} disabled={busy} onChange={event=>setReference(event.target.value)}/></label>
 <label>{es?'Motivo (sin documentos ni datos sensibles)':'Reason (no documents or sensitive data)'}<input required minLength={8} maxLength={300} value={reason} disabled={busy} onChange={event=>setReason(event.target.value)}/></label>
 <label><input type="checkbox" required checked={requested} disabled={busy} onChange={event=>setRequested(event.target.checked)}/>{es?'El titular solicitó expresamente la recuperación.':'The account holder explicitly requested recovery.'}</label>
 <label><input type="checkbox" required checked={verified} disabled={busy} onChange={event=>setVerified(event.target.checked)}/>{es?'Verifiqué contacto registrado por canal independiente y autoridad sobre el negocio; conservé constancia en el caso.':'I verified the registered contact through an independent channel and authority over the business, and recorded evidence in the support case.'}</label>
 <label>{es?'Escribe RESET AUTHENTICATOR':'Type RESET AUTHENTICATOR'}<input required value={confirmation} disabled={busy} onChange={event=>setConfirmation(event.target.value)}/></label>
 <button className="danger" disabled={busy||!requested||!verified||confirmation!=='RESET AUTHENTICATOR'}>{busy?(es?'Procesando…':'Processing…'):(es?'Restablecer Authenticator del cliente':'Reset client Authenticator')}</button>
 </form>{error&&<p role="alert">{error}</p>}{message&&<p role="status">{message}</p>}
 <p className="wfa-note">{es?'Si la respuesta es incierta, revisa el registro de seguridad antes de crear otra solicitud. No uses esta acción para tu cuenta administrativa.':'If the response is uncertain, review the security audit before creating another request. This action cannot reset your administrative account.'}</p>
 <button type="button" disabled={busy} onClick={()=>void loadAudit()}>{es?'Ver registro de recuperación':'View recovery audit'}</button>{audit.length>0&&<ul>{audit.map(row=><li key={row.auditId}>{new Date(row.createdAt).toLocaleString(es?'es-PR':'en-US')} · {row.requestReference} · {row.auditId} · {row.status} · {row.notification}</li>)}</ul>}
 </PortalPanel>
}
