import { useState } from 'react'
import { AdaptiveLogo, ThemeToggle } from './theme'
import { FeedbackPreferences } from './feedback/FeedbackPreferences'
import './home-premium.css'

type Language = 'en' | 'es'
const copy = {
  es: {
    nav: ['Plataforma', 'Explorar', 'Cómo funciona', 'Planes'], login: 'Entrar', start: 'Crear mi website',
    eyebrow: 'CREADO EN PUERTO RICO · PARA TU NEGOCIO', title: 'Tu negocio,', accent: 'en control.',
    lead: 'Un website para vender y recibir citas. Un centro de control para administrar todo lo que viene después.', templates: 'Ver templates', trial: '7 días gratis · Sin tarjeta · Luego $30/mes',
    portal: 'Centro de control', overview: 'Tu negocio de un vistazo', example: 'Vista ilustrativa · Datos de ejemplo', sales: 'Ventas', bookings: 'Reservas', customers: 'Clientes', team: 'Equipo', reports: 'Reportes', payments: 'Pagos', today: 'Actividad reciente', paid: 'Pagado', confirmed: 'Confirmada',
    explore: 'EXPLORA WEBFACTORY', exploreTitle: 'Mira cómo se conecta todo.', exploreText: 'Prueba un carrito, prepara una cita y explora la idea de tu centro de control.', tabs: ['Vender', 'Reservar', 'Administrar'],
    sellTitle: 'De tu catálogo al carrito.', sellText: 'Productos y servicios en tu website, con pagos conectados a tu negocio.', item: 'Kit de cuidado', add: 'Añadir al carrito', cart: 'Tu carrito', empty: 'Añade un producto para comenzar.', clear: 'Vaciar carrito', total: 'Total de ejemplo', demoNote: 'Demo local. No procesa pagos ni crea pedidos o reservas.',
    bookTitle: 'Una cita, menos pasos.', bookText: 'Servicio, profesional y horario en una experiencia clara para tus clientes.', service: 'Servicio', professional: 'Profesional', schedule: 'Horario de ejemplo', book: 'Previsualizar reserva', bookingReady: 'Reserva de ejemplo preparada', serviceName: 'Consulta personalizada',
    manageTitle: 'El siguiente paso, a la vista.', manageText: 'Ventas, reservas, pagos, clientes y equipo reunidos en tu Business Control Center.', quick: 'Accesos rápidos',
    toolsLabel: 'UNA PLATAFORMA, MUCHAS POSIBILIDADES', toolsTitle: 'Lo que necesitas. Bien conectado.', tools: [['Website + Factory AI', 'Comienza con un template o prepara tu contenido bilingüe en el Builder.'], ['Ventas + pagos', 'Catálogo, inventario, POS y enlaces de pago. Conecta Stripe y ATH Móvil.'], ['Reservas + equipo', 'Servicios, horarios, profesionales y calendario en un solo flujo.'], ['Clientes + reportes', 'Consulta actividad, transacciones y métricas desde tu portal.']],
    stepsLabel: 'DE LA IDEA A TU OPERACIÓN', stepsTitle: 'Empieza con tu negocio.', steps: [['Crea', 'Elige tu base y aplica tu logo, colores y contenido.'], ['Configura', 'Añade productos, servicios, equipo y tus métodos de pago.'], ['Administra', 'Gestiona ventas y reservas desde tu portal.']],
    priceLabel: 'UN PLAN CLARO', priceTitle: 'Tu plataforma. Tu marca.', month: '/mes', annual: 'O $350 al año', priceText: 'Website, ventas, reservas y portal administrativo.', noCommission: 'Sin comisión de WebFactory sobre tus ventas.',
    faq: [['¿Puedo vender y recibir citas?', 'Sí. Puedes ofrecer productos y servicios con reservaciones en el mismo website.'], ['¿A dónde llegan los pagos?', 'Stripe y ATH Móvil se conectan a las cuentas de tu negocio. Aplican las tarifas del proveedor de pago.'], ['¿Puedo cambiar el contenido después?', 'Sí. Administra catálogo, precios, empleados y horarios desde tu portal.']], footer: 'Tu website. Tu operación. Tu control.', legal: ['Privacidad', 'Términos', 'Reembolsos']
  },
  en: {
    nav: ['Platform', 'Explore', 'How it works', 'Plans'], login: 'Log In', start: 'Build my website',
    eyebrow: 'BUILT IN PUERTO RICO · FOR YOUR BUSINESS', title: 'Your business,', accent: 'in control.',
    lead: 'A website to sell and accept bookings. A control center to manage everything that comes next.', templates: 'Browse templates', trial: '7 days free · No card · Then $30/month',
    portal: 'Control center', overview: 'Your business at a glance', example: 'Illustrative view · Sample data', sales: 'Sales', bookings: 'Bookings', customers: 'Customers', team: 'Team', reports: 'Reports', payments: 'Payments', today: 'Recent activity', paid: 'Paid', confirmed: 'Confirmed',
    explore: 'EXPLORE WEBFACTORY', exploreTitle: 'See how it all connects.', exploreText: 'Try a cart, prepare an appointment and explore your control center concept.', tabs: ['Sell', 'Book', 'Manage'],
    sellTitle: 'From your catalog to the cart.', sellText: 'Products and services on your website, with payments connected to your business.', item: 'Care kit', add: 'Add to cart', cart: 'Your cart', empty: 'Add a product to get started.', clear: 'Clear cart', total: 'Sample total', demoNote: 'Local demo. No payments, orders or bookings are created.',
    bookTitle: 'An appointment, fewer steps.', bookText: 'Service, professional and time in a clear experience for your customers.', service: 'Service', professional: 'Professional', schedule: 'Sample time', book: 'Preview booking', bookingReady: 'Sample booking prepared', serviceName: 'Personal consultation',
    manageTitle: 'Your next step, in view.', manageText: 'Sales, bookings, payments, customers and team together in your Business Control Center.', quick: 'Quick access',
    toolsLabel: 'ONE PLATFORM, MANY POSSIBILITIES', toolsTitle: 'What you need. Connected.', tools: [['Website + Factory AI', 'Start with a template or prepare bilingual content in the Builder.'], ['Sales + payments', 'Catalog, inventory, POS and payment links. Connect Stripe and ATH Móvil.'], ['Bookings + team', 'Services, schedules, professionals and calendars in one flow.'], ['Customers + reports', 'Review activity, transactions and metrics from your portal.']],
    stepsLabel: 'FROM YOUR IDEA TO YOUR OPERATION', stepsTitle: 'Start with your business.', steps: [['Create', 'Choose your starting point and add your logo, colors and content.'], ['Configure', 'Add products, services, team and your payment methods.'], ['Manage', 'Handle sales and bookings from your portal.']],
    priceLabel: 'ONE CLEAR PLAN', priceTitle: 'Your platform. Your brand.', month: '/month', annual: 'Or $350 per year', priceText: 'Website, sales, bookings and an admin portal.', noCommission: 'No WebFactory commission on your sales.',
    faq: [['Can I sell and accept bookings?', 'Yes. Offer products and services with appointments on the same website.'], ['Where do payments go?', 'Stripe and ATH Móvil connect to your business accounts. Payment provider fees apply.'], ['Can I edit my content later?', 'Yes. Manage your catalog, prices, employees and hours from your portal.']], footer: 'Your website. Your operation. Your control.', legal: ['Privacy', 'Terms', 'Refunds']
  }
}

function Symbol({name}:{name:string}) {
  const paths:Record<string,string>={sales:'M4 7h16l-2 10H6L4 7Zm0 0L3 3H1M8 21h.01M17 21h.01',bookings:'M5 5h14v15H5V5Zm3-3v6m8-6v6M5 10h14',payments:'M3 6h18v12H3V6Zm0 5h18M7 15h3',customers:'M15 21v-3a5 5 0 0 0-10 0v3M10 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8Zm10 9v-3a5 5 0 0 0-3-4',team:'M4 19h16M7 15V9m5 6V4m5 11v-5',reports:'M4 20V4m0 16h16M8 15l4-5 4 2 4-7'}
  return <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d={paths[name]||paths.reports}/></svg>
}

function ControlPreview({lang,compact=false}:{lang:Language,compact?:boolean}) {
  const t=copy[lang]
  return <div className={`wf-p-control ${compact?'compact':''}`}>
    <div className="wf-p-control-top"><span className="wf-p-dot"/><b>Business Control Center</b><span className="wf-p-example">{t.example}</span></div>
    <div className="wf-p-control-body"><aside aria-hidden="true"><div className="wf-p-monogram">W<span>F</span></div>{['reports','sales','bookings','payments','customers','team'].map((x,i)=><div key={x} className={i===0?'selected':''}><Symbol name={x}/></div>)}</aside>
      <div className="wf-p-dashboard"><div className="wf-p-dash-heading"><div><small>WEBFACTORY PR</small><h3>{t.overview}</h3></div><span className="wf-p-avatar">WF</span></div>
        <div className="wf-p-metrics">{[[t.sales,'$645'],[t.bookings,'03'],[t.customers,'12']].map(([label,value])=><div key={label}><span>{label}</span><strong>{value}</strong></div>)}</div>
        <div className="wf-p-chart-card"><div><b>{t.sales}</b><small>{lang==='es'?'7 días de ejemplo':'7 sample days'}</small></div><div className="wf-p-chart" aria-label={lang==='es'?'Gráfica ilustrativa de ventas':'Illustrative sales chart'}>{[28,47,75,50,38,100,66].map((h,i)=><div key={i}><span style={{height:`${h}%`}}/><small>{['M','T','W','T','F','S','S'][i]}</small></div>)}</div></div>
        <div className="wf-p-activity"><b>{t.today}</b><div><Symbol name="sales"/><span>{lang==='es'?'Pedido de ejemplo':'Sample order'}<small>{t.payments}</small></span><em>{t.paid}</em><strong>$45</strong></div><div><Symbol name="bookings"/><span>{lang==='es'?'Cita de ejemplo':'Sample appointment'}<small>{lang==='es'?'Profesional A · 10:00 AM':'Professional A · 10:00 AM'}</small></span><em>{t.confirmed}</em></div></div>
      </div>
    </div>
  </div>
}

export default function HomePage({lang,setLang}:{lang:Language,setLang:(value:Language)=>void}) {
  const t=copy[lang]; const [menu,setMenu]=useState(false);const [tab,setTab]=useState(0);const [quantity,setQuantity]=useState(0);const [professional,setProfessional]=useState('A');const [time,setTime]=useState('10:00 AM');const [booking,setBooking]=useState(false)
  const nav=['#plataforma','#explorar','#como-funciona','#planes']
  return <div className="wf-premium-home" id="top">
    <header className="wf-p-header"><a href="/" className="wf-p-logo"><AdaptiveLogo alt="WebFactory PR"/></a><nav className={menu?'open':''} aria-label={lang==='es'?'Navegación principal':'Main navigation'}>{t.nav.map((label,i)=><a key={label} href={nav[i]} onClick={()=>setMenu(false)}>{label}</a>)}<a href="/client-admin">{t.login} ↗</a></nav><div className="wf-p-header-actions"><div className="wf-p-languages"><button aria-pressed={lang==='en'} onClick={()=>setLang('en')}>EN</button><button aria-pressed={lang==='es'} onClick={()=>setLang('es')}>ES</button></div><ThemeToggle/><button className="wf-p-menu" aria-label={lang==='es'?'Menú':'Menu'} aria-expanded={menu} onClick={()=>setMenu(!menu)}>☰</button></div></header>
    <main>
      <section className="wf-p-hero wf-p-shell"><div className="wf-p-hero-copy"><p className="wf-p-eyebrow"><span/>{t.eyebrow}</p><h1>{t.title}<br/><em>{t.accent}</em></h1><p className="wf-p-lead">{t.lead}</p><div className="wf-p-actions"><a className="wf-p-button" href="/builder">{t.start}<span>↗</span></a><a className="wf-p-text-link" href="/templates">{t.templates} →</a></div><p className="wf-p-trial">{t.trial}</p></div><div className="wf-p-hero-preview"><div className="wf-p-orbit" aria-hidden="true"/><ControlPreview lang={lang}/><div className="wf-p-connected"><span className="wf-p-dot"/>{lang==='es'?'Website + ventas + reservas':'Website + sales + bookings'}</div></div></section>
      <section className="wf-p-strip wf-p-shell" aria-label={t.portal}>{[t.sales,t.bookings,t.payments,t.customers,t.team,t.reports].map((s,i)=><span key={s}><Symbol name={['sales','bookings','payments','customers','team','reports'][i]}/>{s}</span>)}</section>
      <section className="wf-p-section wf-p-shell" id="explorar"><div className="wf-p-section-heading"><p className="wf-p-eyebrow">{t.explore}</p><h2>{t.exploreTitle}</h2><p>{t.exploreText}</p></div>
        <div className="wf-p-demo"><div className="wf-p-tabs" role="tablist" aria-label={t.explore}>{t.tabs.map((label,i)=><button key={label} id={`wf-demo-tab-${i}`} role="tab" aria-selected={tab===i} aria-controls="wf-demo-panel" tabIndex={tab===i?0:-1} onKeyDown={e=>{if(e.key==='ArrowRight'||e.key==='ArrowLeft'){e.preventDefault();const next=(i+(e.key==='ArrowRight'?1:2))%3;setTab(next);document.getElementById(`wf-demo-tab-${next}`)?.focus()}}} onClick={()=>setTab(i)}><Symbol name={['sales','bookings','reports'][i]}/>{label}</button>)}</div>
          <div className="wf-p-demo-content" id="wf-demo-panel" role="tabpanel" aria-labelledby={`wf-demo-tab-${tab}`} tabIndex={0}>
            <div className="wf-p-demo-copy"><span className="wf-p-number">0{tab+1}</span><h3>{[t.sellTitle,t.bookTitle,t.manageTitle][tab]}</h3><p>{[t.sellText,t.bookText,t.manageText][tab]}</p><small>{t.demoNote}</small></div>
            {tab===0?<div className="wf-p-shop"><div className="wf-p-product"><div className="wf-p-product-art" aria-hidden="true"><div>WF<span>CARE</span></div><div/></div><div><small>WEBFACTORY DEMO</small><h4>{t.item}</h4><strong>$29.00</strong></div><button className="wf-p-button" onClick={()=>setQuantity(q=>q+1)}>{t.add} +</button></div><div className="wf-p-cart" aria-live="polite"><h4>{t.cart}<span>{quantity}</span></h4>{quantity?<><p>{quantity} × {t.item}<button aria-label={lang==='es'?'Quitar un producto':'Remove one product'} onClick={()=>setQuantity(q=>Math.max(0,q-1))}>−</button></p><div className="wf-p-total"><small>{t.total}</small><strong>${(quantity*29).toFixed(2)}</strong></div><button className="wf-p-text-link" onClick={()=>setQuantity(0)}>{t.clear}</button></>:<p className="wf-p-empty">{t.empty}</p>}</div></div>:tab===1?<div className="wf-p-booking"><label>{t.service}<div className="wf-p-field">{t.serviceName}<span>$45 · 30 min</span></div></label><label>{t.professional}<select value={professional} onChange={e=>{setProfessional(e.target.value);setBooking(false)}}><option value="A">{lang==='es'?'Profesional A':'Professional A'}</option><option value="B">{lang==='es'?'Profesional B':'Professional B'}</option></select></label><fieldset><legend>{t.schedule}</legend>{['10:00 AM','11:30 AM','2:00 PM'].map(v=><button key={v} aria-pressed={v===time} onClick={()=>{setTime(v);setBooking(false)}}>{v}</button>)}</fieldset><button className="wf-p-button" onClick={()=>setBooking(true)}>{t.book} →</button>{booking&&<div className="wf-p-booking-ready" role="status">✓ {t.bookingReady}<small>{professional} · {time} · $45</small></div>}</div>:<div className="wf-p-manage"><ControlPreview lang={lang} compact/><a href="/client-admin" className="wf-p-text-link">{t.login} →</a></div>}
          </div>
        </div>
      </section>
      <section className="wf-p-section wf-p-shell" id="plataforma"><div className="wf-p-section-heading"><p className="wf-p-eyebrow">{t.toolsLabel}</p><h2>{t.toolsTitle}</h2></div><div className="wf-p-tools">{t.tools.map(([title,text],i)=><article key={title}><Symbol name={['reports','sales','bookings','customers'][i]}/><h3>{title}</h3><p>{text}</p></article>)}</div></section>
      <section className="wf-p-section wf-p-shell" id="como-funciona"><div className="wf-p-section-heading"><p className="wf-p-eyebrow">{t.stepsLabel}</p><h2>{t.stepsTitle}</h2></div><div className="wf-p-steps">{t.steps.map(([title,text],i)=><article key={title}><span>0{i+1}</span><h3>{title}</h3><p>{text}</p></article>)}</div></section>
      <section className="wf-p-section wf-p-shell" id="planes"><div className="wf-p-pricing"><div><p className="wf-p-eyebrow">{t.priceLabel}</p><h2>{t.priceTitle}</h2><p>{t.priceText}</p><span>{t.noCommission}</span></div><div className="wf-p-price"><strong>$30<small>{t.month}</small></strong><p>{t.annual}</p><a className="wf-p-button" href="/builder">{t.start} ↗</a><small>{t.trial.split(' · ').slice(0,2).join(' · ')}</small></div></div><div className="wf-p-faq">{t.faq.map(([q,a])=><details key={q}><summary>{q}<span>+</span></summary><p>{a}</p></details>)}</div></section>
    </main>
    <footer className="wf-p-footer wf-p-shell"><div><a className="wf-p-logo" href="/"><AdaptiveLogo alt="WebFactory PR"/></a><p>{t.footer}</p><small>© 2026 WebFactory PR</small></div><nav aria-label={lang==='es'?'Enlaces legales':'Legal links'}><a href="mailto:info@webfactorypr.com">info@webfactorypr.com</a>{t.legal.map((s,i)=><a key={s} href={['/privacy','/terms','/refund-policy'][i]}>{s}</a>)}<FeedbackPreferences lang={lang}/></nav></footer>
  </div>
}
