import { useEffect, useState } from 'react'

type Order={kind:string;items:Array<{name:string;quantity:number}>;status:string;paymentStatus:string;kitchenStatus:string;queueNumber:string;turnNumber:number;locationName:string;updatedAt:string;paidAt:string}

export default function OrderTrackingPage({token}:{token:string}){
  const [order,setOrder]=useState<Order|null>(null);const [error,setError]=useState('');const es=document.documentElement.lang==='es'
  useEffect(()=>{let active=true;const load=()=>fetch(`/.netlify/functions/public-order-tracking?token=${encodeURIComponent(token)}`,{cache:'no-store'}).then(async r=>{const x=await r.json();if(!r.ok)throw new Error(x.message);if(active){setOrder(x.order);setError('')}}).catch(e=>{if(active)setError(e instanceof Error?e.message:'Could not load order.')});void load();const timer=window.setInterval(load,5000);return()=>{active=false;window.clearInterval(timer)}},[token])
  const copy=async()=>{try{await navigator.clipboard.writeText(location.href)}catch{setError(es?'No se pudo copiar el enlace.':'Could not copy the link.')}}
  const share=async()=>{if(navigator.share){try{await navigator.share({title:es?'Seguimiento de pedido':'Order tracking',url:location.href})}catch{}}else await copy()}
  const kitchenLabel:Record<string,{es:string;en:string}>={received:{es:'Recibida',en:'Received'},preparing:{es:'En preparación',en:'Preparing'},ready:{es:'Lista para recoger',en:'Ready for pickup'},completed:{es:'Entregada',en:'Completed'}}
  return <main className="cs-state"><article className="cs-tracking-card"><small>{es?'SEGUIMIENTO DEL PEDIDO':'ORDER TRACKING'}</small><h1>{es?'Estado de tu pedido':'Your order status'}</h1>{error&&<p role="alert">{error}</p>}{!order&&!error&&<p>{es?'Cargando…':'Loading…'}</p>}{order&&<><p>{order.locationName&&<b>{order.locationName} · </b>}{order.turnNumber>0&&<b>{es?`Turno #${order.turnNumber} · `:`Turn #${order.turnNumber} · `}</b>}{order.kitchenStatus?(kitchenLabel[order.kitchenStatus]?.[es?'es':'en']||order.kitchenStatus):order.paymentStatus==='due'?(es?'Pago pendiente en el local':'Payment due at location'):order.paymentStatus==='paid'||order.paymentStatus==='paid_in_person'?(es?'Pago confirmado':'Payment confirmed'):(es?'Confirmando pago':'Confirming payment')}</p><ul>{order.items.map((item,i)=><li key={`${item.name}-${i}`}>{item.name} × {item.quantity}</li>)}</ul><p>{es?'Actualizado':'Updated'}: {new Date(order.updatedAt).toLocaleString(es?'es-PR':'en-US')}</p><div className="cs-tracking-actions"><button onClick={copy}>{es?'Copiar enlace':'Copy link'}</button><button onClick={share}>{es?'Compartir':'Share'}</button></div></>}</article></main>
}
