import { useEffect, useState, type FormEvent } from 'react'

type PaymentLinkData={business:{name:string;logo:string};link:{title:string;description:string;amount:number;currency:string;allowQuantity:boolean}}
const money=(cents:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format((Number(cents)||0)/100)

export default function PaymentLinkPage({slug,token}:{slug:string;token:string}){
  const [data,setData]=useState<PaymentLinkData|null>(null);const [name,setName]=useState('');const [email,setEmail]=useState('');const [phone,setPhone]=useState('');const [quantity,setQuantity]=useState(1);const [busy,setBusy]=useState(false);const [error,setError]=useState('')
  const success=new URLSearchParams(location.search).get('checkout')==='success'
  useEffect(()=>{fetch(`/.netlify/functions/public-payment-link?slug=${encodeURIComponent(slug)}&token=${encodeURIComponent(token)}`,{cache:'no-store'}).then(async r=>{const body=await r.json();if(!r.ok||body.ok===false)throw new Error(body.message||'Payment link unavailable.');setData(body)}).catch(e=>setError(e instanceof Error?e.message:'Payment link unavailable.'))},[slug,token])
  const submit=async(e:FormEvent)=>{e.preventDefault();setBusy(true);setError('');try{const r=await fetch('/.netlify/functions/create-payment-link-checkout',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({slug,token,quantity,customer:{name,email,phone}})});const body=await r.json();if(!r.ok||body.ok===false)throw new Error(body.message||'Checkout could not be opened.');location.assign(body.checkoutUrl)}catch(err){setError(err instanceof Error?err.message:'Checkout could not be opened.');setBusy(false)}}
  return <main className="wf-pay-page"><section className="wf-pay-card">{data?.business.logo?<img src={data.business.logo} alt={data.business.name}/>:<img src="/webfactory-pr-logo.png" alt="WebFactory PR"/>}<small>SECURE PAYMENT · WEBFACTORY</small>{success?<><h1>Payment received</h1><p>Your payment was submitted successfully. You can close this page or return to {data?.business.name||'the business'}.</p></>:!data&&!error?<p>Loading payment…</p>:data?<><h1>{data.link.title}</h1>{data.link.description&&<p>{data.link.description}</p>}<div className="wf-pay-amount">{money(data.link.amount*quantity)}</div><form onSubmit={submit}><label>Name<input value={name} onChange={e=>setName(e.target.value)} required/></label><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>Phone<input value={phone} onChange={e=>setPhone(e.target.value)}/></label>{data.link.allowQuantity&&<label>Quantity<input type="number" min="1" max="20" value={quantity} onChange={e=>setQuantity(Math.max(1,Math.min(20,Number(e.target.value)||1)))}/></label>}<button disabled={busy}>{busy?'Opening secure checkout…':`Pay ${money(data.link.amount*quantity)}`}</button></form><p className="wf-pay-note">Card processing is completed securely through the connected Stripe account of {data.business.name}.</p></>:null}{error&&<div className="ca-error">{error}</div>}</section></main>
}
