import { useEffect, useState } from 'react'
import { PortalPanel } from './PortalPanel'
import RevenueChart from './RevenueChart'
import { withAuthRetry } from './auth-retry'
import './platform-sales.css'

type Revenue={available:boolean;reason?:string;complete?:boolean;mode?:string;generatedAt?:string;periodStart?:string;periodEnd?:string;capturedCents?:number;netCents?:number;refundedCents?:number;paymentCount?:number;last7DaysCents?:number;days?:Array<{date:string;netCents:number}>}
export default function PlatformRevenue({lang,refreshKey}:{lang:'en'|'es';refreshKey:string}){
  const es=lang==='es';const [revenue,setRevenue]=useState<Revenue|null>(null);const [loading,setLoading]=useState(true);const [retry,setRetry]=useState(0)
  useEffect(()=>{let active=true;setLoading(true);withAuthRetry(async()=>{const response=await fetch('/.netlify/functions/webfactory-admin-revenue',{credentials:'include',cache:'no-store'});const result=await response.json();if(!response.ok||result.ok===false)throw new Error('Revenue unavailable');return result.revenue as Revenue}).then(value=>{if(active)setRevenue(value)}).catch(()=>{if(active)setRevenue({available:false,reason:'temporarily_unavailable'})}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[refreshKey,retry])
  const money=(cents:number)=>new Intl.NumberFormat(es?'es-PR':'en-US',{style:'currency',currency:'USD'}).format(cents/100)
  const date=(value:string)=>new Date(`${value}T12:00:00Z`).toLocaleDateString(es?'es-PR':'en-US',{month:'short',day:'numeric',timeZone:'America/Puerto_Rico'})
  const days=revenue?.days||[];const ready=!loading&&revenue?.available
  const metrics=[[es?'Ventas netas · 30 días':'Net sales · 30 days',money(revenue?.netCents||0),es?'Cobros menos reembolsos':'Payments less refunds'],[es?'Ventas · últimos 7 días':'Sales · last 7 days',money(revenue?.last7DaysCents||0),es?'Total de la gráfica diaria':'Daily chart total'],[es?'Pagos confirmados':'Confirmed payments',String(revenue?.paymentCount||0),es?'Dentro del período':'Within this period'],[es?'Reembolsos aplicados':'Applied refunds',money(revenue?.refundedCents||0),es?'Sobre cobros del período':'On payments in this period']]
  const breakdown=[[es?'Cobros recibidos':'Captured payments',revenue?.capturedCents??((revenue?.netCents||0)+(revenue?.refundedCents||0))],[es?'Reembolsos':'Refunds',revenue?.refundedCents||0]] as Array<[string,number]>
  const breakdownMax=Math.max(1,...breakdown.map(([,amount])=>amount))
  return <section className="wfa-sales wfa-revenue" aria-label={es?'Ventas de WebFactory':'WebFactory sales'} aria-busy={loading}>
    <header className="wfa-sales-heading"><div><small>{es?'INGRESOS DE WEBFACTORY':'WEBFACTORY REVENUE'}</small><h2>{es?'Ventas y cobros de tu plataforma':'Your platform sales and payments'}</h2><p>{es?'Cuenta Stripe de WebFactory · USD · Últimos 30 días':'WebFactory Stripe account · USD · Last 30 days'}</p></div><button type="button" onClick={()=>setRetry(value=>value+1)} disabled={loading}>{es?'Actualizar ventas':'Refresh sales'}</button></header>
    <div aria-live="polite">{loading?<p className="wfa-empty">{es?'Consultando cobros en Stripe…':'Loading payments from Stripe…'}</p>:!revenue?.available?<p className="wfa-empty">{revenue?.reason==='not_configured'?(es?'Conecta Stripe para consultar los cobros de WebFactory.':'Configure Stripe to view WebFactory payments.'):(es?'No pudimos consultar los ingresos. Pulsa Actualizar ventas para intentar de nuevo.':'Revenue could not be loaded. Select Refresh sales to try again.')}</p>:null}</div>
    {ready&&<>{revenue.mode==='test'&&<p className="wfa-alert danger" role="status">{es?'MODO DE PRUEBAS · Estos cobros no son ingresos reales.':'TEST MODE · These payments are not real revenue.'}</p>}{!revenue.complete&&<p className="wfa-alert danger" role="status">{es?'Historial parcial: los totales corresponden solo a los cobros cargados.':'Partial history: totals only reflect loaded payments.'}</p>}</>}
    <div className="wfa-sales-metrics">{metrics.map(([label,value,note])=><article className="wfa-stat" key={label}><small>{label}</small><strong>{ready?value:'—'}</strong><span>{ready?note:(es?'Pendiente de datos verificados':'Awaiting verified data')}</span></article>)}</div>
    <div className="wfa-sales-charts">
      <PortalPanel className="wfa-card wfa-sales-chart"><header><div><small>{es?'RENDIMIENTO':'PERFORMANCE'}</small><h3>{es?'Ventas de los últimos 7 días':'Sales in the last 7 days'}</h3></div><strong>{ready?money(revenue.last7DaysCents||0):'—'}</strong></header>
        {ready?<RevenueChart variant="platform" lang={lang} days={days.map(day=>({key:day.date,dateLabel:date(day.date),label:new Date(`${day.date}T12:00:00Z`).toLocaleDateString(es?'es-PR':'en-US',{weekday:'short',timeZone:'America/Puerto_Rico'}),amount:day.netCents}))}/>:<p className="wfa-sales-empty">{es?'La gráfica aparecerá cuando se puedan consultar los cobros.':'The chart will appear when payments can be retrieved.'}</p>}
        <p className="wfa-note">{es?'USD · Cobros netos · Zona horaria de Puerto Rico':'USD · Net payments · Puerto Rico time zone'}</p>
      </PortalPanel>
      <PortalPanel className="wfa-card wfa-sales-chart"><header><div><small>{es?'RESUMEN DE COBROS':'PAYMENT SUMMARY'}</small><h3>{es?'Cobros y reembolsos':'Payments and refunds'}</h3></div></header>
        {ready?<div className="wfa-sales-breakdown" role="img" aria-label={breakdown.map(([label,amount])=>`${label}: ${money(amount)}`).join('; ')}>{breakdown.map(([label,amount],index)=><div key={label}><div><span>{label}</span><strong>{money(amount)}</strong></div><div className="wfa-sales-track"><i className={index?'is-refund':''} style={{width:`${amount/breakdownMax*100}%`}}/></div></div>)}</div>:<p className="wfa-sales-empty">{es?'Sin datos disponibles. No se muestran importes estimados.':'No data available. Estimated amounts are not shown.'}</p>}
        <p className="wfa-note">{es?'Últimos 30 días · Los reembolsos reducen las ventas netas.':'Last 30 days · Refunds reduce net sales.'}</p>
      </PortalPanel>
    </div>
    {ready&&<>{!revenue.paymentCount&&<p className="wfa-note">{es?'No hay cobros confirmados en este período.':'No confirmed payments in this period.'}</p>}<p className="wfa-note">{revenue.periodStart&&date(revenue.periodStart)} – {revenue.periodEnd&&date(revenue.periodEnd)} · USD · Puerto Rico{revenue.generatedAt&&` · ${es?'Actualizado':'Updated'} ${new Date(revenue.generatedAt).toLocaleTimeString(es?'es-PR':'en-US',{hour:'numeric',minute:'2-digit',timeZone:'America/Puerto_Rico'})}`}</p></>}
    <p className="wfa-note">{es?'Cuenta Stripe de WebFactory. Excluye ventas destinadas a clientes, otras monedas y cobros disputados. Antes de comisiones, impuestos y gastos; no representa ganancias ni saldo disponible. Los reembolsos se descuentan del día original del cobro.':'WebFactory Stripe account. Excludes client destination payments, other currencies and disputed charges. Before fees, taxes and expenses; this is not profit or available balance. Refunds reduce the original payment day.'}</p>
  </section>
}
