import { useEffect, useState } from 'react'
import { PortalPanel } from './PortalPanel'
import { withAuthRetry } from './auth-retry'

type Revenue={available:boolean;reason?:string;complete?:boolean;mode?:string;generatedAt?:string;periodStart?:string;periodEnd?:string;netCents?:number;refundedCents?:number;paymentCount?:number;last7DaysCents?:number;days?:Array<{date:string;netCents:number}>}
export default function PlatformRevenue({lang,refreshKey}:{lang:'en'|'es';refreshKey:string}){
  const es=lang==='es';const [revenue,setRevenue]=useState<Revenue|null>(null);const [loading,setLoading]=useState(true)
  useEffect(()=>{let active=true;setLoading(true);withAuthRetry(async()=>{const response=await fetch('/.netlify/functions/webfactory-admin-revenue',{credentials:'include',cache:'no-store'});const result=await response.json();if(!response.ok||result.ok===false)throw new Error('Revenue unavailable');return result.revenue as Revenue}).then(value=>{if(active)setRevenue(value)}).catch(()=>{if(active)setRevenue({available:false,reason:'temporarily_unavailable'})}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[refreshKey])
  const money=(cents:number)=>new Intl.NumberFormat(es?'es-PR':'en-US',{style:'currency',currency:'USD'}).format(cents/100)
  const chartAmount=(cents:number)=>new Intl.NumberFormat(es?'es-PR':'en-US',{notation:cents>=100000?'compact':'standard',maximumFractionDigits:cents>=100000?1:2}).format(cents/100)
  const date=(value:string)=>new Date(`${value}T12:00:00Z`).toLocaleDateString(es?'es-PR':'en-US',{month:'short',day:'numeric',timeZone:'America/Puerto_Rico'})
  const days=revenue?.days||[];const max=Math.max(1,...days.map(day=>day.netCents));const ready=!loading&&revenue?.available
  return <PortalPanel className="wfa-card wfa-revenue"><header><div><small>{es?'INGRESOS DE WEBFACTORY':'WEBFACTORY REVENUE'}</small><h2>{es?'Cobros de tu plataforma':'Your platform payments'}</h2></div><span className="wfa-revenue-period">{es?'Últimos 30 días':'Last 30 days'}</span></header>
    <div aria-live="polite">{loading?<p className="wfa-empty">{es?'Consultando cobros en Stripe…':'Loading payments from Stripe…'}</p>:!revenue?.available?<p className="wfa-empty">{revenue?.reason==='not_configured'?(es?'Conecta Stripe para consultar los cobros de WebFactory.':'Configure Stripe to view WebFactory payments.'):(es?'No pudimos consultar los ingresos. Pulsa Actualizar datos para intentar de nuevo.':'Revenue could not be loaded. Select Refresh data to try again.')}</p>:null}</div>
    {ready&&<>{revenue.mode==='test'&&<p className="wfa-alert danger" role="status">{es?'MODO DE PRUEBAS · Estos cobros no son ingresos reales.':'TEST MODE · These payments are not real revenue.'}</p>}{!revenue.complete&&<p className="wfa-alert danger" role="status">{es?'Historial parcial: los totales corresponden solo a los cobros cargados.':'Partial history: totals only reflect loaded payments.'}</p>}
    <div className="wfa-revenue-metrics">{[[es?'Cobros netos · 30 días':'Net payments · 30 days',money(revenue.netCents||0),es?'Cobrado menos reembolsos':'Captured less refunds'],[es?'Últimos 7 días':'Last 7 days',money(revenue.last7DaysCents||0),es?'Total de la gráfica':'Chart total'],[es?'Pagos confirmados':'Confirmed payments',String(revenue.paymentCount||0),es?'Dentro del período':'Within this period'],[es?'Reembolsos aplicados':'Applied refunds',money(revenue.refundedCents||0),es?'Sobre cobros del período':'On payments in this period']].map(([label,value,note])=><article key={label}><small>{label}</small><strong>{value}</strong><span>{note}</span></article>)}</div>
    <h3>{es?'Cobros de los últimos 7 días':'Payments in the last 7 days'}</h3><div className="wfa-revenue-chart" role="img" aria-label={days.map(day=>`${date(day.date)}: ${money(day.netCents)}`).join('; ')}>{days.map(day=><div key={day.date}><span title={money(day.netCents)}>{chartAmount(day.netCents)}</span><div className="wfa-revenue-track"><i style={{height:`${day.netCents/max*100}%`}}/></div><small>{new Date(`${day.date}T12:00:00Z`).toLocaleDateString(es?'es-PR':'en-US',{weekday:'short',timeZone:'America/Puerto_Rico'})}</small></div>)}</div>
    {!revenue.paymentCount&&<p className="wfa-note">{es?'No hay cobros confirmados en este período.':'No confirmed payments in this period.'}</p>}
    <p className="wfa-note">{revenue.periodStart&&date(revenue.periodStart)} – {revenue.periodEnd&&date(revenue.periodEnd)} · USD · {es?'Puerto Rico':'Puerto Rico'}{revenue.generatedAt&&` · ${es?'Actualizado':'Updated'} ${new Date(revenue.generatedAt).toLocaleTimeString(es?'es-PR':'en-US',{hour:'numeric',minute:'2-digit',timeZone:'America/Puerto_Rico'})}`}</p>
    <p className="wfa-note">{es?'Cuenta Stripe de WebFactory. Excluye ventas destinadas a clientes, otras monedas y cobros disputados. Antes de comisiones, impuestos y gastos; no representa ganancias ni saldo disponible. Los reembolsos se descuentan del día original del cobro.':'WebFactory Stripe account. Excludes client destination payments, other currencies and disputed charges. Before fees, taxes and expenses; this is not profit or available balance. Refunds reduce the original payment day.'}</p></>}
  </PortalPanel>
}
