import ReceiptPaper, { type ReceiptRecord } from './ReceiptPaper'
import TemplateHighlights from './TemplateHighlights'
import {templateBySlug} from './templateData'
import {localizeTemplate} from './templateI18n'

const sample: ReceiptRecord = {
  receiptId: 'rcpt-ejemplo', transactionId: 'transaccion-ejemplo', total: 2541,
  paymentStatus: 'paid', paymentMethod: 'card', createdAt: '2026-10-08T16:00:00Z',
  customer: { name: 'Cliente de ejemplo', email: 'cliente@example.invalid' },
  items: [{ name: 'Producto de ejemplo', quantity: 2, unitAmount: 1100, amount: 2200 }],
  subtotal: 2200, discounts: 100, tax: 241, tip: 200,
}

export default function StyleReferenceReview({ lang, device, theme }: {
  lang: 'es' | 'en'; device: 'desktop' | 'mobile'; theme: 'dark' | 'light'
}) {
  const es = lang === 'es', width = device === 'mobile' ? 390 : 1280
  const template=localizeTemplate(templateBySlug('brisa-cocina')!,lang)
  return <div className="pr-style-review">
    <p className="pr-caption">{es ? 'Estilos adaptados de tus archivos. Capturas del código real con datos de ejemplo.' : 'Styles adapted from your files. Captures of the actual code using sample data.'}</p>
    <section><h2>{es?'Sidebar original integrado':'Integrated original sidebar'}</h2><p className="pr-caption">{es?'Vidrio, expansión de 74 a 240 px y magnificación de iconos del código original. Colores WebFactory, búsqueda de secciones y navegación conectadas a cada portal. En móvil se abre sobre el contenido. Capturas con cuentas de ejemplo.':'Original glass, 74-to-240 px expansion and icon magnification. WebFactory colors, section search and navigation connected to each portal. Opens over the content on mobile. Captures use sample accounts.'}</p><div className="pr-style-dashboards">{(['client-admin','webfactory-admin'] as const).map(portal=><figure className="pr-shot" key={portal}><img src={`/preview-review/styles/${portal}-sidebar-${width}-${theme}.webp`} alt={es?'Sidebar expandido con navegación del portal':'Expanded sidebar with portal navigation'}/><figcaption>{portal==='client-admin'?(es?'Portal del cliente':'Client portal'):(es?'Administración WebFactory':'WebFactory administration')}</figcaption></figure>)}</div></section>
    <section><h2>{es?'Carousel Glasssy V2':'Glasssy V2 carousel'}</h2><p className="pr-caption">{es?'Componentes y animaciones del código original, conectados al catálogo de ejemplo y a los colores de la plataforma. Prueba arrastrar, ampliar, guardar favoritos y reproducir.':'Original source components and animations, connected to the sample catalog and platform colors. Try dragging, expanding details, bookmarking and playing.'}</p><div className="template-site" style={{maxWidth:width,margin:'auto'}}><TemplateHighlights items={template.items} language={lang}/></div></section>
    <section><h2>{es ? 'Login Glassy' : 'Glassy login'}</h2><p><a href="/client-admin">{es ? 'Abrir login de clientes' : 'Open client login'} ↗</a> · <a href="/webfactory-admin">{es ? 'Abrir login administrativo' : 'Open admin login'} ↗</a></p><figure className="pr-shot"><img src={`/preview-review/styles/login-${width}-${theme}.webp`} alt={es ? 'Login con fondo original, botones azules y formulario de vidrio' : 'Login with original background, blue buttons and glass form'} /></figure></section>
    <section><h2>{es ? 'Dashboards Glassy' : 'Glassy dashboards'}</h2><div className="pr-style-dashboards">{(['client-admin', 'webfactory-admin'] as const).map(portal => <figure className="pr-shot" key={portal}><img src={`/preview-review/styles/${portal}-overview-${width}-${theme}.webp`} alt={portal === 'client-admin' ? (es ? 'Panel de negocio con vidrio y fondo original' : 'Business dashboard with glass and original background') : (es ? 'Centro administrativo con vidrio y fondo original' : 'Administrative center with glass and original background')} /><figcaption>{portal === 'client-admin' ? (es ? 'Panel del negocio · Datos de ejemplo' : 'Business dashboard · Sample data') : (es ? 'Centro administrativo · Datos de ejemplo' : 'Administrative center · Sample data')}</figcaption></figure>)}</div></section>
    <section><h2>{es?'Ventas administrativas':'Administrative sales'}</h2><p className="pr-caption">{es?'Tarjetas de ventas netas, últimos siete días, pagos y reembolsos. Gráficas diarias y de cobros frente a reembolsos. Capturas con datos de ejemplo; no representan ingresos reales.':'Net sales, last seven days, payments and refunds cards. Daily and payments-versus-refunds charts. Captures use sample data and do not represent real revenue.'}</p><figure className="pr-shot"><img src={`/preview-review/styles/sales-cards-${width}-${theme}.webp`} alt={es?'Cuatro tarjetas de ventas administrativas con datos de ejemplo':'Four administrative sales cards using sample data'}/></figure><div className="pr-style-dashboards">{['daily','refunds'].map(chart=><figure className="pr-shot" key={chart}><img src={`/preview-review/styles/sales-${chart}-${width}-${theme}.webp`} alt={es?(chart==='daily'?'Gráfica diaria de ventas de ejemplo':'Gráfica de cobros y reembolsos de ejemplo'):(chart==='daily'?'Sample daily sales chart':'Sample payments and refunds chart')}/></figure>)}</div></section>
    <section><h2>{es ? 'Recibo con impresora 3D' : 'Receipt with 3D printer'}</h2><p className="pr-caption">{es ? 'Impresión progresiva, papel curvado y controles para desprender e inspeccionar el recibo. Datos de ejemplo; el portal conserva el recibo guardado, PDF y reenvío.' : 'Progressive printing, curved paper and controls to tear and inspect the receipt. Sample data; the portal retains saved receipts, PDF and resend.'}</p><div className="pr-style-receipt" key={`${device}-${theme}`}><ReceiptPaper receipt={sample} lang={lang}/></div></section>
    <section><h2>{es ? 'Animación hacia el carrito' : 'Fly-to-cart animation'}</h2><p>{es ? 'Abre el catálogo del template y pulsa Añadir para ver cómo la imagen llega al carrito.' : 'Open the template catalog and press Add to see the image fly to the cart.'}</p><a href="/templates/brisa-cocina#services">{es ? 'Probar el carrito del template' : 'Try the template cart'} ↗</a></section>
  </div>
}
