import { useEffect, useMemo, useState, type FormEvent } from 'react'
import { acceptInvite, getUser, handleAuthCallback, login, logout, onAuthChange, requestPasswordRecovery, type User } from '@netlify/identity'
import './webfactory-admin.css'
import { withAuthRetry } from './auth-retry'

type ClientRow={siteId:string;slug:string;businessName:string;ownerEmail:string;status:string;revision:number;catalogItems:number;employees:number;stripeStatus:string;calendarConnected:boolean;planName:string;billingModel:string;billingStatus:string;subscriptionStatus:string;templateMode?:string;templateName?:string;templateCategory?:string;templatePath?:string;updatedAt:string;publicPath:string}
type OrderRow={orderId:string;businessName:string;customerEmail:string;status:string;amount:number;updatedAt:string;packageReady:boolean;adminEmailSent:boolean;customerEmailSent:boolean}
type AdminData={generatedAt:string;administrator:{email:string;name:string};summary:Record<string,number>;capacity:{level:string;safeClientCapacity:number;activeClients:number;estimatedOpenings:number;utilizationPercent:number;model:string};resources:{netlify:{plan:string;monthlyCredits:number|null;creditsUsed:number|null;utilizationPercent:number|null;productionDeployCreditCost:number;productionDeploysThisMonth:number|null;estimatedDeployCredits:number|null;apiConnected:boolean;apiError:string;source:string;dashboardUrl:string};storage:{clientAssets:number;orderAssets:number;productionPackages:number;trackedObjects:number;bytesKnown:boolean};runtime:{deployId:string;deployContext:string;published:boolean;siteName:string;siteUrl:string}};integrations:{configured:number;total:number;configuration:Array<{name:string;configured:boolean}>};subscriptionBilling:{enabled:boolean;stripeSecretConfigured:boolean;priceConfigured:boolean;monthlyPriceConfigured:boolean;annualPriceConfigured:boolean;webhookConfigured:boolean;missing:string[];ready:boolean};operations:{orderStatuses:Record<string,number>;transactionStatuses:Record<string,number>;stripeWebhookEvents:number;clientWebhookEvents:number;stuckOrders:OrderRow[];pendingTransactions:Array<{transactionId:string;siteId:string;kind:string;status:string;updatedAt:string}>};clients:ClientRow[];orders:OrderRow[]}
type ProvisionResult={siteId:string;slug:string;status:string;trialEndsAt:string;publicUrl:string;portalUrl:string;invitationSent:boolean}
type Tab='overview'|'clients'|'operations'|'resources'
type Language='es'|'en'

const adminCopy={
  es:{loginTitle:'Centro administrativo.',loginText:'Acceso exclusivo para supervisar clientes, integraciones, operaciones y capacidad de WebFactory.',password:'Contraseña',enter:'Entrar de forma segura',checking:'Verificando…',forgot:'¿Olvidaste tu contraseña?',sent:'Revisa tu email para restablecer la contraseña.',overview:'Resumen',clients:'Clientes',operations:'Operaciones',resources:'Recursos',logout:'Cerrar sesión',viewSite:'Ver WebFactory ↗',general:'Estado general',clientsTitle:'Clientes y tiendas',operationsTitle:'Salud operacional',resourcesTitle:'Recursos y capacidad',updated:'Actualizado',refresh:'Actualizar datos',refreshing:'Actualizando…',metrics:'Métricas operacionales',published:'Publicados',setup:'Configuración pendiente',activeSubs:'Suscripciones activas',pastDue:'Pagos vencidos'},
  en:{loginTitle:'Administrative center.',loginText:'Private access to supervise WebFactory clients, integrations, operations and capacity.',password:'Password',enter:'Sign in securely',checking:'Checking…',forgot:'Forgot password?',sent:'Check your email to reset your password.',overview:'Overview',clients:'Clients',operations:'Operations',resources:'Resources',logout:'Sign out',viewSite:'View WebFactory ↗',general:'General status',clientsTitle:'Clients and stores',operationsTitle:'Operational health',resourcesTitle:'Resources and capacity',updated:'Updated',refresh:'Refresh data',refreshing:'Refreshing…',metrics:'Operational metrics',published:'Published',setup:'Setup pending',activeSubs:'Active subscriptions',pastDue:'Past due'}
}


const api=()=>withAuthRetry(async()=>{const response=await fetch('/.netlify/functions/webfactory-admin-overview',{credentials:'include',cache:'no-store'});const result=await response.json();if(!response.ok||result.ok===false)throw new Error(result.message||'No se pudo cargar el Control Center.');return result as AdminData})
const provisionTrial=(payload:Record<string,string>)=>withAuthRetry(async()=>{const response=await fetch('/.netlify/functions/provision-client-trial',{method:'POST',credentials:'include',cache:'no-store',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const result=await response.json();if(!response.ok||result.ok===false)throw new Error(result.message||'The client trial could not be created.');return result as ProvisionResult})
const date=(value:string)=>value?new Intl.DateTimeFormat('es-PR',{dateStyle:'medium',timeStyle:'short'}).format(new Date(value)):'—'
const statusLabel=(value:string)=>value.replaceAll('_',' ').toLowerCase()

function AdminLogin({onLogin,lang,setLang}:{onLogin:(user:User)=>Promise<void>;lang:Language;setLang:(v:Language)=>void}){
  const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [sent,setSent]=useState(false);const t=adminCopy[lang]
  const submit=async(event:FormEvent)=>{event.preventDefault();setBusy(true);setError('');try{const current=await withAuthRetry(()=>login(email,password));await onLogin(current)}catch(e){setError(e instanceof Error?e.message:'No se pudo iniciar sesión.')}finally{setBusy(false)}}
  const recover=async()=>{if(!email)return setError(lang==='es'?'Escribe primero tu email.':'Enter your email first.');setBusy(true);setError('');try{await requestPasswordRecovery(email);setSent(true)}catch(e){setError(e instanceof Error?e.message:(lang==='es'?'No se pudo enviar el enlace.':'The recovery link could not be sent.'))}finally{setBusy(false)}}
  return <main className="wfa-login-page"><section className="wfa-login"><div className="portal-language"><button className={lang==='es'?'active':''} onClick={()=>setLang('es')}>ES</button><button className={lang==='en'?'active':''} onClick={()=>setLang('en')}>EN</button></div><img src="/webfactory-pr-logo.png" alt="WebFactory PR"/><small>CONTROL CENTER</small><h1>{t.loginTitle}</h1><p>{t.loginText}</p><form onSubmit={submit}><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} autoComplete="email" required/></label><label>{t.password}<input type="password" value={password} onChange={e=>setPassword(e.target.value)} autoComplete="current-password" required/></label><button disabled={busy}>{busy?t.checking:t.enter}</button></form><button className="wfa-text-button" onClick={recover}>{t.forgot}</button>{sent&&<div className="wfa-alert success">{t.sent}</div>}{error&&<div className="wfa-alert danger">{error}</div>}</section></main>
}

function Meter({value,label}:{value:number;label:string}){return <div className="wfa-meter"><div><span>{label}</span><b>{value}%</b></div><i><em style={{width:`${Math.min(100,Math.max(0,value))}%`}}/></i></div>}
function Stat({label,value,note}:{label:string;value:string|number;note:string}){return <article className="wfa-stat"><span>{label}</span><strong>{value}</strong><small>{note}</small></article>}
function Badge({value}:{value:string}){const clean=value.toLowerCase();const kind=['active','published','live','in_production','completed'].includes(clean)?'good':['failed','critical','suspended','past_due'].includes(clean)?'bad':'pending';return <span className={`wfa-badge ${kind}`}>{statusLabel(value)}</span>}

export default function WebFactoryAdminPage(){
  const [lang,setLang]=useState<Language>('es');const [user,setUser]=useState<User|null>(null);const [data,setData]=useState<AdminData|null>(null);const [loading,setLoading]=useState(true);const [refreshing,setRefreshing]=useState(false);const [error,setError]=useState('');const [tab,setTab]=useState<Tab>('overview');const [query,setQuery]=useState('');const [inviteToken,setInviteToken]=useState('');const [newPassword,setNewPassword]=useState('');const [acceptingInvite,setAcceptingInvite]=useState(false);const [provisioning,setProvisioning]=useState(false);const [newClient,setNewClient]=useState({businessName:'',ownerEmail:'',slug:'',contactName:'',category:'',locale:'es'});const [provisioned,setProvisioned]=useState<ProvisionResult|null>(null)
  const load=async(silent=false)=>{if(!silent)setRefreshing(true);setError('');try{setData(await api())}catch(e){setError(e instanceof Error?e.message:'No se pudo cargar el Control Center.')}finally{setRefreshing(false)}}
  useEffect(()=>{document.documentElement.lang=lang},[lang])
  useEffect(()=>{document.title='WebFactory Control Center';let unsubscribe=()=>{};(async()=>{try{const callback=await handleAuthCallback();if(callback?.type==='invite'&&callback.token){setInviteToken(callback.token);return}const current=callback?.user||await getUser();setUser(current);if(current)await load()}catch(e){setError(e instanceof Error?e.message:'No se pudo abrir el Control Center.')}finally{setLoading(false)}})();unsubscribe=onAuthChange((_event,current)=>setUser(current));return()=>unsubscribe()},[])
  useEffect(()=>{if(!user)return;const timer=window.setInterval(()=>load(true),5*60*1000);return()=>window.clearInterval(timer)},[user])
  const clients=useMemo(()=>{const term=query.trim().toLowerCase();return !term?(data?.clients||[]):(data?.clients||[]).filter(client=>[client.businessName,client.ownerEmail,client.slug,client.siteId].some(value=>value.toLowerCase().includes(term)))},[data,query])
  const signOut=async()=>{await logout();setUser(null);setData(null)}
  const createTrial=async(event:FormEvent)=>{event.preventDefault();setProvisioning(true);setProvisioned(null);setError('');try{const result=await provisionTrial(newClient);setProvisioned(result);setNewClient({businessName:'',ownerEmail:'',slug:'',contactName:'',category:'',locale:'es'});await load(true)}catch(e){setError(e instanceof Error?e.message:(lang==='es'?'No se pudo crear la prueba.':'The trial could not be created.'))}finally{setProvisioning(false)}}
  const acceptAdminInvite=async()=>{if(newPassword.length<8)return setError('Usa una contraseña de al menos 8 caracteres.');setAcceptingInvite(true);setError('');try{const invited=await acceptInvite(inviteToken,newPassword);if(!invited.email)throw new Error('La invitación no contiene un email válido.');const current=await withAuthRetry(()=>login(invited.email!,newPassword));setInviteToken('');setNewPassword('');setUser(current);await load()}catch(e){setError(e instanceof Error?e.message:'No se pudo activar el acceso administrativo.')}finally{setAcceptingInvite(false)}}
  if(loading)return <main className="wfa-login-page"><div className="wfa-loading">Abriendo Control Center seguro…</div></main>
  if(inviteToken)return <main className="wfa-login-page"><section className="wfa-login"><img src="/webfactory-pr-logo.png" alt="WebFactory PR"/><small>ACTIVACIÓN SEGURA</small><h1>Establece tu contraseña.</h1><p>Crea la contraseña privada para acceder al Centro Administrativo de WebFactory.</p><label>Nueva contraseña<input type="password" value={newPassword} onChange={e=>setNewPassword(e.target.value)} autoComplete="new-password" minLength={8} required/></label><button onClick={acceptAdminInvite} disabled={acceptingInvite}>{acceptingInvite?'Activando…':'Activar acceso administrativo'}</button>{error&&<div className="wfa-alert danger">{error}</div>}</section></main>
  if(!user)return <AdminLogin lang={lang} setLang={setLang} onLogin={async current=>{setUser(current);await load()}}/>
  if(!data&&refreshing)return <main className="wfa-login-page"><div className="wfa-loading">Cargando información administrativa…</div></main>
  if(!data)return <main className="wfa-login-page"><section className="wfa-login"><img src="/webfactory-pr-logo.png" alt="WebFactory PR"/><h1>Acceso no disponible</h1><div className="wfa-alert danger">{error||'No pudimos cargar la información administrativa.'}</div><button onClick={()=>load()}>Intentar nuevamente</button><button className="wfa-text-button" onClick={signOut}>Cerrar sesión</button></section></main>

  const s=data.summary;const t=adminCopy[lang];const capacityLabel={healthy:lang==='es'?'Saludable':'Healthy',watch:lang==='es'?'Observación':'Watch',warning:lang==='es'?'Precaución':'Warning',critical:lang==='es'?'Crítico':'Critical'}[data.capacity.level]||data.capacity.level
  return <main className="wfa-dashboard">
    <aside className="wfa-sidebar"><img src="/webfactory-pr-logo.png" alt="WebFactory PR"/><div className="wfa-admin-id"><small>{lang==='es'?'ADMINISTRADOR':'ADMINISTRATOR'}</small><strong>{data.administrator.name}</strong><span>{data.administrator.email}</span></div><div className="portal-language sidebar"><button className={lang==='es'?'active':''} onClick={()=>setLang('es')}>ES</button><button className={lang==='en'?'active':''} onClick={()=>setLang('en')}>EN</button></div><nav>{([['overview',t.overview],['clients',t.clients],['operations',t.operations],['resources',t.resources]] as Array<[Tab,string]>).map(([id,label])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}>{label}</button>)}</nav><a href="/" target="_blank">{t.viewSite}</a><button className="wfa-signout" onClick={signOut}>{t.logout}</button></aside>
    <section className="wfa-work"><header className="wfa-top"><div><small>WEBFACTORY CONTROL CENTER</small><h1>{tab==='overview'?t.general:tab==='clients'?t.clientsTitle:tab==='operations'?t.operationsTitle:t.resourcesTitle}</h1><p>{t.updated} {date(data.generatedAt)}</p></div><button onClick={()=>load()} disabled={refreshing}>{refreshing?t.refreshing:t.refresh}</button></header>{error&&<div className="wfa-alert danger">{error}</div>}
      {tab==='overview'&&<><section className="wfa-card wfa-chart-card"><header><div><small>{t.metrics.toUpperCase()}</small><h2>{lang==='es'?'Distribución actual':'Current distribution'}</h2></div></header><MetricBars rows={[[t.published,s.publishedSites||0],[t.setup,s.setupPending||0],[t.activeSubs,s.activeSubscriptions||0],[t.pastDue,s.pastDueSubscriptions||0]]}/></section><section className="wfa-stats"><Stat label={lang==='es'?'Clientes':'Clients'} value={s.clients} note={`${s.publishedSites} ${lang==='es'?'publicados':'published'}`}/><Stat label={lang==='es'?'Pedidos legacy':'Legacy orders'} value={s.productionOrders} note={`${s.completedOrders} ${lang==='es'?'completados':'completed'}`}/><Stat label={lang==='es'?'Stripe conectado':'Stripe connected'} value={`${s.connectedStripe}/${s.clients}`} note={lang==='es'?'Cuentas listas':'Accounts ready'}/><Stat label={lang==='es'?'Bloqueos':'Blockers'} value={s.blockers} note={lang==='es'?'Requieren revisión':'Need review'}/></section><div className="wfa-grid"><section className="wfa-card capacity"><header><div><small>{lang==='es'?'CAPACIDAD DE INCORPORACIÓN':'ONBOARDING CAPACITY'}</small><h2>{capacityLabel}</h2></div><span className={`wfa-health ${data.capacity.level}`}/></header><Meter value={data.capacity.utilizationPercent} label={lang==='es'?'Clientes registrados vs. límite seguro':'Registered clients vs. safe capacity'}/><div className="wfa-capacity-numbers"><div><strong>{data.capacity.estimatedOpenings}</strong><span>{lang==='es'?'espacios estimados':'estimated openings'}</span></div><div><strong>{data.capacity.safeClientCapacity}</strong><span>{lang==='es'?'límite operativo inicial':'initial operating limit'}</span></div></div><p>{data.capacity.model}</p></section><section className="wfa-card"><header><div><small>{lang==='es'?'INTEGRACIONES':'INTEGRATIONS'}</small><h2>{data.integrations.configured} {lang==='es'?'de':'of'} {data.integrations.total}</h2></div></header><div className="wfa-checks">{data.integrations.configuration.map(item=><div key={item.name}><i className={item.configured?'ready':''}/><span>{item.name}</span><b>{item.configured?(lang==='es'?'Lista':'Ready'):(lang==='es'?'Pendiente':'Pending')}</b></div>)}</div></section></div><section className="wfa-card"><header><div><small>{lang==='es'?'CLIENTES RECIENTES':'RECENT CLIENTS'}</small><h2>{lang==='es'?'Actividad de tiendas':'Store activity'}</h2></div><button onClick={()=>setTab('clients')}>{lang==='es'?'Ver todos':'View all'}</button></header><ClientTable clients={data.clients.slice(0,6)} lang={lang}/></section></>}
      {tab==='clients'&&<><section className="wfa-card wfa-provision"><header><div><small>{lang==='es'?'NUEVO CLIENTE SAAS':'NEW SAAS CLIENT'}</small><h2>{lang==='es'?'Iniciar prueba gratuita de 48 horas':'Start a free 48-hour trial'}</h2></div></header><p>{lang==='es'?'Crea el website con su enlace preferido y envía al propietario un email seguro para establecer su contraseña. No solicita tarjeta ni genera cargos.':'Create the website with its preferred link and send the owner a secure email to set a password. No card is requested and no charge is created.'}</p><form onSubmit={createTrial}><label>{lang==='es'?'Nombre del negocio':'Business name'}<input value={newClient.businessName} onChange={e=>setNewClient({...newClient,businessName:e.target.value})} required minLength={2}/></label><label>{lang==='es'?'Email del propietario':'Owner email'}<input type="email" value={newClient.ownerEmail} onChange={e=>setNewClient({...newClient,ownerEmail:e.target.value})} required/></label><label>{lang==='es'?'Enlace preferido':'Preferred link'}<div className="wfa-slug"><span>/sites/</span><input value={newClient.slug} onChange={e=>setNewClient({...newClient,slug:e.target.value.toLowerCase().replace(/[^a-z0-9-]/g,'')})} placeholder={lang==='es'?'nombre-del-negocio':'business-name'}/></div></label><label>{lang==='es'?'Persona de contacto':'Contact person'}<input value={newClient.contactName} onChange={e=>setNewClient({...newClient,contactName:e.target.value})}/></label><label>{lang==='es'?'Categoría':'Category'}<input value={newClient.category} onChange={e=>setNewClient({...newClient,category:e.target.value})}/></label><label>{lang==='es'?'Idioma inicial':'Initial language'}<select value={newClient.locale} onChange={e=>setNewClient({...newClient,locale:e.target.value})}><option value="es">Español</option><option value="en">English</option></select></label><button disabled={provisioning}>{provisioning?(lang==='es'?'Creando…':'Creating…'):(lang==='es'?'Crear trial y enviar acceso':'Create trial and send access')}</button></form>{provisioned&&<div className="wfa-alert success"><strong>{lang==='es'?'Trial creado correctamente.':'Trial created successfully.'}</strong><span>{lang==='es'?'El acceso privado fue enviado por email.':'Private access was sent by email.'}</span><a href={provisioned.publicUrl} target="_blank" rel="noreferrer">{lang==='es'?'Abrir website':'Open website'} ↗</a></div>}</section><section className="wfa-card"><header><div><small>{lang==='es'?'DIRECTORIO MULTI-CLIENTE':'MULTI-CLIENT DIRECTORY'}</small><h2>{clients.length} {lang==='es'?'tiendas':'stores'}</h2></div><input className="wfa-search" placeholder={lang==='es'?'Buscar negocio, email o enlace':'Search business, email, or link'} value={query} onChange={e=>setQuery(e.target.value)}/></header><ClientTable clients={clients} lang={lang}/></section></>}
      {tab==='operations'&&<><section className="wfa-stats"><Stat label={lang==='es'?'Eventos Stripe':'Stripe events'} value={data.operations.stripeWebhookEvents} note={lang==='es'?'Billing de suscripciones y checkout legacy':'Subscription billing and legacy checkout'}/><Stat label={lang==='es'?'Eventos de clientes':'Client events'} value={data.operations.clientWebhookEvents} note="Stripe Connect"/><Stat label={lang==='es'?'Pedidos legacy detenidos':'Stalled legacy orders'} value={data.operations.stuckOrders.length} note={lang==='es'?'Reintento posible':'Retry available'}/><Stat label={lang==='es'?'Transacciones pendientes':'Pending transactions'} value={data.operations.pendingTransactions.length} note="Commerce runtime"/></section><div className="wfa-grid"><StatusCard title={lang==='es'?'Estados de pedidos legacy':'Legacy order statuses'} values={data.operations.orderStatuses} lang={lang}/><StatusCard title={lang==='es'?'Estados de transacciones':'Transaction statuses'} values={data.operations.transactionStatuses} lang={lang}/></div><section className="wfa-card"><header><div><small>{lang==='es'?'ATENCIÓN OPERACIONAL':'OPERATIONAL ATTENTION'}</small><h2>{lang==='es'?'Procesos que necesitan revisión':'Processes that need review'}</h2></div></header>{data.operations.stuckOrders.length===0&&data.operations.pendingTransactions.length===0?<div className="wfa-empty good">{lang==='es'?'No encontramos trabajos detenidos.':'No stalled jobs found.'}</div>:<div className="wfa-issues">{data.operations.stuckOrders.map(order=><article key={order.orderId}><div><strong>{order.businessName}</strong><span>{order.orderId}</span></div><Badge value={order.status}/><time>{date(order.updatedAt)}</time></article>)}{data.operations.pendingTransactions.map(item=><article key={item.transactionId}><div><strong>{item.kind}</strong><span>{item.transactionId}</span></div><Badge value={item.status}/><time>{date(item.updatedAt)}</time></article>)}</div>}</section></>}
      {tab==='resources'&&<ResourcesTab data={data} lang={lang}/>}
    </section>
  </main>
}

function ClientTable({clients,lang}:{clients:ClientRow[];lang:Language}){return <div className="wfa-table-wrap"><table><thead><tr>{(lang==='es'?['Negocio','Estado','Template','Plan','Integraciones','Contenido','Actualizado']:['Business','Status','Template','Plan','Integrations','Content','Updated']).map(label=><th key={label}>{label}</th>)}<th/></tr></thead><tbody>{clients.map(client=><tr key={client.siteId}><td><strong>{client.businessName}</strong><span>{client.ownerEmail||client.slug}</span></td><td><Badge value={client.status}/></td><td><strong>{client.templateMode==='template_base'?(client.templateName||'Template'):'Custom'}</strong><span>{client.templateCategory||''}</span>{client.templatePath&&<a href={client.templatePath} target="_blank">{lang==='es'?'Ver Template':'View Template'} ↗</a>}</td><td><strong>{client.billingModel==='subscription'?(lang==='es'?'Suscripción':'Subscription'):(lang==='es'?'Pago único':'One-time payment')}</strong><span>{client.billingModel==='subscription'?statusLabel(client.subscriptionStatus):statusLabel(client.billingStatus)}</span></td><td><span>Stripe: {client.stripeStatus}</span><span>Calendar: {client.calendarConnected?(lang==='es'?'conectado':'connected'):(lang==='es'?'pendiente':'pending')}</span></td><td><span>{client.catalogItems} {lang==='es'?'artículos':'items'}</span><span>{client.employees} {lang==='es'?'empleados':'employees'}</span></td><td>{date(client.updatedAt)}</td><td>{client.publicPath&&<a href={client.publicPath} target="_blank">{lang==='es'?'Abrir':'Open'} ↗</a>}</td></tr>)}</tbody></table>{clients.length===0&&<div className="wfa-empty">{lang==='es'?'No hay tiendas que coincidan con la búsqueda.':'No stores match your search.'}</div>}</div>}
function StatusCard({title,values,lang}:{title:string;values:Record<string,number>;lang:Language}){const rows=Object.entries(values).sort((a,b)=>b[1]-a[1]);return <section className="wfa-card"><header><div><small>{lang==='es'?'RESUMEN':'SUMMARY'}</small><h2>{title}</h2></div></header><div className="wfa-status-list">{rows.length?rows.map(([status,count])=><div key={status}><Badge value={status}/><strong>{count}</strong></div>):<div className="wfa-empty">{lang==='es'?'Sin registros todavía.':'No records yet.'}</div>}</div></section>}

function ResourcesTab({data,lang}:{data:AdminData;lang:Language}){
  const es=lang==='es';const s=data.summary;const n=data.resources.netlify
  const state=(ready:boolean)=>ready?(es?'Configurado':'Configured'):(es?'Pendiente':'Pending')
  return <><div className="wfa-grid"><section className="wfa-card"><header><div><small>NETLIFY</small><h2>{n.plan}</h2></div><a href={n.dashboardUrl} target="_blank" rel="noreferrer">{es?'Abrir uso oficial':'Open official usage'} ↗</a></header>
    {n.utilizationPercent===null?<div className="wfa-empty">{es?'El API registra plan y despliegues. Netlify no expone el medidor oficial de créditos a este panel; usa el enlace para confirmar el saldo exacto.':'The API tracks plan and deploys. Netlify does not expose its official credit meter to this panel; use the link to confirm the exact balance.'}</div>:<Meter value={n.utilizationPercent} label={`${n.creditsUsed} ${es?'de':'of'} ${n.monthlyCredits} ${es?'créditos oficiales':'official credits'}`}/>}<dl>
      <div><dt>{es?'API de Netlify':'Netlify API'}</dt><dd>{n.apiConnected?(es?'Conectada':'Connected'):(es?'Falta token privado':'Private token required')}</dd></div>
      <div><dt>{es?'Deploys de producción este mes':'Production deploys this month'}</dt><dd>{n.productionDeploysThisMonth??(es?'No disponible':'Unavailable')}</dd></div>
      <div><dt>{es?'Créditos estimados por deploys':'Estimated deploy credits'}</dt><dd>{n.estimatedDeployCredits??'—'} {n.estimatedDeployCredits!==null?(es?'estimados':'estimated'):''}</dd></div>
      <div><dt>{es?'Costo de referencia por deploy':'Reference cost per deploy'}</dt><dd>{n.productionDeployCreditCost} {es?'créditos':'credits'}</dd></div>
      <div><dt>{es?'Contexto actual':'Current context'}</dt><dd>{data.resources.runtime.deployContext}</dd></div><div><dt>{es?'Publicado':'Published'}</dt><dd>{data.resources.runtime.published?(es?'Sí':'Yes'):'No'}</dd></div><div><dt>Deploy ID</dt><dd>{data.resources.runtime.deployId||(es?'No disponible':'Unavailable')}</dd></div></dl><p className="wfa-note">{n.source}</p></section>
    <section className="wfa-card"><header><div><small>{es?'ALMACENAMIENTO RASTREADO':'TRACKED STORAGE'}</small><h2>{data.resources.storage.trackedObjects} {es?'objetos':'objects'}</h2></div></header><dl><div><dt>{es?'Imágenes de clientes':'Client images'}</dt><dd>{data.resources.storage.clientAssets}</dd></div><div><dt>{es?'Archivos legacy':'Legacy order files'}</dt><dd>{data.resources.storage.orderAssets}</dd></div><div><dt>Legacy Production Packages</dt><dd>{data.resources.storage.productionPackages}</dd></div><div><dt>{es?'Tamaño exacto':'Exact size'}</dt><dd>{data.resources.storage.bytesKnown?(es?'Disponible':'Available'):(es?'No expuesto por el listado actual':'Not exposed by the current listing')}</dd></div></dl></section></div>
    <div className="wfa-grid"><section className="wfa-card"><header><div><small>STRIPE BILLING</small><h2>{data.subscriptionBilling.enabled?(es?'Habilitado':'Enabled'):(es?'Desactivado':'Disabled')}</h2></div><Badge value={data.subscriptionBilling.ready?'active':'setup_pending'}/></header><dl><div><dt>{es?'Clave Stripe':'Stripe key'}</dt><dd>{state(data.subscriptionBilling.stripeSecretConfigured)}</dd></div><div><dt>{es?'Precio mensual':'Monthly price'} · $30</dt><dd>{state(data.subscriptionBilling.monthlyPriceConfigured)}</dd></div><div><dt>{es?'Precio anual':'Annual price'} · $350</dt><dd>{state(data.subscriptionBilling.annualPriceConfigured)}</dd></div><div><dt>{es?'Webhook firmado':'Signed webhook'}</dt><dd>{state(data.subscriptionBilling.webhookConfigured)}</dd></div><div><dt>{es?'Suscripciones activas':'Active subscriptions'}</dt><dd>{s.activeSubscriptions}</dd></div><div><dt>{es?'Pagos vencidos':'Past-due payments'}</dt><dd>{s.pastDueSubscriptions}</dd></div></dl><p className="wfa-note">{data.subscriptionBilling.ready?(es?'Billing está listo para operar.':'Billing is ready to operate.'):(es?`Billing permanece bloqueado hasta completar ${data.subscriptionBilling.missing.length} requisito(s).`:`Billing remains blocked until ${data.subscriptionBilling.missing.length} requirement(s) are complete.`)}</p></section>
    <section className="wfa-card"><header><div><small>{es?'POLÍTICA DE CAPACIDAD':'CAPACITY POLICY'}</small><h2>{data.capacity.estimatedOpenings} {es?'espacios estimados':'estimated openings'}</h2></div><Badge value={data.capacity.level}/></header><Meter value={data.capacity.utilizationPercent} label={`${data.capacity.activeClients} ${es?'de':'of'} ${data.capacity.safeClientCapacity} ${es?'clientes':'clients'}`}/><p className="wfa-note">{es?'Este límite es un margen operacional configurable, no un límite técnico de Netlify.':'This limit is a configurable operating margin, not a Netlify technical limit.'}</p></section></div></>
}

function MetricBars({rows}:{rows:Array<[string,number]>}){const max=Math.max(1,...rows.map(([,v])=>Number(v)||0));return <div className="metric-bars">{rows.map(([label,value])=><div className="metric-row" key={label}><span>{label}</span><i><em style={{width:`${Math.round((Number(value)||0)/max*100)}%`}}/></i><b>{value}</b></div>)}</div>}
