import { useEffect, useMemo, useState, type FormEvent } from 'react'
import { acceptInvite, getUser, handleAuthCallback, login, logout, onAuthChange, type User } from '@netlify/identity'
import './webfactory-admin.css'
import { withAuthRetry } from './auth-retry'

type ClientRow={siteId:string;slug:string;businessName:string;ownerEmail:string;status:string;revision:number;catalogItems:number;employees:number;stripeStatus:string;calendarConnected:boolean;updatedAt:string;publicPath:string}
type OrderRow={orderId:string;businessName:string;customerEmail:string;status:string;amount:number;updatedAt:string;packageReady:boolean;adminEmailSent:boolean;customerEmailSent:boolean}
type AdminData={generatedAt:string;administrator:{email:string;name:string};summary:Record<string,number>;capacity:{level:string;safeClientCapacity:number;activeClients:number;estimatedOpenings:number;utilizationPercent:number;model:string};resources:{netlify:{plan:string;monthlyCredits:number|null;creditsUsed:number|null;utilizationPercent:number|null;productionDeployCreditCost:number;source:string;dashboardUrl:string};storage:{clientAssets:number;orderAssets:number;productionPackages:number;trackedObjects:number;bytesKnown:boolean};runtime:{deployId:string;deployContext:string;published:boolean;siteName:string;siteUrl:string}};integrations:{configured:number;total:number;configuration:Array<{name:string;configured:boolean}>};operations:{orderStatuses:Record<string,number>;transactionStatuses:Record<string,number>;stripeWebhookEvents:number;clientWebhookEvents:number;stuckOrders:OrderRow[];pendingTransactions:Array<{transactionId:string;siteId:string;kind:string;status:string;updatedAt:string}>};clients:ClientRow[];orders:OrderRow[]}
type Tab='overview'|'clients'|'operations'|'resources'

const api=()=>withAuthRetry(async()=>{const response=await fetch('/.netlify/functions/webfactory-admin-overview',{credentials:'include',cache:'no-store'});const result=await response.json();if(!response.ok||result.ok===false)throw new Error(result.message||'No se pudo cargar el Control Center.');return result as AdminData})
const date=(value:string)=>value?new Intl.DateTimeFormat('es-PR',{dateStyle:'medium',timeStyle:'short'}).format(new Date(value)):'—'
const statusLabel=(value:string)=>value.replaceAll('_',' ').toLowerCase()

function AdminLogin({onLogin}:{onLogin:(user:User)=>Promise<void>}){
  const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false)
  const submit=async(event:FormEvent)=>{event.preventDefault();setBusy(true);setError('');try{const current=await withAuthRetry(()=>login(email,password));await onLogin(current)}catch(e){setError(e instanceof Error?e.message:'No se pudo iniciar sesión.')}finally{setBusy(false)}}
  return <main className="wfa-login-page"><section className="wfa-login"><img src="/webfactory-pr-logo.png" alt="WebFactory PR"/><small>CONTROL CENTER</small><h1>Centro administrativo.</h1><p>Acceso exclusivo para supervisar clientes, integraciones, operaciones y capacidad de WebFactory.</p><form onSubmit={submit}><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} autoComplete="email" required/></label><label>Contraseña<input type="password" value={password} onChange={e=>setPassword(e.target.value)} autoComplete="current-password" required/></label><button disabled={busy}>{busy?'Verificando…':'Entrar de forma segura'}</button></form>{error&&<div className="wfa-alert danger">{error}</div>}</section></main>
}

function Meter({value,label}:{value:number;label:string}){return <div className="wfa-meter"><div><span>{label}</span><b>{value}%</b></div><i><em style={{width:`${Math.min(100,Math.max(0,value))}%`}}/></i></div>}
function Stat({label,value,note}:{label:string;value:string|number;note:string}){return <article className="wfa-stat"><span>{label}</span><strong>{value}</strong><small>{note}</small></article>}
function Badge({value}:{value:string}){const clean=value.toLowerCase();const kind=['active','published','live','in_production','completed'].includes(clean)?'good':['failed','critical','suspended','past_due'].includes(clean)?'bad':'pending';return <span className={`wfa-badge ${kind}`}>{statusLabel(value)}</span>}

export default function WebFactoryAdminPage(){
  const [user,setUser]=useState<User|null>(null);const [data,setData]=useState<AdminData|null>(null);const [loading,setLoading]=useState(true);const [refreshing,setRefreshing]=useState(false);const [error,setError]=useState('');const [tab,setTab]=useState<Tab>('overview');const [query,setQuery]=useState('');const [inviteToken,setInviteToken]=useState('');const [newPassword,setNewPassword]=useState('');const [acceptingInvite,setAcceptingInvite]=useState(false)
  const load=async(silent=false)=>{if(!silent)setRefreshing(true);setError('');try{setData(await api())}catch(e){setError(e instanceof Error?e.message:'No se pudo cargar el Control Center.')}finally{setRefreshing(false)}}
  useEffect(()=>{document.title='WebFactory Control Center';let unsubscribe=()=>{};(async()=>{try{const callback=await handleAuthCallback();if(callback?.type==='invite'&&callback.token){setInviteToken(callback.token);return}const current=callback?.user||await getUser();setUser(current);if(current)await load()}catch(e){setError(e instanceof Error?e.message:'No se pudo abrir el Control Center.')}finally{setLoading(false)}})();unsubscribe=onAuthChange((_event,current)=>setUser(current));return()=>unsubscribe()},[])
  useEffect(()=>{if(!user)return;const timer=window.setInterval(()=>load(true),5*60*1000);return()=>window.clearInterval(timer)},[user])
  const clients=useMemo(()=>{const term=query.trim().toLowerCase();return !term?(data?.clients||[]):(data?.clients||[]).filter(client=>[client.businessName,client.ownerEmail,client.slug,client.siteId].some(value=>value.toLowerCase().includes(term)))},[data,query])
  const signOut=async()=>{await logout();setUser(null);setData(null)}
  const acceptAdminInvite=async()=>{if(newPassword.length<8)return setError('Usa una contraseña de al menos 8 caracteres.');setAcceptingInvite(true);setError('');try{const invited=await acceptInvite(inviteToken,newPassword);if(!invited.email)throw new Error('La invitación no contiene un email válido.');const current=await withAuthRetry(()=>login(invited.email!,newPassword));setInviteToken('');setNewPassword('');setUser(current);await load()}catch(e){setError(e instanceof Error?e.message:'No se pudo activar el acceso administrativo.')}finally{setAcceptingInvite(false)}}
  if(loading)return <main className="wfa-login-page"><div className="wfa-loading">Abriendo Control Center seguro…</div></main>
  if(inviteToken)return <main className="wfa-login-page"><section className="wfa-login"><img src="/webfactory-pr-logo.png" alt="WebFactory PR"/><small>ACTIVACIÓN SEGURA</small><h1>Establece tu contraseña.</h1><p>Crea la contraseña privada para acceder al Centro Administrativo de WebFactory.</p><label>Nueva contraseña<input type="password" value={newPassword} onChange={e=>setNewPassword(e.target.value)} autoComplete="new-password" minLength={8} required/></label><button onClick={acceptAdminInvite} disabled={acceptingInvite}>{acceptingInvite?'Activando…':'Activar acceso administrativo'}</button>{error&&<div className="wfa-alert danger">{error}</div>}</section></main>
  if(!user)return <AdminLogin onLogin={async current=>{setUser(current);await load()}}/>
  if(!data)return <main className="wfa-login-page"><section className="wfa-login"><img src="/webfactory-pr-logo.png" alt="WebFactory PR"/><h1>Acceso no disponible</h1><div className="wfa-alert danger">{error||'No pudimos cargar la información administrativa.'}</div><button onClick={()=>load()}>Intentar nuevamente</button><button className="wfa-text-button" onClick={signOut}>Cerrar sesión</button></section></main>

  const s=data.summary;const capacityLabel={healthy:'Saludable',watch:'Observación',warning:'Precaución',critical:'Crítico'}[data.capacity.level]||data.capacity.level
  return <main className="wfa-dashboard">
    <aside className="wfa-sidebar"><img src="/webfactory-pr-logo.png" alt="WebFactory PR"/><div className="wfa-admin-id"><small>ADMINISTRADOR</small><strong>{data.administrator.name}</strong><span>{data.administrator.email}</span></div><nav>{([['overview','Resumen'],['clients','Clientes'],['operations','Operaciones'],['resources','Recursos']] as Array<[Tab,string]>).map(([id,label])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}>{label}</button>)}</nav><a href="/" target="_blank">Ver WebFactory ↗</a><button className="wfa-signout" onClick={signOut}>Cerrar sesión</button></aside>
    <section className="wfa-work"><header className="wfa-top"><div><small>WEBFACTORY CONTROL CENTER</small><h1>{tab==='overview'?'Estado general':tab==='clients'?'Clientes y tiendas':tab==='operations'?'Salud operacional':'Recursos y capacidad'}</h1><p>Actualizado {date(data.generatedAt)}</p></div><button onClick={()=>load()} disabled={refreshing}>{refreshing?'Actualizando…':'Actualizar datos'}</button></header>{error&&<div className="wfa-alert danger">{error}</div>}
      {tab==='overview'&&<><section className="wfa-stats"><Stat label="Clientes" value={s.clients} note={`${s.publishedSites} publicados`}/><Stat label="Pedidos WebFactory" value={s.productionOrders} note={`${s.completedOrders} completados`}/><Stat label="Stripe conectado" value={`${s.connectedStripe}/${s.clients}`} note="Cuentas listas"/><Stat label="Bloqueos" value={s.blockers} note="Requieren revisión"/></section><div className="wfa-grid"><section className="wfa-card capacity"><header><div><small>CAPACIDAD DE INCORPORACIÓN</small><h2>{capacityLabel}</h2></div><span className={`wfa-health ${data.capacity.level}`}/></header><Meter value={data.capacity.utilizationPercent} label="Clientes registrados vs. límite seguro"/><div className="wfa-capacity-numbers"><div><strong>{data.capacity.estimatedOpenings}</strong><span>espacios estimados</span></div><div><strong>{data.capacity.safeClientCapacity}</strong><span>límite operativo inicial</span></div></div><p>{data.capacity.model}</p></section><section className="wfa-card"><header><div><small>INTEGRACIONES</small><h2>{data.integrations.configured} de {data.integrations.total}</h2></div></header><div className="wfa-checks">{data.integrations.configuration.map(item=><div key={item.name}><i className={item.configured?'ready':''}/><span>{item.name}</span><b>{item.configured?'Lista':'Pendiente'}</b></div>)}</div></section></div><section className="wfa-card"><header><div><small>CLIENTES RECIENTES</small><h2>Actividad de tiendas</h2></div><button onClick={()=>setTab('clients')}>Ver todos</button></header><ClientTable clients={data.clients.slice(0,6)}/></section></>}
      {tab==='clients'&&<section className="wfa-card"><header><div><small>DIRECTORIO MULTI-CLIENTE</small><h2>{clients.length} tiendas</h2></div><input className="wfa-search" placeholder="Buscar negocio, email o enlace" value={query} onChange={e=>setQuery(e.target.value)}/></header><ClientTable clients={clients}/></section>}
      {tab==='operations'&&<><section className="wfa-stats"><Stat label="Eventos Stripe" value={data.operations.stripeWebhookEvents} note="WebFactory checkout"/><Stat label="Eventos de clientes" value={data.operations.clientWebhookEvents} note="Stripe Connect"/><Stat label="Pedidos detenidos" value={data.operations.stuckOrders.length} note="Reintento posible"/><Stat label="Transacciones pendientes" value={data.operations.pendingTransactions.length} note="Commerce runtime"/></section><div className="wfa-grid"><StatusCard title="Estados de pedidos" values={data.operations.orderStatuses}/><StatusCard title="Estados de transacciones" values={data.operations.transactionStatuses}/></div><section className="wfa-card"><header><div><small>ATENCIÓN OPERACIONAL</small><h2>Procesos que necesitan revisión</h2></div></header>{data.operations.stuckOrders.length===0&&data.operations.pendingTransactions.length===0?<div className="wfa-empty good">No encontramos trabajos detenidos.</div>:<div className="wfa-issues">{data.operations.stuckOrders.map(order=><article key={order.orderId}><div><strong>{order.businessName}</strong><span>{order.orderId}</span></div><Badge value={order.status}/><time>{date(order.updatedAt)}</time></article>)}{data.operations.pendingTransactions.map(item=><article key={item.transactionId}><div><strong>{item.kind}</strong><span>{item.transactionId}</span></div><Badge value={item.status}/><time>{date(item.updatedAt)}</time></article>)}</div>}</section></>}
      {tab==='resources'&&<><div className="wfa-grid"><section className="wfa-card"><header><div><small>NETLIFY</small><h2>{data.resources.netlify.plan}</h2></div><a href={data.resources.netlify.dashboardUrl} target="_blank" rel="noreferrer">Abrir uso oficial ↗</a></header>{data.resources.netlify.utilizationPercent===null?<div className="wfa-empty">El límite y consumo exactos permanecen en Netlify. Podemos conectarlos después mediante una autorización dedicada.</div>:<Meter value={data.resources.netlify.utilizationPercent} label={`${data.resources.netlify.creditsUsed} de ${data.resources.netlify.monthlyCredits} créditos`}/>}<dl><div><dt>Costo por deploy de producción</dt><dd>{data.resources.netlify.productionDeployCreditCost} créditos</dd></div><div><dt>Contexto actual</dt><dd>{data.resources.runtime.deployContext}</dd></div><div><dt>Publicado</dt><dd>{data.resources.runtime.published?'Sí':'No'}</dd></div><div><dt>Deploy ID</dt><dd>{data.resources.runtime.deployId||'No disponible'}</dd></div></dl></section><section className="wfa-card"><header><div><small>ALMACENAMIENTO RASTREADO</small><h2>{data.resources.storage.trackedObjects} objetos</h2></div></header><dl><div><dt>Imágenes de clientes</dt><dd>{data.resources.storage.clientAssets}</dd></div><div><dt>Archivos de pedidos</dt><dd>{data.resources.storage.orderAssets}</dd></div><div><dt>Production Packages</dt><dd>{data.resources.storage.productionPackages}</dd></div><div><dt>Tamaño exacto</dt><dd>{data.resources.storage.bytesKnown?'Disponible':'Se rastreará en nuevas cargas'}</dd></div></dl></section></div><section className="wfa-card"><header><div><small>POLÍTICA DE CAPACIDAD</small><h2>{data.capacity.estimatedOpenings} espacios estimados</h2></div><Badge value={data.capacity.level}/></header><Meter value={data.capacity.utilizationPercent} label={`${data.capacity.activeClients} de ${data.capacity.safeClientCapacity} clientes`}/><p className="wfa-note">Este límite es un margen operacional configurable de WebFactory. No representa un límite técnico fijo de Netlify. Antes de aceptar más clientes, también se debe revisar el consumo oficial de créditos.</p></section></>}
    </section>
  </main>
}

function ClientTable({clients}:{clients:ClientRow[]}){return <div className="wfa-table-wrap"><table><thead><tr><th>Negocio</th><th>Estado</th><th>Integraciones</th><th>Contenido</th><th>Actualizado</th><th/></tr></thead><tbody>{clients.map(client=><tr key={client.siteId}><td><strong>{client.businessName}</strong><span>{client.ownerEmail||client.slug}</span></td><td><Badge value={client.status}/></td><td><span>Stripe: {client.stripeStatus}</span><span>Calendar: {client.calendarConnected?'conectado':'pendiente'}</span></td><td><span>{client.catalogItems} artículos</span><span>{client.employees} empleados</span></td><td>{date(client.updatedAt)}</td><td>{client.publicPath&&<a href={client.publicPath} target="_blank">Abrir ↗</a>}</td></tr>)}</tbody></table>{clients.length===0&&<div className="wfa-empty">No hay tiendas que coincidan con la búsqueda.</div>}</div>}
function StatusCard({title,values}:{title:string;values:Record<string,number>}){const rows=Object.entries(values).sort((a,b)=>b[1]-a[1]);return <section className="wfa-card"><header><div><small>RESUMEN</small><h2>{title}</h2></div></header><div className="wfa-status-list">{rows.length?rows.map(([status,count])=><div key={status}><Badge value={status}/><strong>{count}</strong></div>):<div className="wfa-empty">Sin registros todavía.</div>}</div></section>}
