import './client-admin.css'
import {useEffect,useState} from 'react'
import WebsiteContentFields from './WebsiteContentFields'
import StorefrontPreview from './StorefrontPreview'
import {editablePreview} from './site-preview-data'
import {useUnsavedChanges} from './interaction-state'
export default function WebsiteEditor({site,lang,onSave,busy}:{site:any;lang:'es'|'en';onSave:(value:any)=>void;busy:boolean}){
 const [value,setValue]=useState(site.business);const [uploading,setUploading]=useState(false);const [error,setError]=useState('');const [device,setDevice]=useState<'mobile'|'desktop'>('mobile');const es=lang==='es'
 useUnsavedChanges(value,site.revision,setValue,lang,site.business)
 useEffect(()=>setValue(site.business),[site.siteId,site.revision])
 const upload=async(kind:'logo'|'hero'|'gallery',files:FileList|null)=>{
  if(!files?.length)return;setUploading(true);setError('')
  try{const keys:string[]=[];for(const file of Array.from(files)){const form=new FormData();form.append('siteId',site.siteId);form.append('file',file);const response=await fetch('/.netlify/functions/client-asset',{method:'POST',credentials:'include',body:form});const result=await response.json();if(!response.ok)throw Error(result.message);keys.push(result.assetKey)}setValue((previous:any)=>({...previous,...(kind==='gallery'?{galleryAssetKeys:[...(previous.galleryAssetKeys||[]),...keys].slice(0,100)}:{[kind+'AssetKey']:keys[0]})}))}catch(e){setError(e instanceof Error?e.message:'Upload failed.')}finally{setUploading(false)}
 }
 const image=(key:string)=>`/.netlify/functions/client-asset?siteId=${encodeURIComponent(site.siteId)}&key=${encodeURIComponent(key)}`
 return <section className="ca-panel wf-website-editor"><header><h2>{es?'Contenido de mi página':'My website content'}</h2><p>{es?'Edita el contenido y las imágenes conservando la estructura del template.':'Edit content and images while preserving the template structure.'}</p></header><WebsiteContentFields value={value} onChange={setValue} lang={lang}/><fieldset><legend>{es?'Logo, portada y galería':'Logo, hero and gallery'}</legend>{(['logo','hero','gallery'] as const).map(kind=><div key={kind}><label>{kind==='logo'?'Logo':kind==='hero'?(es?'Portada':'Hero'):(es?'Galería':'Gallery')}<input type="file" accept="image/jpeg,image/png,image/webp,image/gif" multiple={kind==='gallery'} disabled={uploading} onChange={e=>void upload(kind,e.target.files)}/></label>{kind!=='gallery'&&value[kind+'AssetKey']&&<div><img src={image(value[kind+'AssetKey'])} alt={kind} width="160"/><button type="button" onClick={()=>setValue({...value,[kind+'AssetKey']:''})}>{es?'Quitar':'Remove'}</button></div>}</div>)}<div className="wf-editor-gallery">{(value.galleryAssetKeys||[]).map((key:string,index:number)=><article key={key}><img src={image(key)} alt={`${es?'Galería':'Gallery'} ${index+1}`} width="120"/><button type="button" disabled={index===0} onClick={()=>{const list=[...value.galleryAssetKeys];[list[index-1],list[index]]=[list[index],list[index-1]];setValue({...value,galleryAssetKeys:list})}}>{es?'Mover antes':'Move earlier'}</button><button type="button" onClick={()=>setValue({...value,galleryAssetKeys:value.galleryAssetKeys.filter((_:string,i:number)=>i!==index)})}>{es?'Quitar':'Remove'}</button></article>)}</div></fieldset>{error&&<p role="alert">{error}</p>}<button type="button" disabled={busy||uploading} onClick={()=>onSave(value)}>{busy?(es?'Guardando…':'Saving…'):(es?'Guardar y publicar contenido':'Save and publish content')}</button><h3>{es?'Preview antes de guardar':'Preview before saving'}</h3><div role="group" aria-label={es?'Dispositivo':'Device'}>{(['mobile','desktop'] as const).map(d=><button key={d} aria-pressed={device===d} onClick={()=>setDevice(d)}>{d==='mobile'?(es?'Móvil':'Mobile'):'Desktop'}</button>)}</div><StorefrontPreview previewSite={editablePreview({...site,business:value})} lang={lang} device={device}/><p><a href={`/builder?edit=${encodeURIComponent(site.siteId)}`}>{es?'Cambiar template y funciones':'Change template and features'}</a></p></section>
}
