import {useCallback,useEffect,useRef,useState} from 'react'
import {PortalPanel} from './PortalPanel'
import './workforce.css'
type Shift={id:string;employeeId:string;locationId:string;start:string;end:string|null;breaks:{start:string;end:string|null}[];workedMinutes:number;breakMinutes:number;approvedAt?:string;correction?:{start:string;end:string}}
type View={events:{id:string;action:string;at:string;employeeId:string}[];totals:{todayMinutes:number;weekMinutes:number};enabled:boolean;paidBreaks:boolean;revision:number;serverNow:string;confirmedOperationIds:string[];admin:boolean;employeeId:string;shifts:Shift[];requests:{id:string;shiftId:string;employeeId:string;reason:string;start:string;end:string;status:string}[];employees:{id:string;name:string}[];locations:{id:string;name:string}[];bindings:{email:string;employeeId:string;locationId:string}[]}
export function WorkforcePanel({site,lang,mode='dashboard'}:{site:any;lang:'es'|'en';mode?:'dashboard'|'settings'}){
 const es=lang==='es',[view,setView]=useState<View|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[filter,setFilter]=useState(''),[branch,setBranch]=useState(''),[email,setEmail]=useState(''),[employee,setEmployee]=useState(''),[location,setLocation]=useState(''),[from,setFrom]=useState(''),[to,setTo]=useState('');
 const [closing,setClosing]=useState<{shiftId:string;reason:string}|null>(null);
 const [correction,setCorrection]=useState<{shiftId:string;start:string;end:string;reason:string}|null>(null);
 const pending=useRef<{body:any}|null>(null),gate=useRef(false),mounted=useRef(true),loadSequence=useRef(0);
 const load=useCallback(async()=>{const sequence=++loadSequence.current;const r=await fetch(`/.netlify/functions/client-workforce?siteId=${encodeURIComponent(site.siteId)}`,{credentials:'include',cache:'no-store'});const data=await r.json();if(!r.ok)throw Error(data.message|| (lang==='es'?'No se pudo cargar la asistencia.':'Attendance could not be loaded.'));if(!['shifts','employees','requests','bindings','locations','events'].every(key=>Array.isArray(data[key])))throw Error(lang==='es'?'Respuesta de asistencia inválida. Reintenta.':'Invalid attendance response. Retry.');if(mounted.current&&sequence===loadSequence.current){if(pending.current&&data.confirmedOperationIds?.includes(pending.current.body.operationId)){pending.current=null;setError('');setMessage(lang==='es'?'Registro verificado en el servidor.':'Record verified on the server.')}setView(data)}},[site.siteId,lang]);
 useEffect(()=>{mounted.current=true;load().catch(e=>setError(e.message));const timer=setInterval(()=>{if(!gate.current)load().catch(e=>setError(e.message))},30000);return()=>{mounted.current=false;clearInterval(timer)}},[load]);
 const mutate=async(action:string,extra:any={})=>{
  if(gate.current)return;gate.current=true;loadSequence.current++;setBusy(true);setError('');setMessage('');
  const body=pending.current?.body||{siteId:site.siteId,operationId:crypto.randomUUID(),action,...extra};pending.current={body};
  try{const r=await fetch('/.netlify/functions/client-workforce',{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await r.json();if(!r.ok){if([400,401,403,409].includes(r.status))pending.current=null;throw Error(data.message)}pending.current=null;setView(data);setMessage(es?'Registro confirmado por el servidor.':'Record confirmed by the server.');return true}
  catch(e){setError(e instanceof Error?e.message:String(e));load().catch(()=>{})}finally{gate.current=false;setBusy(false)}
 }
 const date=(v:string)=>new Date(v).toLocaleString(es?'es-PR':'en-US',{timeZone:site.settings?.timezone||'America/Puerto_Rico',dateStyle:'short',timeStyle:'short'}),hours=(n:number)=>`${Math.floor(n/60)}h ${n%60}m`;
 const names=new Map(view?.employees.map(e=>[e.id,e.name])||[]),active=view?.shifts.find(s=>s.employeeId===view.employeeId&&!s.end),onBreak=active?.breaks.some(b=>!b.end);
 const localDay=(v:string)=>new Intl.DateTimeFormat('en-CA',{timeZone:site.settings?.timezone||'America/Puerto_Rico',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(v));
 
 const rows=(view?.shifts||[]).filter(s=>(!filter||s.employeeId===filter)&&(!branch||s.locationId===branch)&&(!from||localDay(s.start)>=from)&&(!to||localDay(s.start)<=to));
 const exportUrl=`/.netlify/functions/client-workforce?siteId=${encodeURIComponent(site.siteId)}&format=csv&from=${from}&to=${to}&employeeId=${encodeURIComponent(filter)}&locationId=${encodeURIComponent(branch)}`;
 if(!view)return <PortalPanel className="ca-panel wf-workforce"><h2>{es?'Asistencia':'Workforce'}</h2>{error?<p role="alert">{error}<button onClick={()=>load().catch(e=>setError(e.message))}>{es?'Reintentar':'Retry'}</button></p>:<p role="status">{es?'Cargando registros…':'Loading records…'}</p>}</PortalPanel>;
 if(!view.enabled&&mode==='dashboard')return null;
 return <PortalPanel className="ca-panel wf-workforce"><header><div><small>{es?'ASISTENCIA DEL EQUIPO':'WORKFORCE MANAGEMENT'}</small><h2>{mode==='settings'?(es?'Configuración de asistencia':'Workforce settings'):(view.admin?(es?'Asistencia del negocio':'Business attendance'):(es?'Mi jornada':'My shift'))}</h2><p>{es?'Hora del servidor · Registros auditables · Actualización cada 30 segundos':'Server time · Auditable records · Refreshes every 30 seconds'}</p></div><span>{date(view.serverNow)}</span></header>
 {error&&<div role="alert" className="ca-error">{error}</div>}{message&&<div role="status" className="ca-success">{message}</div>}{pending.current&&!busy&&<div className="wf-attention"><p>{es?'La respuesta es incierta. Reintenta la misma operación; el servidor evita duplicados.':'The response is uncertain. Retry the same operation; the server prevents duplicates.'}</p><button onClick={()=>mutate('retry')}>{es?'Reintentar operación':'Retry operation'}</button></div>}
 {mode==='settings'&&view.admin?<><div className="wf-workforce-settings"><label><input type="checkbox" disabled={busy||!!pending.current} checked={view.enabled} onChange={e=>mutate('configure',{enabled:e.target.checked,paidBreaks:view.paidBreaks})}/>{es?'Habilitar asistencia':'Enable workforce'}</label><label><input type="checkbox" disabled={busy||!!pending.current} checked={view.paidBreaks} onChange={e=>mutate('configure',{enabled:view.enabled,paidBreaks:e.target.checked})}/>{es?'Descansos pagados para turnos nuevos':'Paid breaks for new shifts'}</label><p>{es?'Las reglas de descanso y compensación deben revisarse antes de aprobar horas. Cambiar reglas requiere cerrar los turnos activos.':'Review break and compensation rules before approving hours. Close active shifts before changing rules.'}</p></div><h3>{es?'Vincular acceso y empleado':'Link portal access and employee'}</h3><div className="wf-workforce-filters"><label>{es?'Miembro del portal':'Portal member'}<select value={email} onChange={e=>setEmail(e.target.value)}><option value="">{es?'Seleccionar':'Select'}</option>{site.members?.filter((m:any)=>['owner','manager','employee','cashier'].includes(m.role)).map((m:any)=><option key={m.email} value={m.email}>{m.email}</option>)}</select></label><label>{es?'Empleado':'Employee'}<select value={employee} onChange={e=>setEmployee(e.target.value)}><option value="">{es?'Seleccionar':'Select'}</option>{view.employees.map(e=><option key={e.id} value={e.id}>{e.name}</option>)}</select></label><label>{es?'Sucursal':'Branch'}<select value={location} onChange={e=>setLocation(e.target.value)}><option value="">{es?'Principal':'Main'}</option>{view.locations.map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select></label><button disabled={busy||!!pending.current||!email||!employee} onClick={()=>mutate('bind',{email,employeeId:employee,locationId:location})}>{es?'Guardar vinculación':'Save link'}</button></div><ul>{view.bindings.map(b=><li key={b.email}>{names.get(b.employeeId)} · {b.email} · {view.locations.find(l=>l.id===b.locationId)?.name|| (es?'Principal':'Main')}</li>)}</ul></>:<>
 {!view.enabled&&<p>{es?'Asistencia desactivada. Puedes habilitarla en Configuración y vincular los empleados existentes.':'Workforce is disabled. Enable it in Settings and link existing employees.'}</p>}
 {view.enabled&&<><div className="wf-workforce-metrics">{[[es?'Trabajando':'Working',view.shifts.filter(s=>!s.end&&!s.breaks.some(b=>!b.end)).length],[es?'En descanso':'On break',view.shifts.filter(s=>!s.end&&s.breaks.some(b=>!b.end)).length],[es?'Fuera de turno':'Off shift',view.employees.filter(e=>!view.shifts.some(s=>s.employeeId===e.id&&!s.end)).length],[es?'Minutos por aprobar':'Minutes awaiting approval',view.shifts.filter(s=>s.end&&!s.approvedAt).reduce((n,s)=>n+s.workedMinutes,0)]].map(([label,value])=><article key={label}><span>{label}</span><strong>{value}</strong></article>)}</div>
 {view.employeeId?<section className="wf-my-shift"><h3>{es?'Mi jornada':'My shift'}</h3><p>{active?(onBreak?(es?'En descanso':'On break'):(es?'Trabajando':'Working')):(es?'Fuera de turno':'Off shift')}{active&&` · ${date(active.start)} · ${hours(active.workedMinutes)}`}</p><p>{es?'Hoy':'Today'}: {hours(view.totals?.todayMinutes||0)} · {es?'Esta semana':'This week'}: {hours(view.totals?.weekMinutes||0)}</p><div className="wf-workforce-actions"><button disabled={busy||!!pending.current||!!active} onClick={()=>mutate('clock_in')}>{es?'Registrar entrada':'Clock in'}</button><button disabled={busy||!!pending.current||!active||!!onBreak} onClick={()=>mutate('start_break')}>{es?'Iniciar descanso':'Start break'}</button><button disabled={busy||!!pending.current||!onBreak} onClick={()=>mutate('end_break')}>{es?'Terminar descanso':'End break'}</button><button disabled={busy||!!pending.current||!active} onClick={()=>mutate('clock_out')}>{es?'Registrar salida':'Clock out'}</button></div></section>:<p>{es?'No tienes un empleado vinculado. Un administrador puede asignarlo en Configuración.':'No employee is linked to your login. An administrator can assign it in Settings.'}</p>}
 <h3>{es?'Estado por empleado':'Employee status'}</h3><div className="wf-employee-status">{view.employees.map(employee=>{const shift=view.shifts.find(s=>s.employeeId===employee.id&&!s.end);return <article key={employee.id}><strong>{employee.name}</strong><span>{shift?(shift.breaks.some(b=>!b.end)?(es?'En descanso':'On break'):(es?'Trabajando':'Working')):(es?'Fuera de turno':'Off shift')}</span>{shift&&<small>{date(shift.start)} · {hours(shift.workedMinutes)} · {view.locations.find(l=>l.id===shift.locationId)?.name||(es?'Principal':'Main')}</small>}</article>})}</div><p>{es?'Tardanzas: no se calculan sin un horario laboral programado. El calendario de citas no se usa como horario de asistencia.':'Lateness is not calculated without a scheduled work shift. The appointment calendar is not used as an attendance schedule.'}</p>
 <div className="wf-workforce-filters"><label>{es?'Empleado':'Employee'}<select value={filter} onChange={e=>setFilter(e.target.value)}><option value="">{es?'Todos los autorizados':'All authorized'}</option>{view.employees.map(e=><option key={e.id} value={e.id}>{e.name}</option>)}</select></label><label>{es?'Sucursal':'Branch'}<select value={branch} onChange={e=>setBranch(e.target.value)}><option value="">{es?'Todas':'All'}</option>{view.locations.map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select></label><label>{es?'Desde':'From'}<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>{es?'Hasta':'To'}<input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label><a href={exportUrl}>{es?'Exportar CSV':'Export CSV'}</a></div>
 <div className="wf-workforce-table" role="region" aria-label={es?'Historial de turnos':'Shift history'} tabIndex={0}><table><thead><tr>{[es?'Empleado':'Employee',es?'Sucursal':'Branch',es?'Entrada / salida':'In / out',es?'Horas / descanso':'Work / break',es?'Estado':'Status',es?'Acciones':'Actions'].map(t=><th scope="col" key={t}>{t}</th>)}</tr></thead><tbody>{rows.slice().reverse().map(s=><tr key={s.id}><td>{names.get(s.employeeId)||s.employeeId}</td><td>{view.locations.find(l=>l.id===s.locationId)?.name|| (es?'Principal':'Main')}</td><td>{date(s.start)}<br/>{s.end?date(s.end):(es?'Turno abierto':'Open shift')}{s.correction&&<small>{es?'Con corrección aprobada; original conservado':'Reviewed correction; original retained'}</small>}</td><td>{hours(s.workedMinutes)} / {hours(s.breakMinutes)}</td><td>{s.approvedAt?(es?'Aprobado':'Approved'):s.end?(es?'Pendiente':'Pending'):(s.breaks.some(b=>!b.end)?(es?'Descanso':'Break'):(es?'Trabajando':'Working'))}</td><td>{!s.end&&view.admin&&<button disabled={busy||!!pending.current} onClick={()=>setClosing({shiftId:s.id,reason:''})}>{es?'Cerrar turno con motivo':'Close shift with reason'}</button>}{s.end&&!s.approvedAt&&view.admin&&<button disabled={busy||!!pending.current} onClick={()=>mutate('approve',{shiftId:s.id})}>{es?'Aprobar horas':'Approve hours'}</button>}{s.end&&!s.approvedAt&&s.employeeId===view.employeeId&&<button disabled={busy||!!pending.current} onClick={()=>setCorrection({shiftId:s.id,start:new Date(Date.parse(s.start)-new Date(s.start).getTimezoneOffset()*60000).toISOString().slice(0,16),end:new Date(Date.parse(s.end!)-new Date(s.end!).getTimezoneOffset()*60000).toISOString().slice(0,16),reason:''})}>{es?'Solicitar corrección':'Request correction'}</button>}</td></tr>)}</tbody></table></div>{!rows.length&&<p>{es?'No hay turnos en este período.':'No shifts in this period.'}</p>}
 {closing&&<form className="wf-correction" onSubmit={e=>{e.preventDefault();mutate('close_shift',closing).then(ok=>{if(ok)setClosing(null)})}}><h3>{es?'Cerrar turno abierto':'Close open shift'}</h3><p>{es?'La salida utilizará la hora del servidor y quedará pendiente de revisión.':'Clock out uses server time and remains pending review.'}</p><label>{es?'Motivo':'Reason'}<textarea required minLength={5} maxLength={1000} value={closing.reason} onChange={e=>setClosing({...closing,reason:e.target.value})}/></label><div className="wf-workforce-actions"><button type="submit" disabled={busy||!!pending.current}>{es?'Confirmar cierre':'Confirm close'}</button><button type="button" onClick={()=>setClosing(null)}>{es?'Cancelar':'Cancel'}</button></div></form>}
 {correction&&<form className="wf-correction" onSubmit={e=>{e.preventDefault();mutate('request_correction',{shiftId:correction.shiftId,start:new Date(correction.start).toISOString(),end:new Date(correction.end).toISOString(),reason:correction.reason}).then(ok=>{if(ok)setCorrection(null)})}}><h3>{es?'Solicitar corrección':'Request correction'}</h3><p>{es?'Indica la hora local de tu dispositivo. Un administrador revisará la solicitud.':'Enter your device local time. An administrator will review the request.'}</p><div className="wf-workforce-filters"><label>{es?'Entrada':'Start'}<input type="datetime-local" required value={correction.start} onChange={e=>setCorrection({...correction,start:e.target.value})}/></label><label>{es?'Salida':'End'}<input type="datetime-local" required value={correction.end} onChange={e=>setCorrection({...correction,end:e.target.value})}/></label></div><label>{es?'Motivo':'Reason'}<textarea required minLength={5} maxLength={1000} value={correction.reason} onChange={e=>setCorrection({...correction,reason:e.target.value})}/></label><div className="wf-workforce-actions"><button disabled={busy||!!pending.current} type="submit">{es?'Enviar solicitud':'Submit request'}</button><button type="button" onClick={()=>setCorrection(null)}>{es?'Cancelar':'Cancel'}</button></div></form>}<h3>{es?'Solicitudes de corrección':'Correction requests'}</h3>{view.requests.length?view.requests.map(r=><article className="wf-correction" key={r.id}><strong>{names.get(r.employeeId)}</strong><p>{r.reason} · {date(r.start)} → {date(r.end)}</p><span>{r.status==='pending'?(es?'Pendiente':'Pending'):r.status==='accepted'?(es?'Aceptada':'Accepted'):(es?'Rechazada':'Rejected')}</span>{view.admin&&r.status==='pending'&&<div><button disabled={busy||!!pending.current} onClick={()=>mutate('review_correction',{requestId:r.id,accept:true})}>{es?'Aceptar':'Accept'}</button><button disabled={busy||!!pending.current} onClick={()=>mutate('review_correction',{requestId:r.id,accept:false})}>{es?'Rechazar':'Reject'}</button></div>}</article>):<p>{es?'No hay solicitudes.':'No requests.'}</p>}</>}
 </>}
 {mode==='dashboard'&&view.enabled&&<details><summary>{es?'Historial verificable de asistencia':'Attendance audit history'}</summary>{view.events?.slice(-50).reverse().map(event=><p key={event.id}>{date(event.at)} · {names.get(event.employeeId)|| (es?'Configuración':'Settings')} · {({clock_in:es?'Entrada':'Clock in',clock_out:es?'Salida':'Clock out',close_shift:es?'Cierre administrativo':'Administrative close',start_break:es?'Iniciar descanso':'Start break',end_break:es?'Terminar descanso':'End break',approve:es?'Aprobación de horas':'Hours approval',bind:es?'Vinculación':'Employee link',configure:es?'Configuración':'Settings',request_correction:es?'Solicitud de corrección':'Correction request',review_correction:es?'Revisión de corrección':'Correction review'} as Record<string,string>)[event.action]||event.action}</p>)}</details>}
 </PortalPanel>
}
